# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.the_world.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'the_world', 'function_path': 'animated_java:the_world/variants/barrage_trails/apply'}
execute on passengers if entity @s[tag=aj.the_world.bone.left_arm_lower] run function animated_java:the_world/variants/barrage_trails/zzz/0
execute on passengers if entity @s[tag=aj.the_world.bone.left_arm] run function animated_java:the_world/variants/barrage_trails/zzz/1
execute on passengers if entity @s[tag=aj.the_world.bone.right_arm_lower] run function animated_java:the_world/variants/barrage_trails/zzz/2
execute on passengers if entity @s[tag=aj.the_world.bone.right_arm] run function animated_java:the_world/variants/barrage_trails/zzz/3
execute on passengers if entity @s[tag=aj.the_world.bone.1] run function animated_java:the_world/variants/barrage_trails/zzz/4
execute on passengers if entity @s[tag=aj.the_world.bone.3] run function animated_java:the_world/variants/barrage_trails/zzz/5
execute on passengers if entity @s[tag=aj.the_world.bone.5] run function animated_java:the_world/variants/barrage_trails/zzz/6
execute on passengers if entity @s[tag=aj.the_world.bone.2] run function animated_java:the_world/variants/barrage_trails/zzz/7
execute on passengers if entity @s[tag=aj.the_world.bone.4] run function animated_java:the_world/variants/barrage_trails/zzz/8