# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.the_world_vfx.node.arm_right] at @s run function animated_java:the_world_vfx/variants/flurry_aura_3/zzz/apply_to_node_arm_right
execute on passengers if entity @s[tag=aj.the_world_vfx.node.knife] at @s run function animated_java:the_world_vfx/variants/flurry_aura_3/zzz/apply_to_node_knife
execute on passengers if entity @s[tag=aj.the_world_vfx.node.aura] at @s run function animated_java:the_world_vfx/variants/flurry_aura_3/zzz/apply_to_node_aura
execute on passengers if entity @s[tag=aj.the_world_vfx.node.star] at @s run function animated_java:the_world_vfx/variants/flurry_aura_3/zzz/apply_to_node_star
execute on passengers if entity @s[tag=aj.the_world_vfx.node.rage_mode] at @s run function animated_java:the_world_vfx/variants/flurry_aura_3/zzz/apply_to_node_rage_mode
execute on passengers if entity @s[tag=aj.the_world_vfx.node.arm_left] at @s run function animated_java:the_world_vfx/variants/flurry_aura_3/zzz/apply_to_node_arm_left
return 1