# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.toji.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'toji', 'function_path': 'animated_java:toji/animations/sneak_attack/play'}
tag @s add aj.toji.animation.sneak_attack.playing
scoreboard players set @s aj.sneak_attack.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:toji/animations/sneak_attack/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only