# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.explorer.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:explorer/as_root/pre_tick
execute if entity @s[tag=aj.explorer.animation.positive_spirit.playing] run function animated_java:explorer/animations/positive_spirit/zzz/on_tick
execute if entity @s[tag=aj.explorer.animation.triangulate.playing] run function animated_java:explorer/animations/triangulate/zzz/on_tick
execute if entity @s[tag=aj.explorer.animation.x_marks_the_spot.playing] run function animated_java:explorer/animations/x_marks_the_spot/zzz/on_tick
execute if entity @s[tag=aj.explorer.animation.retrace_start.playing] run function animated_java:explorer/animations/retrace_start/zzz/on_tick
execute if entity @s[tag=aj.explorer.animation.wormhole.playing] run function animated_java:explorer/animations/wormhole/zzz/on_tick
execute if entity @s[tag=aj.explorer.animation.walk.playing] run function animated_java:explorer/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.explorer.animation.chest_drop.playing] run function animated_java:explorer/animations/chest_drop/zzz/on_tick
execute if entity @s[tag=aj.explorer.animation.retrace_end.playing] run function animated_java:explorer/animations/retrace_end/zzz/on_tick
execute on passengers if entity @s[tag=aj.explorer.data] run function animated_java:explorer/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:explorer/as_root/post_tick