# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.billy_vfx.root] run return 0
execute if entity @s[tag=aj.billy_vfx.animation.appear.playing] run function animated_java:billy_vfx/animations/appear/zzz/on_tick
execute if entity @s[tag=aj.billy_vfx.animation.encourage.playing] run function animated_java:billy_vfx/animations/encourage/zzz/on_tick
execute if entity @s[tag=aj.billy_vfx.animation.range.playing] run function animated_java:billy_vfx/animations/range/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:billy_vfx/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~