# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:the_world/root/zzz/2 with entity @s data.locators.right_hand
function animated_java:the_world/root/zzz/4 with entity @s data.locators.left_hand
function animated_java:the_world/root/zzz/6 with entity @s data.cameras.camera