# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hatsune_miku_vfx.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'hatsune_miku_vfx', 'function_path': 'animated_java:hatsune_miku_vfx/animations/beam/next_frame'}
execute if score @s aj.beam.frame matches 17.. run scoreboard players set @s aj.beam.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.beam.frame
execute at @s run function animated_java:hatsune_miku_vfx/animations/beam/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.beam.frame 1