# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function custom:universal/control/movement {user:"customAbility.Gojo",objective:"customGojo.LapisBlueID",rig:"aj.gojo.root"}
function custom:abilities/gojo/moves/reset/all {user:"customAbility.Gojo",objective:"customGojo.LapisBlueID",rig:"gojo"}