# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.particles.root] run return 0
execute on passengers if entity @s[tag=aj.particles.data] unless data entity @s {data:{rigHash: 'e5affd881d67ad8f04f3f74494dfacc73ebb2af0cc02997c52b282ee9dcf236f'}} on vehicle run function animated_java:particles/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1