# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$execute store result storage animated_java:temp args.frame int 1 run scoreboard players set @s aj.npc_close.frame $(frame)
execute at @s run function animated_java:toji/animations/npc_close/zzz/set_frame with storage animated_java:temp args