# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.particles.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'particles', 'function_path': 'animated_java:particles/animations/titan_shift/next_frame'}
execute if score @s aj.titan_shift.frame matches 96.. run scoreboard players set @s aj.titan_shift.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.titan_shift.frame
execute at @s run function animated_java:particles/animations/titan_shift/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.titan_shift.frame 1