# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:avatar_vfx/animations/water_arrow_animation/zzz/frames/11_locator_constant
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^2.375 ^0.5625 rotated ~0 ~0 run function animated_java:avatar_vfx/animations/water_arrow_animation/zzz/frames/11_locator_arrow_location
data modify entity @s data merge value {"cameras":{},"locators":{"arrow_location":{"px":-6.888638245203862e-17,"py":2.375,"pz":0.5625,"ry":0,"rx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] run function animated_java:avatar_vfx/variants/water_arrow_5/apply