# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.7868f,0.5428f,-0.2938f,0.2982f,-0.0169f,0.4569f,0.8894f,0.4764f,0.617f,0.7047f,-0.3502f,0.2138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0.8655f,0.5971f,0.3232f,0.5102f,0.0186f,0.5025f,-0.9783f,0.6549f,-0.6787f,0.7752f,0.3853f,0.4891f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0.9441f,0.6514f,0.3526f,0.5034f,0.0203f,0.5482f,-1.0673f,0.6492f,-0.7404f,0.8457f,0.4203f,0.4803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.7868f,0.5428f,-0.2938f,0.2982f,-0.0169f,0.4569f,0.8894f,0.4764f,0.617f,0.7047f,-0.3502f,0.2138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.7868f,-0.4617f,-0.4096f,0.125f,-0.0169f,0.6795f,-0.7335f,0.7313f,0.617f,-0.5702f,-0.5424f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0.8655f,-0.5079f,0.4505f,-0.0265f,0.0186f,0.7474f,0.8068f,0.9542f,-0.6787f,-0.6272f,0.5967f,-0.1871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.7868f,-0.4617f,-0.4096f,0.125f,-0.0169f,0.6795f,-0.7335f,0.7313f,0.617f,-0.5702f,-0.5424f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.3562f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.1f,0f,0f,-0.125f,0f,1.1f,0f,0.7469f,0f,0f,1.1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.2f,0f,0f,-0.125f,0f,1.2f,0f,0.7344f,0f,0f,1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.3562f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.7313f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.1f,0f,0f,-0.125f,0f,1.1f,0f,1.0594f,0f,0f,1.1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.7313f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.9929f,0.117f,0.0194f,0f,0.117f,0.9397f,0.3214f,0.7313f,0.0194f,0.3214f,-0.9467f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9929f,0.117f,0.0194f,0f,0.117f,0.9397f,0.3214f,0.7313f,0.0194f,0.3214f,-0.9467f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9541f,0.2864f,0.0876f,0.0841f,0.1962f,0.8186f,-0.5398f,1.4067f,-0.2263f,-0.4978f,-0.8372f,0.231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6202f,0.1862f,-0.057f,0.1333f,-0.1275f,0.5321f,0.3508f,1.5474f,0.1471f,-0.3236f,0.5442f,0.1454f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9541f,0.2864f,0.0876f,0.0841f,0.1962f,0.8186f,-0.5398f,1.4067f,-0.2263f,-0.4978f,-0.8372f,0.231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8073f,0.5439f,0.2292f,-0.2992f,0.5742f,0.8136f,0.0919f,1.3624f,-0.1365f,0.2057f,-0.969f,0.2081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8073f,0.5252f,-0.2693f,-0.4358f,0.5742f,0.5933f,-0.5642f,1.1521f,-0.1365f,-0.6101f,-0.7805f,0.1312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8073f,0.5252f,-0.2693f,-0.4522f,0.5742f,0.5933f,-0.5642f,1.1336f,-0.1365f,-0.6101f,-0.7805f,0.1503f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0.2636f,0.6254f,0.9284f,-0.0528f,0.1056f,0.9356f,-0.6603f,1.7311f,-1.1144f,0.2366f,0.157f,0.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8073f,0.5439f,0.2292f,-0.2992f,0.5742f,0.8136f,0.0919f,1.3624f,-0.1365f,0.2057f,-0.969f,0.2081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9822f,-0.1292f,-0.1366f,0.4455f,-0.171f,0.312f,0.9346f,1.2747f,-0.0782f,0.9412f,-0.3285f,0.1936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9822f,-0.1308f,0.1351f,0.4777f,-0.171f,0.9201f,-0.3525f,1.2157f,-0.0782f,-0.3693f,-0.926f,-0.0827f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9822f,-0.1308f,0.1351f,0.4818f,-0.171f,0.9201f,-0.3525f,1.1869f,-0.0782f,-0.3693f,-0.926f,-0.0711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0.1571f,-0.1486f,-1.1295f,0.3869f,-1.0747f,0.3588f,-0.1967f,1.4161f,0.3778f,1.0824f,-0.0899f,0.6201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9822f,-0.1292f,-0.1366f,0.4455f,-0.171f,0.312f,0.9346f,1.2747f,-0.0782f,0.9412f,-0.3285f,0.1936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1419f,0.1345f,-0.0223f,0.1042f,-0.1345f,1.0806f,-0.3696f,1.5682f,-0.0223f,0.3696f,1.0888f,0.2862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0922f,0.1287f,0.0213f,0.0823f,0.1287f,1.0337f,0.3535f,1.392f,0.0213f,0.3535f,-1.0414f,0.226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.73125,"pz":0,"ry":1.1728321853,"rx":18.7472372511}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args