# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.toji.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:toji/as_root/pre_tick
execute if entity @s[tag=aj.toji.animation.flex.playing] run function animated_java:toji/animations/flex/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.arsenal_swap.playing] run function animated_java:toji/animations/arsenal_swap/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.charge.playing] run function animated_java:toji/animations/charge/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.sneak_attack.playing] run function animated_java:toji/animations/sneak_attack/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.berserk_mode.playing] run function animated_java:toji/animations/berserk_mode/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.heavenly_pact.playing] run function animated_java:toji/animations/heavenly_pact/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.overpower.playing] run function animated_java:toji/animations/overpower/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.frenzy_spin.playing] run function animated_java:toji/animations/frenzy_spin/zzz/on_tick
execute if entity @s[tag=aj.toji.animation.assasinate.playing] run function animated_java:toji/animations/assasinate/zzz/on_tick
execute on passengers if entity @s[tag=aj.toji.data] run function animated_java:toji/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:toji/as_root/post_tick