# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-1f,0f,0f,0f,0f,0.7835f,-0.6214f,-0.3685f,0f,-0.6214f,-0.7835f,-0.3328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-1f,0f,0f,0f,0f,0.2838f,-0.9589f,-0.6837f,0f,-0.9589f,-0.2838f,-0.5891f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,0.2188f,0f,-0.3757f,-0.9268f,-1.0167f,0f,-0.9268f,0.3757f,-0.3755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,0.2188f,0f,-0.3701f,-0.929f,-1.2256f,0f,-0.929f,0.3701f,-0.3932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.3757f,-0.9268f,-1.0167f,0f,-0.9268f,0.3757f,-0.3755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.3701f,-0.929f,-1.2256f,0f,-0.929f,0.3701f,-0.3932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0f,0f,0.4929f,-0.8701f,-1.3517f,0f,-0.8701f,-0.4929f,-0.9315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-1f,0f,0f,0f,0f,0.4929f,-0.8701f,-1.9951f,0f,-0.8701f,-0.4929f,-0.9369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.0264f,0f,0f,0f,-0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blb) {transformation: [-1f,0f,0f,0.2813f,0f,1f,0f,-2.1826f,0f,0f,-1f,-0.6869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backleftleg) {transformation: [-1f,0f,0f,0.2813f,0f,1f,0f,-2.0889f,0f,0f,-1f,-0.9369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(brb) {transformation: [-1f,0f,0f,-0.2812f,0f,1f,0f,-2.1826f,0f,0f,-1f,-0.6869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backrightleg) {transformation: [-1f,0f,0f,-0.2812f,0f,1f,0f,-2.0889f,0f,0f,-1f,-0.9369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0,"py":-0.3595884854,"pz":-0.362766966,"ry":0,"rx":-73.5127314815},"position":{"px":0,"py":-2.4951171875,"pz":-0.4368896484,"ry":0,"rx":0},"text_location":{"px":0,"py":-1.7451171875,"pz":-0.3118896484,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args