# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-1f,0f,0f,0f,0f,0.9959f,0.09f,1.8624f,0f,0.09f,-0.9959f,0.1694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-1f,0f,0f,0f,0f,0.8441f,-0.5361f,1.7932f,0f,-0.5361f,-0.8441f,-0.2309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,0.2188f,0f,-0.1845f,-0.9828f,1.4541f,0f,-0.9828f,0.1845f,-0.0473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,0.2188f,0f,-0.4153f,-0.9097f,1.2446f,0f,-0.9097f,0.4153f,-0.0547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.1845f,-0.9828f,1.4541f,0f,-0.9828f,0.1845f,-0.0473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.4153f,-0.9097f,1.2446f,0f,-0.9097f,0.4153f,-0.0547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0f,0f,0.5238f,-0.8518f,1.138f,0f,-0.8518f,-0.5238f,-0.5972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-1f,0f,0f,0f,0f,0.5238f,-0.8518f,0.4951f,0f,-0.8518f,-0.5238f,-0.6256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.4639f,0f,0f,0f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blb) {transformation: [-1f,0f,0f,0.2813f,0f,1f,0f,0.3076f,0f,0f,-1f,-0.3756f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backleftleg) {transformation: [-1f,0f,0f,0.2813f,0f,1f,0f,0.4014f,0f,0f,-1f,-0.6256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(brb) {transformation: [-1f,0f,0f,-0.2812f,0f,1f,0f,0.3076f,0f,0f,-1f,-0.3756f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backrightleg) {transformation: [-1f,0f,0f,-0.2812f,0f,1f,0f,0.4014f,0f,0f,-1f,-0.6256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0,"py":1.8887320698,"pz":0.1526573163,"ry":0,"rx":-32.4198250729},"position":{"px":0,"py":-0.0048828125,"pz":-0.1256103516,"ry":0,"rx":0},"text_location":{"px":0,"py":0.7451171875,"pz":-0.0006103516,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/snare_trigger/zzz/frames/9_locator_commands