# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-1f,0f,0f,0.875f,0f,0.8199f,-0.5725f,2.1064f,0f,-0.5725f,-0.8199f,-1.1548f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-1f,0f,0f,0.875f,0f,0.4352f,-0.9003f,1.8368f,0f,-0.9003f,-0.4352f,-1.4586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,1.0938f,0f,-0.4809f,-0.8768f,1.5176f,0f,-0.8768f,0.4809f,-1.2733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,1.0938f,0f,-0.7148f,-0.6994f,1.3194f,0f,-0.6994f,0.7148f,-1.2049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,0.6563f,0f,-0.4809f,-0.8768f,1.5176f,0f,-0.8768f,0.4809f,-1.2733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,0.6563f,0f,-0.7148f,-0.6994f,1.3194f,0f,-0.6994f,0.7148f,-1.2049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0.875f,0f,0.3951f,-0.9186f,1.1355f,0f,-0.9186f,-0.3951f,-1.7263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-1f,0f,0f,0.875f,0f,0.342f,-0.9397f,0.5f,0f,-0.9397f,-0.342f,-1.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.875,"py":2.1200057369,"pz":-1.1828874602,"ry":0,"rx":-64.2035741108}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args