# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-1f,0f,0f,0.875f,0f,0.7907f,-0.6123f,2.0875f,0f,-0.6123f,-0.7907f,-1.1284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-1f,0f,0f,0.875f,0f,0.4635f,-0.8861f,1.8276f,0f,-0.8861f,-0.4635f,-1.4406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,1.0938f,0f,-0.3562f,-0.9344f,1.5061f,0f,-0.9344f,0.3562f,-1.2536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,1.0938f,0f,-0.6502f,-0.7598f,1.3027f,0f,-0.7598f,0.6502f,-1.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,0.6563f,0f,-0.3562f,-0.9344f,1.5061f,0f,-0.9344f,0.3562f,-1.2536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,0.6563f,0f,-0.6502f,-0.7598f,1.3027f,0f,-0.7598f,0.6502f,-1.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0.875f,0f,0.4232f,-0.906f,1.1349f,0f,-0.906f,-0.4232f,-1.7297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-1f,0f,0f,0.875f,0f,0.3369f,-0.9415f,0.5f,0f,-0.9415f,-0.3369f,-1.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.875,"py":2.1019968466,"pz":-1.1560569801,"ry":0,"rx":-62.3885025915}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/encourage/zzz/frames/15_locator_constant