# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.toji.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'toji', 'function_path': 'animated_java:toji/animations/acrobatics_wall/next_frame'}
execute if score @s aj.acrobatics_wall.frame matches 36.. run scoreboard players set @s aj.acrobatics_wall.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.acrobatics_wall.frame
execute at @s run function animated_java:toji/animations/acrobatics_wall/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.acrobatics_wall.frame 1