# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.commands
function aj:yuji/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.constant
function aj:yuji/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.skins
function aj:yuji/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.sfx
function aj:yuji/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.mount
function aj:yuji/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args