# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bottom2) {transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0f,0f,-0.3437f,0f,1f,0f,1.4063f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,0f,0f,0.3438f,0f,1f,0f,1.4063f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom3) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.4375f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-1f,0f,0f,-0.1187f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom4) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.4375f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1f,0f,0f,0.1188f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:hatsune_miku/animations/beam/zzz/frames/0_locator_commands
data modify entity @s data merge value {"cameras":{},"locators":{"commands":{"posx":0,"posy":0,"posz":0,"roty":0,"rotx":0},"right_hand":{"posx":-0.34375,"posy":0.8437500000000001,"posz":-4.209723372069027e-17,"roty":0,"rotx":0},"left_hand":{"posx":0.34375,"posy":0.8437500000000001,"posz":4.209723372069027e-17,"roty":0,"rotx":0},"countdown":{"posx":0,"posy":2.21875,"posz":0,"roty":0,"rotx":0},"camera":{"posx":-3.7504808223887693e-16,"posy":1.5,"posz":3.0625,"roty":180,"rotx":0}}}