# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.yuji.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'yuji', 'function_path': 'animated_java:yuji/animations/king_of_curses/play'}
tag @s add aj.yuji.animation.king_of_curses.playing
scoreboard players set @s aj.king_of_curses.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:yuji/animations/king_of_curses/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only