# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.9756f,0.2197f,0.6938f,0f,0.2197f,-0.9756f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.9756f,0.2197f,0.6938f,0f,0.2197f,-0.9756f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0.0026f,0f,0f,0.0022f,0.8379f,0.5458f,1.3423f,0.0015f,0.5458f,-0.8379f,0.1461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0.0017f,0f,0.0004f,-0.0014f,0.5447f,-0.3547f,1.4756f,-0.001f,0.3547f,0.5447f,0.2328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0.0026f,0f,0f,0.0022f,0.8379f,0.5458f,1.3423f,0.0015f,0.5458f,-0.8379f,0.1461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.5145f,-0.4195f,-0.7478f,-0.3469f,0.8566f,-0.2918f,-0.4256f,1.2577f,-0.0397f,-0.8595f,0.5095f,0.127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.5145f,-0.7174f,-0.4696f,-0.2585f,0.8566f,-0.4554f,-0.2428f,1.3205f,-0.0397f,-0.5272f,0.8488f,0.3354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.0835f,0f,0f,0f,1.4572f,0f,0f,0f,0.4722f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.0716f,0f,0f,0f,1.4374f,0f,0f,0f,0.4732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.0597f,0f,0f,0f,1.4176f,0f,0f,0f,0.4741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.5145f,-0.7174f,-0.4696f,-0.2377f,0.8566f,-0.4554f,-0.2428f,1.3337f,-0.0397f,-0.5272f,0.8488f,0.3506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.86f,-0.4825f,0.5917f,-0.5227f,-0.4894f,-0.3356f,-0.985f,1.1354f,0.5859f,-0.9885f,0.0456f,-0.2333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.5145f,-0.4195f,-0.7478f,-0.3469f,0.8566f,-0.2918f,-0.4256f,1.2577f,-0.0397f,-0.8595f,0.5095f,0.127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9133f,-0.173f,0.3687f,0.3469f,-0.1579f,0.9849f,0.0708f,1.2577f,-0.3754f,0.0064f,-0.9268f,0.127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9133f,-0.0194f,0.4068f,0.3913f,-0.1579f,0.9376f,-0.3099f,1.0286f,-0.3754f,-0.3473f,-0.8593f,0.1153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.398f,0f,0f,0f,0.7849f,0f,0f,0f,0.2054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9133f,-0.0194f,0.4068f,0.3919f,-0.1579f,0.9376f,-0.3099f,1.0015f,-0.3754f,-0.3473f,-0.8593f,0.1253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.424f,-0.1989f,-1.0503f,0.2744f,-0.0814f,1.1326f,-0.1816f,1.6706f,1.0659f,0.0074f,-0.4317f,0.1297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9133f,-0.173f,0.3687f,0.3469f,-0.1579f,0.9849f,0.0708f,1.2577f,-0.3754f,0.0064f,-0.9268f,0.127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,1.1219f,-0.2527f,1.4974f,0f,0.2527f,1.1219f,0.181f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,1.0731f,0.2417f,1.3282f,0f,0.2417f,-1.0731f,0.1429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.23125,"py":1.3522544882,"pz":-0.0294772672,"ry":0,"rx":12.6920438957}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop/zzz/frames/2_locator_constant