# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.9993f,-0.0054f,-0.0359f,0f,-0.0071f,0.9988f,0.0484f,0.6938f,0.0356f,0.0486f,-0.9982f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9993f,-0.0054f,-0.0359f,0f,-0.0071f,0.9988f,0.0484f,0.6938f,0.0356f,0.0486f,-0.9982f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9828f,-0.1764f,-0.0549f,-0.0036f,-0.1821f,0.9749f,0.1283f,1.3578f,0.0309f,0.1361f,-0.9902f,0.0323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6388f,-0.1146f,0.0357f,-0.0316f,0.1184f,0.6337f,-0.0834f,1.5128f,-0.0201f,0.0885f,0.6436f,0.0539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9828f,-0.1764f,-0.0549f,-0.0036f,-0.1821f,0.9749f,0.1283f,1.3578f,0.0309f,0.1361f,-0.9902f,0.0323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8597f,0.2532f,-0.4436f,-0.3497f,0.3958f,0.8792f,-0.2653f,1.2687f,0.3229f,-0.4037f,-0.856f,0.0405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8597f,-0.3383f,-0.3827f,-0.4254f,0.3958f,0.0323f,-0.9178f,1.0409f,0.3229f,-0.9405f,0.1061f,0.1183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.3564f,0f,0f,0f,1.0404f,0f,0f,0f,0.3698f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.3365f,0f,0f,0f,1.0312f,0f,0f,0f,0.3623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.3167f,0f,0f,0f,1.0221f,0f,0f,0f,0.3549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8597f,-0.3383f,-0.3827f,-0.4156f,0.3958f,0.0323f,-0.9178f,1.04f,0.3229f,-0.9405f,0.1061f,0.1455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.5102f,0.2912f,0.9886f,-0.2436f,-0.3051f,1.011f,-0.4552f,1.6372f,-0.9844f,-0.4643f,-0.3713f,-0.1287f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8597f,0.2532f,-0.4436f,-0.3497f,0.3958f,0.8792f,-0.2653f,1.2687f,0.3229f,-0.4037f,-0.856f,0.0405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.909f,0.1018f,0.4041f,0.3436f,-0.3872f,-0.1522f,0.9093f,1.2736f,0.1541f,-0.9831f,-0.099f,0.0157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.909f,0.1406f,0.3923f,0.3211f,-0.3872f,-0.0631f,0.9198f,1.3114f,0.1541f,-0.9881f,-0.0029f,0.2429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.2836f,0f,0f,0f,1.3291f,0f,0f,0f,0.4995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.909f,0.1406f,0.3923f,0.3171f,-0.3872f,-0.0631f,0.9198f,1.3132f,0.1541f,-0.9881f,-0.0029f,0.2715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.4648f,0.117f,1.0454f,0.3862f,-1.0457f,-0.1751f,-0.4453f,1.2098f,0.1138f,-1.1306f,0.1772f,-0.3963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.909f,0.1018f,0.4041f,0.3436f,-0.3872f,-0.1522f,0.9093f,1.2736f,0.1541f,-0.9831f,-0.099f,0.0157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1492f,-0.0062f,0.0413f,-0.0044f,0.0082f,1.1486f,-0.0556f,1.5166f,-0.041f,0.0559f,1.1479f,0.04f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0993f,-0.0059f,-0.0395f,-0.0035f,-0.0078f,1.0987f,0.0532f,1.3434f,0.0392f,0.0535f,-1.098f,0.0316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.2214600792,"py":1.3389573302,"pz":-0.1504545352,"ry":357.9384804652,"rx":2.7729114411}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop/zzz/frames/70_locator_constant