# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.999f,-0.0057f,-0.0435f,0f,-0.0076f,0.999f,0.0432f,0.6938f,0.0432f,0.0435f,-0.9981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.999f,-0.0057f,-0.0435f,0f,-0.0076f,0.999f,0.0432f,0.6938f,0.0432f,0.0435f,-0.9981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9846f,-0.166f,-0.0551f,-0.0038f,-0.1716f,0.9777f,0.1207f,1.358f,0.0338f,0.1283f,-0.9912f,0.0289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.64f,-0.1079f,0.0358f,-0.0302f,0.1116f,0.6355f,-0.0785f,1.5134f,-0.022f,0.0834f,0.6443f,0.0493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9846f,-0.166f,-0.0551f,-0.0038f,-0.1716f,0.9777f,0.1207f,1.358f,0.0338f,0.1283f,-0.9912f,0.0289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8684f,0.2412f,-0.4333f,-0.3498f,0.3822f,0.8822f,-0.2749f,1.2687f,0.3159f,-0.4044f,-0.8583f,0.0401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8684f,-0.308f,-0.3887f,-0.4215f,0.3822f,0.0836f,-0.9203f,1.0416f,0.3159f,-0.9477f,0.0451f,0.1179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.3606f,0f,0f,0f,1.0274f,0f,0f,0f,0.3711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.3405f,0f,0f,0f,1.0185f,0f,0f,0f,0.3638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.3204f,0f,0f,0f,1.0097f,0f,0f,0f,0.3565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8684f,-0.308f,-0.3887f,-0.4126f,0.3822f,0.0836f,-0.9203f,1.0392f,0.3159f,-0.9477f,0.0451f,0.1453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.4983f,0.2774f,0.9986f,-0.2487f,-0.3162f,1.0146f,-0.4396f,1.6385f,-0.987f,-0.465f,-0.3633f,-0.1293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8684f,0.2412f,-0.4333f,-0.3498f,0.3822f,0.8822f,-0.2749f,1.2687f,0.3159f,-0.4044f,-0.8583f,0.0401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.9252f,0.0588f,0.3749f,0.3432f,-0.3719f,-0.0557f,0.9266f,1.2739f,0.0754f,-0.9967f,-0.0296f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.9252f,0.0913f,0.3683f,0.3306f,-0.3719f,0.0253f,0.9279f,1.2892f,0.0754f,-0.9955f,0.0574f,0.2407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.3058f,0f,0f,0f,1.2839f,0f,0f,0f,0.4994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.9252f,0.0913f,0.3683f,0.3279f,-0.3719f,0.0253f,0.9279f,1.2884f,0.0754f,-0.9955f,0.0574f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.4311f,0.0676f,1.064f,0.3679f,-1.0656f,-0.064f,-0.4277f,1.2506f,0.0341f,-1.1462f,0.0867f,-0.4076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.9252f,0.0588f,0.3749f,0.3432f,-0.3719f,-0.0557f,0.9266f,1.2739f,0.0754f,-0.9967f,-0.0296f,0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1489f,-0.0066f,0.05f,-0.0047f,0.0087f,1.1489f,-0.0497f,1.5168f,-0.0497f,0.05f,1.1478f,0.0358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0989f,-0.0063f,-0.0478f,-0.0037f,-0.0083f,1.0989f,0.0475f,1.3435f,0.0475f,0.0478f,-1.0979f,0.0283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.2198562921,"py":1.3383229307,"pz":-0.155443175,"ry":357.5048475359,"rx":2.4762720245}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop/zzz/frames/75_locator_commands
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop/zzz/frames/75_locator_constant