# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.999f,-0.0057f,-0.0435f,0f,-0.0076f,0.999f,0.0432f,0.75f,0.0432f,0.0435f,-0.9981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.999f,-0.0057f,-0.0435f,0f,-0.0076f,0.999f,0.0432f,0.75f,0.0432f,0.0435f,-0.9981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9846f,-0.166f,-0.0551f,-0.0041f,-0.1716f,0.9777f,0.1207f,1.4681f,0.0338f,0.1283f,-0.9912f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.64f,-0.1079f,0.0358f,-0.0326f,0.1116f,0.6355f,-0.0785f,1.6361f,-0.022f,0.0834f,0.6443f,0.0533f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9846f,-0.166f,-0.0551f,-0.0041f,-0.1716f,0.9777f,0.1207f,1.4681f,0.0338f,0.1283f,-0.9912f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8684f,0.2412f,-0.4333f,-0.3782f,0.3822f,0.8822f,-0.2749f,1.3716f,0.3159f,-0.4044f,-0.8583f,0.0434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8684f,-0.308f,-0.3887f,-0.4557f,0.3822f,0.0836f,-0.9203f,1.126f,0.3159f,-0.9477f,0.0451f,0.1275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.3898f,0f,0f,0f,1.1107f,0f,0f,0f,0.4012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.3681f,0f,0f,0f,1.1011f,0f,0f,0f,0.3933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.3464f,0f,0f,0f,1.0916f,0f,0f,0f,0.3854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8684f,-0.308f,-0.3887f,-0.446f,0.3822f,0.0836f,-0.9203f,1.1234f,0.3159f,-0.9477f,0.0451f,0.1571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.4983f,0.2774f,0.9986f,-0.2689f,-0.3162f,1.0146f,-0.4396f,1.7713f,-0.987f,-0.465f,-0.3633f,-0.1398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8684f,0.2412f,-0.4333f,-0.3782f,0.3822f,0.8822f,-0.2749f,1.3716f,0.3159f,-0.4044f,-0.8583f,0.0434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.9252f,0.0588f,0.3749f,0.3711f,-0.3719f,-0.0557f,0.9266f,1.3772f,0.0754f,-0.9967f,-0.0296f,0.011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.9252f,0.0913f,0.3683f,0.3574f,-0.3719f,0.0253f,0.9279f,1.3937f,0.0754f,-0.9955f,0.0574f,0.2602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.3306f,0f,0f,0f,1.388f,0f,0f,0f,0.5398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.9252f,0.0913f,0.3683f,0.3545f,-0.3719f,0.0253f,0.9279f,1.3929f,0.0754f,-0.9955f,0.0574f,0.2913f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.4311f,0.0676f,1.064f,0.3977f,-1.0656f,-0.064f,-0.4277f,1.352f,0.0341f,-1.1462f,0.0867f,-0.4407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.9252f,0.0588f,0.3749f,0.3711f,-0.3719f,-0.0557f,0.9266f,1.3772f,0.0754f,-0.9967f,-0.0296f,0.011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1489f,-0.0066f,0.05f,-0.0051f,0.0087f,1.1489f,-0.0497f,1.6398f,-0.0497f,0.05f,1.1478f,0.0387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0989f,-0.0063f,-0.0478f,-0.004f,-0.0083f,1.0989f,0.0475f,1.4524f,0.0475f,0.0478f,-1.0979f,0.0306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.2376824779,"py":1.4468356008,"pz":-0.1680466757,"ry":357.5048475359,"rx":2.4762720245}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop/zzz/frames/75_locator_commands
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop/zzz/frames/75_locator_constant