# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.9993f,-0.0047f,-0.0365f,0f,-0.0056f,0.9997f,0.0238f,0.6938f,0.0363f,0.024f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9993f,-0.0047f,-0.0365f,0f,-0.0056f,0.9997f,0.0238f,0.6938f,0.0363f,0.024f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9942f,-0.1023f,-0.0345f,-0.0031f,-0.1046f,0.9918f,0.073f,1.3584f,0.0268f,0.0762f,-0.9967f,0.016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6462f,-0.0665f,0.0224f,-0.0194f,0.068f,0.6447f,-0.0475f,1.5161f,-0.0174f,0.0495f,0.6479f,0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9942f,-0.1023f,-0.0345f,-0.0031f,-0.1046f,0.9918f,0.073f,1.3584f,0.0268f,0.0762f,-0.9967f,0.016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9461f,0.1897f,-0.2625f,-0.3493f,0.251f,0.9417f,-0.2239f,1.2698f,0.2047f,-0.2777f,-0.9386f,0.0265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.9461f,-0.0313f,-0.3224f,-0.3996f,0.251f,0.5583f,-0.7907f,1.0409f,0.2047f,-0.829f,-0.5204f,0.0748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.4123f,0f,0f,0f,0.9006f,0f,0f,0f,0.2942f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.3904f,0f,0f,0f,0.8948f,0f,0f,0f,0.2895f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.3685f,0f,0f,0f,0.889f,0f,0f,0f,0.2848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.9461f,-0.0313f,-0.3224f,-0.3987f,0.251f,0.5583f,-0.7907f,1.0248f,0.2047f,-0.829f,-0.5204f,0.0987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.3019f,0.2182f,1.088f,-0.2698f,-0.2575f,1.083f,-0.2886f,1.6645f,-1.0794f,-0.3194f,-0.2355f,-0.0899f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.9461f,0.1897f,-0.2625f,-0.3493f,0.251f,0.9417f,-0.2239f,1.2698f,0.2047f,-0.2777f,-0.9386f,0.0265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.831f,-0.3017f,0.4674f,0.3439f,-0.1922f,0.6327f,0.7502f,1.2736f,-0.5221f,-0.7132f,0.4678f,0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.831f,-0.2789f,0.4814f,0.4144f,-0.1922f,0.6681f,0.7188f,1.1283f,-0.5221f,-0.6898f,0.5016f,0.1669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.486f,0f,0f,0f,0.9556f,0f,0f,0f,0.3473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.831f,-0.2789f,0.4814f,0.4224f,-0.1922f,0.6681f,0.7188f,1.109f,-0.5221f,-0.6898f,0.5016f,0.1868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.5375f,-0.347f,0.9556f,0.2175f,-0.8627f,0.7276f,-0.2211f,1.5388f,-0.5379f,-0.8202f,-0.6004f,-0.2977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.831f,-0.3017f,0.4674f,0.3439f,-0.1922f,0.6327f,0.7502f,1.2736f,-0.5221f,-0.7132f,0.4678f,0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1492f,-0.0054f,0.0419f,-0.0039f,0.0064f,1.1497f,-0.0274f,1.5173f,-0.0418f,0.0276f,1.1489f,0.0198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0993f,-0.0052f,-0.0401f,-0.003f,-0.0061f,1.0997f,0.0262f,1.3439f,0.04f,0.0264f,-1.099f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.2217887857,"py":1.3349116055,"pz":-0.1664186378,"ry":357.9092355548,"rx":1.3643308876}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop/zzz/frames/79_locator_constant