# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_blue_hand1) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_purple_hand1) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_red_hand1) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom2) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom3) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom4) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.65f,0f,0f,0f,-8.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blue1) {transformation: [0f,0f,0f,-0.4219f,0f,0f,0f,33.261f,0f,0f,0f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:gojo/animations/hollow_purple_200/zzz/frames/79_locator_commands
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:gojo/animations/hollow_purple_200/zzz/frames/79_locator_commands
data modify entity @s data merge value {"cameras":{},"locators":{"blue_hand":{"posx":-0.000001950591128974906,"posy":13.649972771485105,"posz":-8.448469513722795,"roty":340.90207250326034,"rotx":-10.70378480415727},"purple_hand":{"posx":-0.000001950591128974906,"posy":13.649972771485105,"posz":-8.448469513722795,"roty":340.90207250326034,"rotx":-10.703784804157266},"red_hand":{"posx":-0.000001950591128974906,"posy":13.649972771485105,"posz":-8.448469513722795,"roty":340.90207250326034,"rotx":-10.703784804157266},"blue":{"posx":-0.42187499999999994,"posy":33.26101213122333,"posz":-0.25000000000000006,"roty":0,"rotx":0}}}