# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.the_world_projectiles.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'the_world_projectiles', 'function_path': 'animated_java:the_world_projectiles/animations/knife/next_frame'}
execute if score @s aj.knife.frame matches 21.. run scoreboard players set @s aj.knife.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.knife.frame
execute at @s run function animated_java:the_world_projectiles/animations/knife/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.knife.frame 1