# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:item_display ^0 ^0.75 ^0 {Tags:["aj.global.bone.upper_body.child","aj.global.bone.upper_body.child.locator","aj.global.bone.upper_body.decendant","aj.global.bone.upper_body.decendant.locator","aj.global.bone.upper_body.tree","aj.global.bone.yuji.decendant","aj.global.bone.yuji.decendant.locator","aj.global.bone.yuji.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.mount","aj.new","aj.yuji.bone.upper_body.child","aj.yuji.bone.upper_body.child.locator","aj.yuji.bone.upper_body.decendant","aj.yuji.bone.upper_body.decendant.locator","aj.yuji.bone.upper_body.tree","aj.yuji.bone.yuji.decendant","aj.yuji.bone.yuji.decendant.locator","aj.yuji.bone.yuji.tree","aj.yuji.entity","aj.yuji.locator","aj.yuji.locator.mount","aj.yuji.node","aj.yuji.node.mount"]}
execute as @n[ type=minecraft:item_display, tag=aj.yuji.locator.mount, tag=aj.new, distance=..7 ] run function animated_java:yuji/zzz/summon/as_data_entity/as_locator/mount
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_mount set from storage animated_java:gu out
data modify entity @s data.locators.mount.uuid set from storage animated_java:gu out
summon minecraft:item_display ^0 ^0 ^0 {Tags:["aj.global.camera","aj.global.entity","aj.global.node","aj.global.node.camera","aj.global.root.child","aj.global.root.child.camera","aj.new","aj.yuji.camera","aj.yuji.camera.camera","aj.yuji.entity","aj.yuji.node","aj.yuji.node.camera"], teleport_duration: 2}
execute as @n[ type=minecraft:item_display, tag=aj.yuji.camera.camera, tag=aj.new, distance=..4 ] run function animated_java:yuji/zzz/summon/as_data_entity/as_camera/camera
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.camera_camera set from storage animated_java:gu out
data modify entity @s data.cameras.camera.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.lower_left_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lower_left_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.leggings_lower_r] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_leggings_lower_r set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.boots_r] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_boots_r set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.lower_left_leg_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lower_left_leg_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.left_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.leggings_upper_r] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_leggings_upper_r set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.left_leg_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.lower_right_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lower_right_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.leggings_lower_l] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_leggings_lower_l set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.boots_l] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_boots_l set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.lower_right_leg_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lower_right_leg_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.right_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.leggings_upper_l] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_leggings_upper_l set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.right_leg_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.waist] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_waist set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.waist_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_waist_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.helmet] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_helmet set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.head_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.right_forearm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_forearm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.right_forearm_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_forearm_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.chestplate_arm_r] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_chestplate_arm_r set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.right_arm_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.left_forearm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_forearm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.left_forearm_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_forearm_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.chestplate_arm_l] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_chestplate_arm_l set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.left_arm_group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm_group set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.chestplate_body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_chestplate_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.leggings_pants] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_leggings_pants set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.yuji.node.fuga] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_fuga set from storage animated_java:gu out