# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.toji.locator', 'aj.toji.locator.head']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:toji/zzz/2
data modify entity @s data.locators.head.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.toji.locator', 'aj.toji.locator.mount']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:toji/zzz/3
data modify entity @s data.locators.mount.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.blade2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blade2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.chain2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.bottom2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.rightarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.chain] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.blade] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blade set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.bottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.leftarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.bottom3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.rightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.bottom4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.toji.bone.leftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftleg set from storage aj:uuid main.out