# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.majin_kick_fall.frame matches 201.. run scoreboard players set @s aj.majin_kick_fall.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.majin_kick_fall.frame
execute at @s run function animated_java:yuji/animations/majin_kick_fall/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.majin_kick_fall.frame 1