# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:president rig_hash set value 'ea883843f38d0fef79211246cfc251fef9f03b803abf73ffcdf35fbf66af4275'
scoreboard objectives add aj.kidnap.frame dummy
scoreboard objectives add aj.self_kidnap.frame dummy
scoreboard objectives add aj.shake_key.frame dummy
scoreboard objectives add aj.refreshments.frame dummy
scoreboard objectives add aj.turtle_idle.frame dummy
scoreboard objectives add aj.turtle_walk.frame dummy