# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_middle) {transformation: [-19.0833f,0f,0f,0f,0f,19.0833f,0f,0f,0f,0f,-19.0833f,-3.0813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-10f,0f,0f,0f,0f,10f,0f,0f,0f,0f,-10f,-32.5812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:hatsune_miku_vfx/animations/beam_fire/zzz/frames/20_locator_commands
execute on vehicle unless entity @s[tag=aj.transforms_only] run function animated_java:hatsune_miku_vfx/variants/beam3/apply