# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.domain_clash.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'domain_clash', 'function_path': 'animated_java:domain_clash/animations/clash/next_frame'}
execute if score @s aj.clash.frame matches 922.. run scoreboard players set @s aj.clash.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.clash.frame
execute at @s run function animated_java:domain_clash/animations/clash/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.clash.frame 1