# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouthb) {transformation: [-1f,0f,0f,0f,0f,0.9724f,-0.2335f,-0.512f,0f,-0.2335f,-0.9724f,0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head3) {transformation: [-1f,0f,0f,0f,0f,0.6532f,-0.7572f,-0.6939f,0f,-0.7572f,-0.6532f,-0.3508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0.2188f,0f,0.0027f,-1f,-1.0781f,0f,-1f,-0.0027f,-0.1548f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontleftleg) {transformation: [-1f,0f,0f,0.2188f,0f,0.0354f,-0.9994f,-1.2621f,0f,-0.9994f,-0.0354f,-0.2551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom2) {transformation: [-1f,0f,0f,-0.2187f,0f,0.0027f,-1f,-1.0781f,0f,-1f,-0.0027f,-0.1548f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontrightleg2) {transformation: [-1f,0f,0f,-0.2187f,0f,0.0354f,-0.9994f,-1.2621f,0f,-0.9994f,-0.0354f,-0.2551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front) {transformation: [-1f,0f,0f,0f,0f,0.6407f,-0.7678f,-1.2898f,0f,-0.7678f,-0.6407f,-0.8073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,0.6407f,-0.7678f,-1.9219f,0f,-0.7678f,-0.6407f,-0.9277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_waist) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-8192.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(item_display_helmet) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-0.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_right_forearm) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-6144.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(item_display_chestplate_arm_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-1024.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_forearm) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-7168.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(item_display_chestplate_arm_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-2048.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(item_display_chestplate_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_leggings_pants) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_leggings_lower_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_boots_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_right_leg) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-9216.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(item_display_leggings_upper_l) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-4096.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(item_display_leggings_lower_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_boots_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_left_leg) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-10240.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(item_display_leggings_upper_r) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.9531f,0f,0f,0f,-0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation:[0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,-5120.9531f,0.0f,0.0f,0.0f,-0.3027f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_blb) {transformation: [-1f,0f,0f,0.2813f,0f,1f,0f,-2.1094f,0f,0f,-1f,-0.6777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backleftleg) {transformation: [-1f,0f,0f,0.2813f,0f,1f,0f,-2.0156f,0f,0f,-1f,-0.9277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_brb) {transformation: [-1f,0f,0f,-0.2812f,0f,1f,0f,-2.1094f,0f,0f,-1f,-0.6777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backrightleg) {transformation: [-1f,0f,0f,-0.2812f,0f,1f,0f,-2.0156f,0f,0f,-1f,-0.9277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:billy/animations/snare_trigger/zzz/frames/3_locator_commands
data modify entity @s data merge value {"cameras":{},"locators":{"mouth":{"px":1.3665969179390001e-18,"py":-0.49159867058122886,"pz":-0.011159110683100493,"ry":0,"rx":-49.21875},"position":{"px":5.2382353322904366e-17,"py":-2.421875,"pz":-0.427734375,"ry":0,"rx":0},"text_location":{"px":3.707426833356245e-17,"py":-1.671875,"pz":-0.302734375,"ry":0,"rx":0}}}