# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:text_display/animations/pause_all
tag @s add aj.text_display.animation.homeland.playing
scoreboard players set @s aj.homeland.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:text_display/animations/homeland/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only