# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-1f,0f,0f,0.875f,0f,0.999f,0.0442f,0.6599f,0f,0.0442f,-0.999f,0.0556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-1f,0f,0f,0.875f,0f,0.999f,0.0442f,0.8326f,0f,0.0442f,-0.999f,-0.3121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,1.0938f,0f,0.9997f,-0.0224f,0.3112f,0f,-0.0224f,-0.9997f,-0.5041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,1.0938f,0f,0.9997f,-0.0224f,0.4007f,0f,-0.0224f,-0.9997f,-0.6936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,0.6563f,0f,0.9997f,-0.0224f,0.3112f,0f,-0.0224f,-0.9997f,-0.5041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,0.6563f,0f,0.9997f,-0.0224f,0.4007f,0f,-0.0224f,-0.9997f,-0.6936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0.875f,0f,0.9999f,0.0149f,0.8125f,0f,0.0149f,-0.9999f,-1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.875,"py":0.6910941847,"pz":0.0569874436,"ry":0,"rx":2.534848}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args