# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.vfx_billboard.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'vfx_billboard', 'function_path': 'animated_java:vfx_billboard/animations/pause_all'}
tag @s remove aj.vfx_billboard.animation.lapis_blue.playing
tag @s remove aj.vfx_billboard.animation.reversal_red.playing
tag @s remove aj.vfx_billboard.animation.hollow_purple.playing
tag @s remove aj.vfx_billboard.animation.light_beam.playing