# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.375f,-1f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,-1.1f,6.75f,0f,1.1f,0f,0.7656f,1.1f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,-1.2f,6.75f,0f,1.2f,0f,0.7531f,1.2f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.375f,-1f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.75f,-1f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,-1.1f,6.75f,0f,1.1f,0f,1.0781f,1.1f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.75f,-1f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.375f,-1f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,-1.1f,6.75f,0f,1.1f,0f,0.7656f,1.1f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,-1.2f,6.75f,0f,1.2f,0f,0.7531f,1.2f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.375f,-1f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.75f,-1f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,-1.1f,6.75f,0f,1.1f,0f,1.0781f,1.1f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.75f,-1f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.75f,-1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,0.75f,-1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.4688f,-1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,-0.65f,6.75f,0f,0.65f,0f,1.6406f,0.65f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.4688f,-1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.375f,-1f,0f,0f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.125f,-1f,0f,0f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.0938f,-1f,0f,0f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [1.15f,0f,0f,6.75f,0f,1.15f,0f,1.8281f,0f,0f,1.15f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.375f,-1f,0f,0f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.375f,-1f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.125f,-1f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.0938f,-1f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-1.15f,0f,0f,6.75f,0f,1.15f,0f,1.8281f,0f,0f,-1.15f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0f,0f,1f,6.75f,0f,1f,0f,1.375f,-1f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,-1.15f,6.75f,0f,1.15f,0f,1.6406f,1.15f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,1.1f,6.75f,0f,1.1f,0f,1.4531f,-1.1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fuga) {transformation: [0f,0f,-1f,-0.375f,0f,1f,0f,0.8438f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":0,"py":0,"pz":0,"ry":0,"rx":0,"rz":0}},"locators":{"commands":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"constant":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"skins":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"sfx":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"mount":{"px":6.75,"py":0.75,"pz":0,"ry":90,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] run function aj:yuji/variants/sukuna/apply