# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:eren/animations/strafe_right/zzz/apply_frame {frame: 55}
scoreboard players add @s aj.strafe_right.frame 1