# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.9765f,0.0022f,-0.2155f,0.1482f,-0.0054f,0.9994f,0.0344f,0.3515f,0.2155f,0.0348f,-0.9759f,0.0209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.0741f,0.0024f,0.2371f,0.1489f,0.0059f,1.0993f,-0.0378f,0.7126f,-0.237f,0.0382f,1.0735f,0.0334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.1718f,0.0026f,0.2587f,0.1489f,0.0065f,1.1993f,-0.0413f,0.701f,-0.2586f,0.0417f,1.1711f,0.033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.9765f,0.0022f,-0.2155f,0.1482f,-0.0054f,0.9994f,0.0344f,0.3515f,0.2155f,0.0348f,-0.9759f,0.0209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9765f,-0.0938f,-0.1941f,0.1156f,-0.0054f,0.9107f,-0.413f,0.6674f,0.2155f,-0.4023f,-0.8898f,-0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.0741f,-0.1032f,0.2135f,0.0872f,0.0059f,1.0018f,0.4543f,0.9438f,-0.237f,-0.4425f,0.9788f,-0.2407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.9765f,-0.0938f,-0.1941f,0.1156f,-0.0054f,0.9107f,-0.413f,0.6674f,0.2155f,-0.4023f,-0.8898f,-0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9997f,0.0143f,-0.0216f,-0.1156f,0.0217f,0.918f,-0.3961f,0.6674f,0.0142f,-0.3964f,-0.918f,-0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.9997f,0.0225f,-0.013f,-0.1206f,0.0217f,0.9984f,0.0528f,0.349f,0.0142f,0.0525f,-0.9985f,0.0189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0996f,0.0247f,0.0143f,-0.1125f,-0.0239f,1.0982f,-0.0581f,0.7097f,-0.0156f,0.0578f,1.0984f,0.0378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1996f,0.027f,0.0156f,-0.1127f,-0.0261f,1.198f,-0.0634f,0.6982f,-0.017f,0.063f,1.1982f,0.0372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.9997f,0.0225f,-0.013f,-0.1206f,0.0217f,0.9984f,0.0528f,0.349f,0.0142f,0.0525f,-0.9985f,0.0189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0996f,0.0158f,0.0238f,-0.1113f,-0.0239f,1.0098f,0.4357f,0.946f,-0.0156f,-0.4361f,1.0098f,-0.239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.9997f,0.0143f,-0.0216f,-0.1156f,0.0217f,0.918f,-0.3961f,0.6674f,0.0142f,-0.3964f,-0.918f,-0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.8136f,0.5814f,0.6674f,0f,0.5814f,-0.8136f,-0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.8136f,0.5814f,0.6674f,0f,0.5814f,-0.8136f,-0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.7087f,0.7055f,1.2083f,0f,0.7055f,-0.7087f,0.2679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,0.4607f,-0.4586f,1.321f,0f,0.4586f,0.4607f,0.3801f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,0.7087f,0.7055f,1.2083f,0f,0.7055f,-0.7087f,0.2679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.1737f,-0.7457f,-0.6432f,-0.3469f,0.8038f,0.4847f,-0.345f,1.1378f,0.569f,-0.4571f,0.6836f,0.2175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.1737f,-0.9299f,-0.3243f,-0.1797f,0.8038f,0.3241f,-0.4989f,1.021f,0.569f,-0.1741f,0.8037f,0.3314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,0.0654f,0f,0f,0f,0.9538f,0f,0f,0f,0.3896f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,0.0614f,0f,0f,0f,0.9352f,0f,0f,0f,0.3764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,0.0574f,0f,0f,0f,0.9166f,0f,0f,0f,0.3633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.1737f,-0.9299f,-0.3243f,-0.1529f,0.8038f,0.3241f,-0.4989f,1.0117f,0.569f,-0.1741f,0.8037f,0.3364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.7397f,-0.8576f,-0.1997f,-0.6594f,-0.3967f,0.5574f,-0.9243f,1.3409f,0.7861f,-0.5256f,-0.6544f,0.0259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.1737f,-0.7457f,-0.6432f,-0.3469f,0.8038f,0.4847f,-0.345f,1.1378f,0.569f,-0.4571f,0.6836f,0.2175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.4001f,0.4676f,0.7882f,0.3469f,-0.4359f,0.8536f,-0.2852f,1.1378f,-0.8062f,-0.2295f,0.5453f,0.2175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.4001f,0.89f,0.2189f,0.2509f,-0.4359f,0.3948f,-0.8088f,0.9271f,-0.8062f,0.2282f,0.5459f,0.2838f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.0192f,0f,0f,0f,0.8244f,0f,0f,0f,0.2261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.4001f,0.89f,0.2189f,0.2252f,-0.4359f,0.3948f,-0.8088f,0.9157f,-0.8062f,0.2282f,0.5459f,0.2772f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.9065f,0.5378f,0.4601f,0.5429f,0.3279f,0.9817f,-0.5013f,1.4955f,-0.6271f,-0.2639f,-0.9271f,0.1213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.4001f,0.4676f,0.7882f,0.3469f,-0.4359f,0.8536f,-0.2852f,1.1378f,-0.8062f,-0.2295f,0.5453f,0.2175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,0.9357f,-0.6686f,1.3377f,0f,0.6686f,0.9357f,0.3603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,0.895f,0.6395f,1.1966f,0f,0.6395f,-0.895f,0.2595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":0.990625,"py":1.41875,"pz":1.3031250000000003,"ry":136.75,"rx":0,"rz":0}},"locators":{"dio_shoulder":{"px":0.23125,"py":1.2856285128,"pz":0.1099725114,"ry":0,"rx":35.5493164063}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/rage_mode/zzz/frames/11_locator_constant