# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.9776f,0.0019f,-0.2104f,0.1467f,-0.0053f,0.9994f,0.0336f,0.3507f,0.2104f,0.034f,-0.977f,0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.0754f,0.0021f,0.2315f,0.1474f,0.0058f,1.0994f,-0.037f,0.7118f,-0.2314f,0.0373f,1.0747f,0.033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.1731f,0.0023f,0.2525f,0.1474f,0.0063f,1.1993f,-0.0403f,0.7002f,-0.2525f,0.0407f,1.1724f,0.0326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.9776f,0.0019f,-0.2104f,0.1467f,-0.0053f,0.9994f,0.0336f,0.3507f,0.2104f,0.034f,-0.977f,0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9776f,-0.0896f,-0.1904f,0.1156f,-0.0053f,0.9149f,-0.4036f,0.668f,0.2104f,-0.3936f,-0.8949f,-0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.0754f,-0.0986f,0.2094f,0.0884f,0.0058f,1.0064f,0.444f,0.9457f,-0.2314f,-0.433f,0.9844f,-0.2353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.9776f,-0.0896f,-0.1904f,0.1156f,-0.0053f,0.9149f,-0.4036f,0.668f,0.2104f,-0.3936f,-0.8949f,-0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9997f,0.0142f,-0.021f,-0.1156f,0.0212f,0.9218f,-0.3871f,0.668f,0.0138f,-0.3874f,-0.9218f,-0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.9997f,0.0219f,-0.0127f,-0.1206f,0.0212f,0.9984f,0.0515f,0.3483f,0.0138f,0.0512f,-0.9986f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0996f,0.0241f,0.014f,-0.1126f,-0.0233f,1.0983f,-0.0567f,0.709f,-0.0152f,0.0564f,1.0984f,0.0371f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1996f,0.0263f,0.0153f,-0.1129f,-0.0255f,1.1981f,-0.0618f,0.6975f,-0.0166f,0.0615f,1.1983f,0.0365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.9997f,0.0219f,-0.0127f,-0.1206f,0.0212f,0.9984f,0.0515f,0.3483f,0.0138f,0.0512f,-0.9986f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0996f,0.0156f,0.0231f,-0.1113f,-0.0233f,1.014f,0.4258f,0.9478f,-0.0152f,-0.4261f,1.014f,-0.2334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.9997f,0.0142f,-0.021f,-0.1156f,0.0212f,0.9218f,-0.3871f,0.668f,0.0138f,-0.3874f,-0.9218f,-0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.6898f,0.724f,0.668f,0f,0.724f,-0.6898f,-0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.6898f,0.724f,0.668f,0f,0.724f,-0.6898f,-0.1158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,-0.0765f,0.9971f,1.1266f,0f,0.9971f,0.0765f,0.3655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,-0.0497f,-0.6481f,1.1145f,0f,0.6481f,-0.0497f,0.5241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,-0.0765f,0.9971f,1.1266f,0f,0.9971f,0.0765f,0.3655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.1719f,-0.7121f,-0.6807f,-0.3469f,0.6329f,0.6094f,-0.4777f,1.0668f,0.7549f,-0.3487f,0.5554f,0.3028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.1719f,-0.936f,-0.3072f,-0.1887f,0.6329f,0.3439f,-0.6937f,0.9182f,0.7549f,-0.0752f,0.6515f,0.3913f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,0.0581f,0f,0f,0f,0.842f,0f,0f,0f,0.4277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,0.0541f,0f,0f,0f,0.8274f,0f,0f,0f,0.4103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,0.0501f,0f,0f,0f,0.8127f,0f,0f,0f,0.3928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.1719f,-0.936f,-0.3072f,-0.1616f,0.6329f,0.3439f,-0.6937f,0.9083f,0.7549f,-0.0752f,0.6515f,0.3935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.7828f,-0.8189f,-0.1977f,-0.6453f,-0.5493f,0.7008f,-0.7278f,1.3222f,0.6387f,-0.401f,-0.8682f,0.1566f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.1719f,-0.7121f,-0.6807f,-0.3469f,0.6329f,0.6094f,-0.4777f,1.0668f,0.7549f,-0.3487f,0.5554f,0.3028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.3469f,0.4721f,0.8104f,0.3469f,-0.2921f,0.8755f,-0.385f,1.0668f,-0.8913f,-0.1032f,0.4416f,0.3028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.3469f,0.9274f,0.1403f,0.2509f,-0.2921f,0.249f,-0.9234f,0.8463f,-0.8913f,0.2793f,0.3573f,0.3377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.0095f,0f,0f,0f,0.7812f,0f,0f,0f,0.2667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.3469f,0.9274f,0.1403f,0.2241f,-0.2921f,0.249f,-0.9234f,0.8391f,-0.8913f,0.2793f,0.3573f,0.3296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.932f,0.5429f,0.3989f,0.5448f,0.4427f,1.0068f,-0.3359f,1.4338f,-0.5078f,-0.1187f,-1.0249f,0.2595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.3469f,0.4721f,0.8104f,0.3469f,-0.2921f,0.8755f,-0.385f,1.0668f,-0.8913f,-0.1032f,0.4416f,0.3028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,0.7933f,-0.8326f,1.2363f,0f,0.8326f,0.7933f,0.4806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,0.7588f,0.7964f,1.1167f,0f,0.7964f,-0.7588f,0.3551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.23125,"py":1.2322664109,"pz":0.2249684263,"ry":0,"rx":46.383972168}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/rage_mode/zzz/frames/24_locator_constant