# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.8969f,0.1157f,-0.4267f,0f,0.0443f,0.9838f,0.1737f,0.6938f,0.4399f,0.1369f,-0.8875f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.8969f,0.1157f,-0.4267f,0f,0.0443f,0.9838f,0.1737f,0.6938f,0.4399f,0.1369f,-0.8875f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9586f,0.0092f,-0.2846f,0.077f,-0.0477f,0.9802f,0.1923f,1.3478f,0.2808f,0.1979f,-0.9391f,0.091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6231f,0.006f,0.185f,0.0784f,0.031f,0.6371f,-0.125f,1.5037f,-0.1825f,0.1287f,0.6104f,0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9586f,0.0092f,-0.2846f,0.077f,-0.0477f,0.9802f,0.1923f,1.3478f,0.2808f,0.1979f,-0.9391f,0.091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.4949f,-0.7524f,-0.4347f,-0.2442f,0.7914f,-0.1837f,-0.583f,1.2779f,0.3588f,-0.6326f,0.6863f,0.2317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.4949f,-0.859f,0.1308f,-0.0733f,0.7914f,-0.5078f,-0.3403f,1.311f,0.3588f,-0.0649f,0.9312f,0.3944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,0.1393f,0f,0f,0f,1.4599f,0f,0f,0f,0.4199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,0.1508f,0f,0f,0f,1.4416f,0f,0f,0f,0.4116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,0.1622f,0f,0f,0f,1.4232f,0f,0f,0f,0.4033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.4949f,-0.859f,0.1308f,-0.0485f,0.7914f,-0.5078f,-0.3403f,1.3257f,0.3588f,-0.0649f,0.9312f,0.3963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.5f,-0.8652f,0.5692f,-0.5596f,-0.6705f,-0.2113f,-0.9101f,1.2009f,0.7893f,-0.7275f,-0.4126f,-0.0334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.4949f,-0.7524f,-0.4347f,-0.2442f,0.7914f,-0.1837f,-0.583f,1.2779f,0.3588f,-0.6326f,0.6863f,0.2317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.4232f,-0.1176f,0.8984f,0.378f,-0.7726f,0.5648f,-0.29f,1.2471f,-0.4733f,-0.8168f,-0.3299f,-0.0734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.4232f,0.8898f,-0.1706f,0.4344f,-0.7726f,-0.4528f,-0.4451f,1.0871f,-0.4733f,-0.0566f,0.8791f,0.1374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.2036f,0f,0f,0f,1.2056f,0f,0f,0f,0.1535f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.4232f,0.8898f,-0.1706f,0.4086f,-0.7726f,-0.4528f,-0.4451f,1.1002f,-0.4733f,-0.0566f,0.8791f,0.1391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-1.0331f,-0.1352f,-0.4867f,0.3288f,0.3336f,0.6495f,-0.8885f,1.4838f,0.3793f,-0.9394f,-0.5442f,-0.4158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.4232f,-0.1176f,0.8984f,0.378f,-0.7726f,0.5648f,-0.29f,1.2471f,-0.4733f,-0.8168f,-0.3299f,-0.0734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0315f,0.1331f,0.4907f,0.0954f,-0.051f,1.1314f,-0.1998f,1.5042f,-0.5059f,0.1574f,1.0207f,0.1128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.9866f,0.1273f,-0.4694f,0.0753f,0.0487f,1.0822f,0.1911f,1.3336f,0.4839f,0.1506f,-0.9763f,0.089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(node) {transformation: [-0.9758f,-0.1916f,-0.1055f,-0.3298f,-0.1959f,0.9801f,0.0315f,2.2097f,0.0973f,0.0514f,-0.9939f,-1.4063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(node2) {transformation: [-0.9752f,0.1472f,-0.1652f,0.1035f,0.1442f,0.9891f,0.0299f,2.2212f,0.1678f,0.0054f,-0.9858f,-1.4652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_world) {transformation: [-0.9905f,0.0017f,-0.1371f,-0.0832f,-0.0262f,0.9792f,0.2012f,2.1408f,0.1346f,0.2029f,-0.9699f,-1.23f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear4) {transformation: [-0.2902f,-0.7186f,-0.632f,0.4343f,0.1859f,0.6055f,-0.7738f,2.1377f,0.9387f,-0.3421f,-0.0421f,-1.4881f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_lower) {transformation: [-0.632f,-0.7186f,0.2902f,0.3658f,-0.7738f,0.6055f,-0.1859f,2.0143f,-0.0421f,-0.3421f,-0.9387f,-1.4826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_world) {transformation: [-0.632f,-0.7608f,-0.1474f,0.0965f,-0.7738f,0.6092f,0.1734f,2.0699f,-0.0421f,0.2237f,-0.9737f,-1.4319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear5) {transformation: [-0.6162f,0.0066f,0.7875f,-0.4426f,-0.7859f,-0.0707f,-0.6143f,2.147f,0.0516f,-0.9975f,0.0488f,-0.8631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_lower) {transformation: [0.7875f,0.0066f,0.6162f,-0.3349f,-0.6143f,-0.0707f,0.7859f,2.0622f,0.0488f,-0.9975f,-0.0516f,-0.8289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_world) {transformation: [0.7875f,0.0053f,0.6162f,-0.2352f,-0.6143f,-0.0725f,0.7857f,1.9672f,0.0488f,-0.9974f,-0.0539f,-1.0722f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear1) {transformation: [-0.6635f,-0.1109f,-0.7399f,-0.174f,-0.2052f,0.978f,0.0374f,1.7883f,0.7195f,0.1767f,-0.6716f,-1.4142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(upper_body) {transformation: [-0.6635f,-0.1109f,-0.7399f,0f,-0.2052f,0.978f,0.0374f,1.4073f,0.7195f,0.1767f,-0.6716f,-1.3625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear7) {transformation: [0.2242f,-0.3101f,0.9239f,-0.3342f,0.8105f,0.5858f,0f,1.1745f,-0.5412f,0.7488f,0.3827f,-1.2195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_lower) {transformation: [0.9239f,-0.3101f,-0.2242f,-0.2045f,0f,0.5858f,-0.8105f,1.1739f,0.3827f,0.7488f,0.5412f,-1.1705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_world) {transformation: [0.9239f,0.2545f,-0.2858f,-0.125f,0f,0.7469f,0.665f,1.4073f,0.3827f,-0.6144f,0.69f,-1.3625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear6) {transformation: [-0.3826f,-0.0058f,0.9239f,0.3687f,-0.0151f,0.9999f,0f,1.4567f,-0.9238f,-0.014f,-0.3827f,-1.1265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_lower) {transformation: [0.9239f,-0.0058f,0.3826f,0.2433f,0f,0.9999f,0.0151f,1.4527f,-0.3827f,-0.014f,0.9238f,-1.0769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_world) {transformation: [0.9239f,-0.3786f,-0.0556f,0.125f,0f,-0.1454f,0.9894f,1.4073f,-0.3827f,-0.9141f,-0.1343f,-1.3625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear2) {transformation: [-1f,0f,0f,0.6386f,0f,1f,0f,2.294f,0f,0f,-1f,-1.6693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear3) {transformation: [-1f,0f,0f,-0.6437f,0f,1f,0f,2.4261f,0f,0f,-1f,-1.5837f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.2070188391,"py":1.3392667367,"pz":-0.1685970809,"ry":334.3225489523,"rx":10.0041082649},"right_hand_world":{"px":-0.3370202153,"py":2.0842634129,"pz":-0.5172389041,"ry":85.2106957191,"rx":51.8013831726},"barrage_anchor":{"px":0,"py":1.7823065761,"pz":-1.3625,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/rage_mode/zzz/frames/72_locator_constant