# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage minecraft:custom yuji.attack.fuga.id int 1 run scoreboard players get @s customYuji_FugaID
function custom:items/yuji/moves/4/fuga/movement with storage minecraft:custom yuji.attack.fuga