# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_blue_hand1) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_purple_hand1) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_red_hand1) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom2) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom3) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom4) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [0f,0f,0f,0f,0f,0f,0f,13.1679f,0f,0f,0f,-8.1346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blue1) {transformation: [0f,0f,0f,-0.4219f,0f,0f,0f,33.6255f,0f,0f,0f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:gojo/animations/hollow_purple_200/zzz/frames/85_locator_commands
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:gojo/animations/hollow_purple_200/zzz/frames/85_locator_commands
data modify entity @s data merge value {"cameras":{},"locators":{"blue_hand":{"posx":-0.000005654631860488622,"posy":13.167910472716153,"posz":-8.13464540494666,"roty":27.69744765649483,"rotx":56.31090303556493},"purple_hand":{"posx":-0.000005654631860488622,"posy":13.167910472716153,"posz":-8.13464540494666,"roty":27.69744765649486,"rotx":56.31090303556492},"red_hand":{"posx":-0.000005654631860488622,"posy":13.167910472716153,"posz":-8.13464540494666,"roty":27.69744765649486,"rotx":56.31090303556492},"blue":{"posx":-0.42187499999999994,"posy":33.625490618649046,"posz":-0.25000000000000006,"roty":0,"rotx":0}}}