# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [0.3634f,0.2782f,-0.8891f,-0.0877f,-0.096f,0.9605f,0.2613f,0.4053f,0.9267f,-0.0096f,0.3757f,-0.1048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [-0.3997f,0.306f,0.978f,0.0128f,0.1056f,1.0565f,-0.2874f,0.7524f,-1.0194f,-0.0106f,-0.4133f,-0.1082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [-0.436f,0.3339f,1.067f,0.0096f,0.1152f,1.1526f,-0.3136f,0.7413f,-1.112f,-0.0115f,-0.4509f,-0.1081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [0.3634f,0.2782f,-0.8891f,-0.0877f,-0.096f,0.9605f,0.2613f,0.4053f,0.9267f,-0.0096f,0.3757f,-0.1048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0.3634f,-0.0202f,-0.9314f,-0.0947f,-0.096f,0.9936f,-0.059f,0.75f,0.9267f,0.1109f,0.3591f,-0.0663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [-0.3997f,-0.0223f,1.0246f,-0.1009f,0.1056f,1.093f,0.0649f,1.0516f,-1.0194f,0.1219f,-0.395f,-0.0327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [0.3634f,-0.0202f,-0.9314f,-0.0947f,-0.096f,0.9936f,-0.059f,0.75f,0.9267f,0.1109f,0.3591f,-0.0663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0.2176f,-0.9737f,0.0671f,0.4274f,0.2585f,-0.0088f,-0.966f,0.7923f,0.9412f,0.2275f,0.2498f,-0.0222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [-0.2394f,-1.0711f,-0.0738f,0.0756f,-0.2844f,-0.0096f,1.0626f,0.7891f,-1.0353f,0.2503f,-0.2748f,0.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [-0.2611f,-1.1685f,-0.0805f,0.0868f,-0.3102f,-0.0105f,1.1592f,0.7892f,-1.1294f,0.273f,-0.2998f,0.0574f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [0.2176f,-0.9737f,0.0671f,0.4274f,0.2585f,-0.0088f,-0.966f,0.7923f,0.9412f,0.2275f,0.2498f,-0.0222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.2176f,-0.9592f,0.1807f,0.0947f,0.2585f,-0.1219f,-0.9583f,0.75f,0.9412f,0.2552f,0.2215f,0.0663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [-0.2394f,-1.0551f,-0.1988f,-0.1964f,-0.2844f,-0.1341f,1.0541f,0.713f,-1.0353f,0.2808f,-0.2436f,0.1438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [0.2176f,-0.9592f,0.1807f,0.0947f,0.2585f,-0.1219f,-0.9583f,0.75f,0.9412f,0.2552f,0.2215f,0.0663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0.0351f,0.0089f,-0.9993f,0f,-0.1265f,0.992f,0.0044f,0.75f,0.9913f,0.1262f,0.036f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [0.0351f,0.0089f,-0.9993f,0f,-0.1265f,0.992f,0.0044f,0.75f,0.9913f,0.1262f,0.036f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.3523f,0.2189f,-0.9099f,0.0059f,-0.017f,0.9706f,0.2401f,1.4095f,0.9357f,0.1001f,-0.3382f,0.0839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.229f,0.1423f,0.5915f,0.0407f,0.0111f,0.6309f,-0.1561f,1.5638f,-0.6082f,0.0651f,0.2198f,0.0998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.3523f,0.2189f,-0.9099f,0.0059f,-0.017f,0.9706f,0.2401f,1.4095f,0.9357f,0.1001f,-0.3382f,0.0839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.6011f,0.736f,-0.3115f,0.0173f,0.1092f,0.3104f,0.9443f,1.2796f,0.7917f,-0.6016f,0.1062f,0.4169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.6011f,0.6293f,-0.4926f,-0.1559f,0.1092f,0.5459f,0.8307f,1.2146f,0.7917f,-0.5531f,0.2594f,0.5574f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.6011f,0.6293f,-0.4926f,-0.1741f,0.1092f,0.5459f,0.8307f,1.1988f,0.7917f,-0.5531f,0.2594f,0.5734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.3582f,0.8464f,-0.6912f,0.3258f,1.0859f,0.357f,-0.1256f,1.4097f,0.1221f,-0.6919f,-0.9104f,0.1647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.6011f,0.736f,-0.3115f,0.0173f,0.1092f,0.3104f,0.9443f,1.2796f,0.7917f,-0.6016f,0.1062f,0.4169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.1033f,-0.6402f,-0.7613f,-0.007f,-0.681f,0.5123f,-0.5232f,1.3673f,0.725f,0.5725f,-0.383f,-0.2709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.1033f,-0.7898f,-0.6047f,0.1367f,-0.681f,0.387f,-0.6217f,1.2452f,0.725f,0.476f,-0.4979f,-0.4061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.1033f,-0.7898f,-0.6047f,0.1595f,-0.681f,0.387f,-0.6217f,1.2341f,0.725f,0.476f,-0.4979f,-0.4198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0.8755f,-0.7362f,0.1188f,-0.2754f,0.6017f,0.5892f,-0.7831f,1.5821f,0.4405f,0.6583f,0.8337f,-0.031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.1033f,-0.6402f,-0.7613f,-0.007f,-0.681f,0.5123f,-0.5232f,1.3673f,0.725f,0.5725f,-0.383f,-0.2709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [-0.0404f,0.0102f,1.1492f,0.0073f,0.1454f,1.1408f,-0.005f,1.5672f,-1.14f,0.1452f,-0.0414f,0.104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0.0387f,0.0098f,-1.0993f,0.0058f,-0.1391f,1.0912f,0.0048f,1.3952f,1.0905f,0.1389f,0.0396f,0.0821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":267.9376086573,"rx":0.2515319079}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/majin_kick/zzz/frames/18_locator_constant