# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.8078f,-0.4757f,0.3481f,0.0183f,-0.5876f,0.6971f,-0.4108f,0.8673f,-0.0472f,-0.5364f,-0.8427f,0.3215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0.8886f,-0.5233f,-0.3829f,-0.1675f,0.6463f,0.7669f,0.4519f,1.1397f,0.0519f,-0.59f,0.9269f,0.112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0.9694f,-0.5709f,-0.4177f,-0.1615f,0.7051f,0.8366f,0.493f,1.131f,0.0567f,-0.6436f,1.0112f,0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.8078f,-0.4757f,0.3481f,0.0183f,-0.5876f,0.6971f,-0.4108f,0.8673f,-0.0472f,-0.5364f,-0.8427f,0.3215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.8078f,0.2806f,0.5184f,0.1236f,-0.5876f,-0.3129f,-0.7462f,0.75f,-0.0472f,-0.9074f,0.4177f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0.8886f,0.3087f,-0.5702f,0.2157f,0.6463f,-0.3442f,0.8209f,0.6473f,0.0519f,-0.9981f,-0.4594f,-0.3165f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.8078f,0.2806f,0.5184f,0.1236f,-0.5876f,-0.3129f,-0.7462f,0.75f,-0.0472f,-0.9074f,0.4177f,-0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.9526f,-0.0524f,0.2998f,-0.1406f,-0.005f,0.9876f,0.1569f,0.3801f,-0.3043f,0.148f,-0.941f,0.078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0478f,-0.0576f,-0.3298f,-0.161f,0.0055f,1.0864f,-0.1726f,0.7659f,0.3347f,0.1628f,1.0351f,0.1358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1431f,-0.0629f,-0.3598f,-0.1604f,0.0059f,1.1851f,-0.1883f,0.7535f,0.3652f,0.1776f,1.1292f,0.134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.9526f,-0.0524f,0.2998f,-0.1406f,-0.005f,0.9876f,0.1569f,0.3801f,-0.3043f,0.148f,-0.941f,0.078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9526f,0.0453f,0.3009f,-0.1236f,-0.005f,0.9864f,-0.1642f,0.75f,-0.3043f,-0.1579f,-0.9394f,0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0478f,0.0499f,-0.331f,-0.1087f,0.0055f,1.085f,0.1807f,1.0737f,0.3347f,-0.1737f,1.0333f,-0.033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.9526f,0.0453f,0.3009f,-0.1236f,-0.005f,0.9864f,-0.1642f,0.75f,-0.3043f,-0.1579f,-0.9394f,0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.8765f,-0.3308f,0.3498f,0f,-0.2502f,0.9337f,0.256f,0.75f,-0.4113f,0.1369f,-0.9011f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.8765f,-0.3308f,0.3498f,0f,-0.2502f,0.9337f,0.256f,0.75f,-0.4113f,0.1369f,-0.9011f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6812f,-0.334f,0.6514f,-0.2378f,-0.1177f,0.9283f,0.3528f,1.4211f,-0.7225f,0.1637f,-0.6717f,0.0984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.4428f,-0.2171f,-0.4234f,-0.2952f,0.0765f,0.6034f,-0.2293f,1.5807f,0.4696f,0.1064f,0.4366f,0.1265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.6812f,-0.334f,0.6514f,-0.2378f,-0.1177f,0.9283f,0.3528f,1.4211f,-0.7225f,0.1637f,-0.6717f,0.0984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.98f,-0.1279f,-0.1528f,-0.5354f,-0.188f,0.8474f,0.4965f,1.2397f,0.0659f,0.5153f,-0.8545f,-0.0687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.98f,-0.1977f,0.025f,-0.5056f,-0.188f,0.8759f,-0.4444f,1.0288f,0.0659f,-0.4402f,-0.8955f,-0.2274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.98f,-0.1977f,0.025f,-0.4995f,-0.188f,0.8759f,-0.4444f,1.0014f,0.0659f,-0.4402f,-0.8955f,-0.2136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.1757f,-0.1471f,1.1269f,-0.5934f,0.571f,0.9746f,0.2162f,1.6237f,-0.9827f,0.5925f,-0.0758f,0.1648f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.98f,-0.1279f,-0.1528f,-0.5354f,-0.188f,0.8474f,0.4965f,1.2397f,0.0659f,0.5153f,-0.8545f,-0.0687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.661f,-0.2046f,0.722f,0.1219f,-0.4595f,0.871f,-0.1739f,1.4274f,-0.5933f,-0.4467f,-0.6697f,0.2398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.661f,0.3648f,0.6558f,0.1908f,-0.4595f,0.4942f,-0.738f,1.1979f,-0.5933f,-0.7891f,-0.159f,0.3408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.661f,0.3648f,0.6558f,0.1794f,-0.4595f,0.4942f,-0.738f,1.1824f,-0.5933f,-0.7891f,-0.159f,0.3654f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.8303f,-0.2352f,-0.7601f,0.0292f,0.2f,1.0016f,-0.5284f,1.8221f,0.7702f,-0.5137f,-0.6823f,0.0374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.661f,-0.2046f,0.722f,0.1219f,-0.4595f,0.871f,-0.1739f,1.4274f,-0.5933f,-0.4467f,-0.6697f,0.2398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0079f,-0.3804f,-0.4023f,-0.2946f,0.2878f,1.0738f,-0.2945f,1.5816f,0.473f,0.1574f,1.0363f,0.1219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.9641f,-0.3639f,0.3848f,-0.2326f,-0.2753f,1.0271f,0.2816f,1.4065f,-0.4525f,0.1506f,-0.9913f,0.0962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":21.2158288388,"rx":14.835527193}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/majin_kick/zzz/frames/6_locator_constant