# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.8036f,-0.2376f,0.5457f,-0.0486f,-0.5501f,0.6466f,-0.5285f,0.8739f,-0.2273f,-0.7248f,-0.6504f,0.2697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0.884f,-0.2614f,-0.6002f,-0.1345f,0.6051f,0.7113f,0.5813f,1.1075f,0.25f,-0.7973f,0.7154f,0.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0.9643f,-0.2852f,-0.6548f,-0.1318f,0.6601f,0.776f,0.6342f,1.1001f,0.2727f,-0.8698f,0.7804f,0.0162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.8036f,-0.2376f,0.5457f,-0.0486f,-0.5501f,0.6466f,-0.5285f,0.8739f,-0.2273f,-0.7248f,-0.6504f,0.2697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.8036f,0.4723f,0.3621f,0.1152f,-0.5501f,-0.3571f,-0.7549f,0.75f,-0.2273f,-0.8058f,0.5468f,-0.0098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0.884f,0.5196f,-0.3983f,0.2586f,0.6051f,-0.3928f,0.8304f,0.6416f,0.25f,-0.8864f,-0.6015f,-0.2544f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.8036f,0.4723f,0.3621f,0.1152f,-0.5501f,-0.3571f,-0.7549f,0.75f,-0.2273f,-0.8058f,0.5468f,-0.0098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.942f,-0.0869f,0.324f,-0.1185f,-0.0201f,0.9788f,0.2039f,0.4044f,-0.3349f,0.1856f,-0.9238f,0.0398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0363f,-0.0956f,-0.3564f,-0.1499f,0.0222f,1.0767f,-0.2243f,0.7581f,0.3684f,0.2042f,1.0162f,0.1068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1305f,-0.1043f,-0.3888f,-0.1489f,0.0242f,1.1745f,-0.2447f,0.7468f,0.4019f,0.2227f,1.1086f,0.1047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.942f,-0.0869f,0.324f,-0.1185f,-0.0201f,0.9788f,0.2039f,0.4044f,-0.3349f,0.1856f,-0.9238f,0.0398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.942f,0.0094f,0.3353f,-0.1152f,-0.0201f,0.9962f,-0.0845f,0.75f,-0.3349f,-0.0864f,-0.9383f,0.0098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0363f,0.0104f,-0.3689f,-0.1124f,0.0222f,1.0958f,0.093f,1.0524f,0.3684f,-0.095f,1.0321f,-0.0164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.942f,0.0094f,0.3353f,-0.1152f,-0.0201f,0.9962f,-0.0845f,0.75f,-0.3349f,-0.0864f,-0.9383f,0.0098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.672f,-0.3347f,0.6606f,0f,-0.1475f,0.9347f,0.3234f,0.75f,-0.7257f,0.1199f,-0.6775f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.672f,-0.3347f,0.6606f,0f,-0.1475f,0.9347f,0.3234f,0.75f,-0.7257f,0.1199f,-0.6775f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.5788f,-0.1717f,0.7972f,-0.2225f,0.1369f,0.9842f,0.1126f,1.3714f,-0.8039f,0.0439f,0.5932f,0.0797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [-0.3762f,-0.1116f,-0.5181f,-0.2498f,-0.089f,0.6397f,-0.0732f,1.5279f,0.5225f,0.0285f,-0.3856f,0.0867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [0.5788f,-0.1717f,0.7972f,-0.2225f,0.1369f,0.9842f,0.1126f,1.3714f,-0.8039f,0.0439f,0.5932f,0.0797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.908f,-0.4008f,0.1224f,-0.4266f,-0.1663f,0.6127f,0.7726f,1.2392f,-0.3847f,0.6812f,-0.623f,-0.1824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.908f,-0.1864f,0.3753f,-0.3277f,-0.1663f,0.9824f,0.0857f,1.1082f,-0.3847f,0.0154f,-0.9229f,-0.3592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.908f,-0.1864f,0.3753f,-0.3223f,-0.1663f,0.9824f,0.0857f,1.0798f,-0.3847f,0.0154f,-0.9229f,-0.3596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0.1408f,-0.4609f,1.0442f,-0.5946f,0.8885f,0.7046f,0.1912f,1.496f,-0.7164f,0.7833f,0.4424f,0.1031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.908f,-0.4008f,0.1224f,-0.4266f,-0.1663f,0.6127f,0.7726f,1.2392f,-0.3847f,0.6812f,-0.623f,-0.1824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.3843f,0.3645f,0.8482f,0.0396f,-0.246f,0.8451f,-0.4747f,1.3415f,-0.8898f,-0.3911f,-0.2351f,0.321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.3843f,0.8176f,0.4287f,-0.0316f,-0.246f,0.3569f,-0.9012f,1.132f,-0.8898f,-0.4518f,0.064f,0.4097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.3843f,0.8176f,0.4287f,-0.0552f,-0.246f,0.3569f,-0.9012f,1.1217f,-0.8898f,-0.4518f,0.064f,0.4228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.9754f,0.4192f,-0.442f,0.1924f,0.5459f,0.9719f,-0.2829f,1.6958f,0.2704f,-0.4497f,-1.0233f,0.1571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.3843f,0.3645f,0.8482f,0.0396f,-0.246f,0.8451f,-0.4747f,1.3415f,-0.8898f,-0.3911f,-0.2351f,0.321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0.7728f,-0.3849f,-0.7597f,-0.2757f,0.1697f,1.0749f,-0.3719f,1.52f,0.8345f,0.1379f,0.7791f,0.0988f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.7392f,-0.3681f,0.7266f,-0.2177f,-0.1623f,1.0281f,0.3558f,1.3579f,-0.7982f,0.1319f,-0.7453f,0.078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":44.2758028858,"rx":18.8705049894}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/majin_kick/zzz/frames/9_locator_constant