# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.9914f,0.1305f,0.75f,0f,0.1305f,-0.9914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.9914f,0.1305f,0.75f,0f,0.1305f,-0.9914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.868f,0.4966f,1.4092f,0f,0.4966f,-0.868f,0.0868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,0.5642f,-0.3228f,1.5472f,0f,0.3228f,0.5642f,0.1657f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,0.868f,0.4966f,1.4092f,0f,0.4966f,-0.868f,0.0868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.4186f,-0.4704f,-0.7769f,-0.3469f,0.6377f,0.4568f,-0.6202f,1.3232f,0.6466f,-0.755f,0.1088f,0.0755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.4186f,-0.8714f,-0.2558f,-0.2497f,0.6377f,-0.0815f,-0.7659f,1.202f,0.6466f,-0.4837f,0.5898f,0.2579f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.4186f,-0.8714f,-0.2558f,-0.2245f,0.6377f,-0.0815f,-0.7659f,1.2043f,0.6466f,-0.4837f,0.5898f,0.2719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.8934f,-0.5409f,0.4814f,-0.544f,-0.7132f,0.5253f,-0.7334f,1.5147f,0.1251f,-0.8683f,-0.7436f,-0.241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.4186f,-0.4704f,-0.7769f,-0.3469f,0.6377f,0.4568f,-0.6202f,1.3232f,0.6466f,-0.755f,0.1088f,0.0755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.4186f,0.4704f,0.7769f,0.3469f,-0.6377f,0.4568f,-0.6202f,1.3232f,-0.6466f,-0.755f,0.1088f,0.0755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.4186f,0.8714f,0.2558f,0.2497f,-0.6377f,-0.0815f,-0.7659f,1.202f,-0.6466f,-0.4837f,0.5898f,0.2579f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.4186f,0.8714f,0.2558f,0.2245f,-0.6377f,-0.0815f,-0.7659f,1.2043f,-0.6466f,-0.4837f,0.5898f,0.2719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.8934f,0.5409f,-0.4814f,0.544f,0.7132f,0.5253f,-0.7334f,1.5147f,-0.1251f,-0.8683f,-0.7436f,-0.241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.4186f,0.4704f,0.7769f,0.3469f,-0.6377f,0.4568f,-0.6202f,1.3232f,-0.6466f,-0.755f,0.1088f,0.0755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,1.1402f,-0.1501f,1.5668f,0f,0.1501f,1.1402f,0.1075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,1.0906f,0.1436f,1.3948f,0f,0.1436f,-1.0906f,0.0849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":0,"rx":7.5}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/cleave_old/zzz/frames/15_locator_commands