# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,0.75f,0f,-0.1736f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,0.75f,0f,-0.1736f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,1.4578f,0f,-0.1736f,-0.9848f,-0.1248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,0.6401f,0.1129f,1.6271f,0f,-0.1129f,0.6401f,-0.1547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,1.4578f,0f,-0.1736f,-0.9848f,-0.1248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7266f,0.4437f,-0.5246f,-0.375f,0.5578f,0.8267f,-0.0733f,1.3655f,0.4012f,-0.3458f,-0.8482f,-0.1085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7266f,0.2376f,-0.6447f,-0.4924f,0.5578f,0.7518f,-0.3516f,1.1565f,0.4012f,-0.6151f,-0.6788f,-0.0305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7266f,0.2376f,-0.6447f,-0.4998f,0.5578f,0.7518f,-0.3516f,1.133f,0.4012f,-0.6151f,-0.6788f,-0.0113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.6033f,0.5103f,0.8356f,-0.1739f,-0.0843f,0.9507f,-0.6415f,1.7401f,-0.9754f,-0.3977f,-0.4614f,-0.2652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7266f,0.4437f,-0.5246f,-0.375f,0.5578f,0.8267f,-0.0733f,1.3655f,0.4012f,-0.3458f,-0.8482f,-0.1085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.7266f,-0.4437f,0.5246f,0.375f,-0.5578f,0.8267f,-0.0733f,1.3655f,-0.4012f,-0.3458f,-0.8482f,-0.1085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.7266f,-0.2376f,0.6447f,0.4924f,-0.5578f,0.7518f,-0.3516f,1.1565f,-0.4012f,-0.6151f,-0.6788f,-0.0305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.7266f,-0.2376f,0.6447f,0.4998f,-0.5578f,0.7518f,-0.3516f,1.133f,-0.4012f,-0.6151f,-0.6788f,-0.0113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.6033f,-0.5103f,-0.8356f,0.1739f,0.0843f,0.9507f,-0.6415f,1.7401f,0.9754f,-0.3977f,-0.4614f,-0.2652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.7266f,-0.4437f,0.5246f,0.375f,-0.5578f,0.8267f,-0.0733f,1.3655f,-0.4012f,-0.3458f,-0.8482f,-0.1085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,1.1325f,0.1997f,1.6271f,0f,-0.1997f,1.1325f,-0.1547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,1.0833f,-0.191f,1.4424f,0f,-0.191f,-1.0833f,-0.1221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":0,"rx":-10}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/cleave_old/zzz/frames/17_locator_commands