# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.9819f,-0.1894f,0.75f,0f,-0.1894f,-0.9819f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.9819f,-0.1894f,0.75f,0f,-0.1894f,-0.9819f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.8263f,-0.5632f,1.4557f,0f,-0.5632f,-0.8263f,-0.1362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,0.5371f,0.3661f,1.5978f,0f,-0.3661f,0.5371f,-0.233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,0.8263f,-0.5632f,1.4557f,0f,-0.5632f,-0.8263f,-0.1362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8794f,0.4707f,0.0711f,-0.375f,0.2169f,0.2633f,0.94f,1.3637f,0.4238f,0.8421f,-0.3337f,-0.1184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8794f,0.4681f,0.0868f,-0.4928f,0.2169f,0.2317f,0.9483f,1.2969f,0.4238f,0.8528f,-0.3053f,-0.3286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8794f,0.4681f,0.0868f,-0.5074f,0.2169f,0.2317f,0.9483f,1.2896f,0.4238f,0.8528f,-0.3053f,-0.3552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0.0817f,0.5414f,1.0113f,-0.1617f,1.081f,0.3028f,-0.2495f,1.483f,-0.3837f,0.9684f,-0.4873f,0.2632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8794f,0.4707f,0.0711f,-0.375f,0.2169f,0.2633f,0.94f,1.3637f,0.4238f,0.8421f,-0.3337f,-0.1184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8794f,-0.4707f,-0.0711f,0.375f,-0.2169f,0.2633f,0.94f,1.3637f,-0.4238f,0.8421f,-0.3337f,-0.1184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.8794f,-0.4681f,-0.0868f,0.4928f,-0.2169f,0.2317f,0.9483f,1.2969f,-0.4238f,0.8528f,-0.3053f,-0.3286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.8794f,-0.4681f,-0.0868f,0.5074f,-0.2169f,0.2317f,0.9483f,1.2896f,-0.4238f,0.8528f,-0.3053f,-0.3552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0.0817f,-0.5414f,-1.0113f,0.1617f,-1.081f,0.3028f,-0.2495f,1.483f,0.3837f,0.9684f,-0.4873f,0.2632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.8794f,-0.4707f,-0.0711f,0.375f,-0.2169f,0.2633f,0.94f,1.3637f,-0.4238f,0.8421f,-0.3337f,-0.1184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,1.1292f,0.2179f,1.6245f,0f,-0.2179f,1.1292f,-0.1687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,1.0801f,-0.2084f,1.4404f,0f,-0.2084f,-1.0801f,-0.1332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":0,"rx":-10.92}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args