# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.9962f,-0.0872f,0.75f,0f,-0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.9962f,-0.0872f,0.75f,0f,-0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.934f,-0.3573f,1.4123f,0f,-0.3573f,-0.934f,-0.0579f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,0.6071f,0.2323f,1.5608f,0f,-0.2323f,0.6071f,-0.1148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,0.934f,-0.3573f,1.4123f,0f,-0.3573f,-0.934f,-0.0579f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9275f,0.3626f,-0.0909f,-0.3469f,0.1611f,0.6072f,0.7781f,1.3259f,0.3373f,0.707f,-0.6216f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.9275f,0.3626f,-0.0909f,-0.4307f,0.1611f,0.6072f,0.7781f,1.1855f,0.3373f,0.707f,-0.6216f,-0.2139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.9275f,0.3626f,-0.0909f,-0.4412f,0.1611f,0.6072f,0.7781f,1.168f,0.3373f,0.707f,-0.6216f,-0.2343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.1045f,0.417f,1.0666f,-0.1949f,0.8948f,0.6982f,-0.1853f,1.5804f,-0.7148f,0.8131f,-0.3879f,0.246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.9275f,0.3626f,-0.0909f,-0.3469f,0.1611f,0.6072f,0.7781f,1.3259f,0.3373f,0.707f,-0.6216f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9275f,-0.3626f,0.0909f,0.3469f,-0.1611f,0.6072f,0.7781f,1.3259f,-0.3373f,0.707f,-0.6216f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9275f,-0.3626f,0.0909f,0.4307f,-0.1611f,0.6072f,0.7781f,1.1855f,-0.3373f,0.707f,-0.6216f,-0.2139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9275f,-0.3626f,0.0909f,0.4412f,-0.1611f,0.6072f,0.7781f,1.168f,-0.3373f,0.707f,-0.6216f,-0.2343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.1045f,-0.417f,-1.0666f,0.1949f,-0.8948f,0.6982f,-0.1853f,1.5804f,0.7148f,0.8131f,-0.3879f,0.246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9275f,-0.3626f,0.0909f,0.3469f,-0.1611f,0.6072f,0.7781f,1.3259f,-0.3373f,0.707f,-0.6216f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,1.1456f,0.1002f,1.5707f,0f,-0.1002f,1.1456f,-0.0718f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,1.0958f,-0.0959f,1.3979f,0f,-0.0959f,-1.0958f,-0.0567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":0,"rx":-5}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args