# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.999f,0.0452f,0.75f,0f,0.0452f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.999f,0.0452f,0.75f,0f,0.0452f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.989f,0.1481f,1.468f,0f,0.1481f,-0.989f,0.0325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,0.6428f,-0.0963f,1.638f,0f,0.0963f,0.6428f,0.058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,0.989f,0.1481f,1.468f,0f,0.1481f,-0.989f,0.0325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9431f,0.1796f,-0.2797f,-0.375f,0.2771f,0.8897f,-0.3629f,1.3744f,0.1837f,-0.4198f,-0.8888f,0.0283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.9431f,0.1183f,-0.3107f,-0.4218f,0.2771f,0.7962f,-0.5379f,1.149f,0.1837f,-0.5934f,-0.7837f,0.1278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.9431f,0.1183f,-0.3107f,-0.4255f,0.2771f,0.7962f,-0.5379f,1.1241f,0.1837f,-0.5934f,-0.7837f,0.1463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.3217f,0.2066f,1.0846f,-0.2936f,-0.4174f,1.0231f,-0.3186f,1.7775f,-1.0222f,-0.4828f,-0.2112f,-0.162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.9431f,0.1796f,-0.2797f,-0.375f,0.2771f,0.8897f,-0.3629f,1.3744f,0.1837f,-0.4198f,-0.8888f,0.0283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9431f,-0.1796f,0.2797f,0.375f,-0.2771f,0.8897f,-0.3629f,1.3744f,-0.1837f,-0.4198f,-0.8888f,0.0283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9431f,-0.1183f,0.3107f,0.4218f,-0.2771f,0.7962f,-0.5379f,1.149f,-0.1837f,-0.5934f,-0.7837f,0.1278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9431f,-0.1183f,0.3107f,0.4255f,-0.2771f,0.7962f,-0.5379f,1.1241f,-0.1837f,-0.5934f,-0.7837f,0.1463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.3217f,-0.2066f,-1.0846f,0.2936f,0.4174f,1.0231f,-0.3186f,1.7775f,1.0222f,-0.4828f,-0.2112f,-0.162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9431f,-0.1796f,0.2797f,0.375f,-0.2771f,0.8897f,-0.3629f,1.3744f,-0.1837f,-0.4198f,-0.8888f,0.0283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,1.1488f,-0.052f,1.6397f,0f,0.052f,1.1488f,0.0403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,1.0989f,0.0498f,1.4524f,0f,0.0498f,-1.0989f,0.0318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":0,"rx":2.5927734375}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/cleave_old/zzz/frames/3_locator_commands