# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(yuji_waist) {transformation: [-0.9987f,-0.0002f,0.0501f,0f,0f,1f,0.0032f,0.6875f,-0.0501f,0.0032f,-0.9987f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist_group) {transformation: [-0.9987f,-0.0002f,0.0501f,0f,0f,1f,0.0032f,0.6875f,-0.0501f,0.0032f,-0.9987f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head) {transformation: [-0.9656f,-0.0077f,-0.2599f,-0.0001f,-0.0233f,0.9981f,0.0569f,1.3523f,0.2589f,0.061f,-0.964f,0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_helmet) {transformation: [0.6276f,-0.005f,0.1689f,-0.0013f,0.0151f,0.6488f,-0.037f,1.511f,-0.1683f,0.0396f,0.6266f,0.0118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head_group) {transformation: [-0.9656f,-0.0077f,-0.2599f,-0.0001f,-0.0233f,0.9981f,0.0569f,1.3523f,0.2589f,0.061f,-0.964f,0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm) {transformation: [-0.8724f,-0.4557f,-0.1768f,-0.3465f,0.1628f,0.0703f,-0.9842f,1.2656f,0.4609f,-0.8873f,0.0128f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm) {transformation: [-0.8724f,-0.4557f,-0.1768f,-0.2412f,0.1628f,0.0703f,-0.9842f,1.2494f,0.4609f,-0.8873f,0.0128f,0.1897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm_group) {transformation: [-0.8724f,-0.4557f,-0.1768f,-0.228f,0.1628f,0.0703f,-0.9842f,1.2473f,0.4609f,-0.8873f,0.0128f,0.2153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_r) {transformation: [-0.2034f,-0.5241f,1.0032f,-0.5375f,-1.1318f,0.0808f,-0.1872f,1.2951f,0.0148f,-1.0205f,-0.5301f,-0.3874f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm_group) {transformation: [-0.8724f,-0.4557f,-0.1768f,-0.3465f,0.1628f,0.0703f,-0.9842f,1.2656f,0.4609f,-0.8873f,0.0128f,-0.0155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm) {transformation: [-0.9808f,-0.069f,0.1822f,0.3463f,-0.1272f,0.9352f,-0.3304f,1.2656f,-0.1476f,-0.3472f,-0.9261f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm) {transformation: [-0.9808f,-0.069f,0.1822f,0.3623f,-0.1272f,0.9352f,-0.3304f,1.0494f,-0.1476f,-0.3472f,-0.9261f,0.0995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm_group) {transformation: [-0.9808f,-0.069f,0.1822f,0.3643f,-0.1272f,0.9352f,-0.3304f,1.0223f,-0.1476f,-0.3472f,-0.9261f,0.1096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_l) {transformation: [-0.2096f,-0.0794f,-1.128f,0.3174f,0.38f,1.0755f,-0.1463f,1.6576f,1.065f,-0.3993f,-0.1698f,-0.1263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm_group) {transformation: [-0.9808f,-0.069f,0.1822f,0.3463f,-0.1272f,0.9352f,-0.3304f,1.2656f,-0.1476f,-0.3472f,-0.9261f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_body) {transformation: [1.1486f,-0.0002f,-0.0576f,-0.0001f,0f,1.15f,-0.0037f,1.5113f,0.0576f,0.0037f,1.1486f,0.0027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_pants) {transformation: [-1.0986f,-0.0002f,0.0551f,-0.0001f,0f,1.1f,0.0036f,1.3379f,-0.0551f,0.0036f,-1.0986f,0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"yuji_mount":{"px":0,"py":0.6875,"pz":0,"ry":2.8703703704,"rx":0.1851851852}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/dismantle/zzz/frames/10_locator_constant
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:yuji/animations/dismantle/zzz/frames/10_root_function