# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.9914f,0f,0.1305f,0f,0f,1f,0f,0.75f,-0.1305f,0f,-0.9914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9914f,0f,0.1305f,0f,0f,1f,0f,0.75f,-0.1305f,0f,-0.9914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9846f,-0.0149f,-0.1739f,0f,-0.0218f,0.999f,0.0378f,1.4148f,0.1732f,0.041f,-0.984f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.64f,-0.0097f,0.1131f,-0.0024f,0.0142f,0.6494f,-0.0246f,1.5737f,-0.1126f,0.0266f,0.6396f,0.0065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9846f,-0.0149f,-0.1739f,0f,-0.0218f,0.999f,0.0378f,1.4148f,0.1732f,0.041f,-0.984f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9305f,-0.3198f,-0.1786f,-0.3439f,0.1612f,0.0803f,-0.9836f,1.3281f,0.3289f,-0.9441f,-0.0231f,-0.0453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.9305f,-0.3198f,-0.1786f,-0.27f,0.1612f,0.0803f,-0.9836f,1.3096f,0.3289f,-0.9441f,-0.0231f,0.173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.9305f,-0.3198f,-0.1786f,-0.2607f,0.1612f,0.0803f,-0.9836f,1.3072f,0.3289f,-0.9441f,-0.0231f,0.2003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.2054f,-0.3677f,1.0701f,-0.4779f,-1.1312f,0.0923f,-0.1854f,1.3618f,-0.0266f,-1.0857f,-0.3782f,-0.441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.9305f,-0.3198f,-0.1786f,-0.3439f,0.1612f,0.0803f,-0.9836f,1.3281f,0.3289f,-0.9441f,-0.0231f,-0.0453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9671f,-0.0419f,0.251f,0.3439f,-0.1258f,0.9361f,-0.3284f,1.3281f,-0.2212f,-0.3492f,-0.9106f,0.0453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9671f,-0.0419f,0.251f,0.3536f,-0.1258f,0.9361f,-0.3284f,1.1116f,-0.2212f,-0.3492f,-0.9106f,0.126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9671f,-0.0419f,0.251f,0.3548f,-0.1258f,0.9361f,-0.3284f,1.0846f,-0.2212f,-0.3492f,-0.9106f,0.1361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.2887f,-0.0482f,-1.1121f,0.3263f,0.3777f,1.0765f,-0.1447f,1.7205f,1.0472f,-0.4016f,-0.2544f,-0.1011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9671f,-0.0419f,0.251f,0.3439f,-0.1258f,0.9361f,-0.3284f,1.3281f,-0.2212f,-0.3492f,-0.9106f,0.0453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1402f,0f,-0.1501f,0f,0f,1.15f,0f,1.5738f,0.1501f,0f,1.1402f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0906f,0f,0.1436f,0f,0f,1.1f,0f,1.4004f,-0.1436f,0f,-1.0906f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":7.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/dismantle/zzz/frames/11_locator_commands
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/dismantle/zzz/frames/11_locator_constant
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/dismantle/zzz/frames/11_locator_sfx