# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.9476f,0.0149f,0.3191f,0f,0f,0.9989f,-0.0466f,0.75f,-0.3194f,-0.0442f,-0.9466f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9476f,0.0149f,0.3191f,0f,0f,0.9989f,-0.0466f,0.75f,-0.3194f,-0.0442f,-0.9466f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,-0.0075f,0.0036f,0.0107f,-0.0081f,0.9718f,-0.2357f,1.468f,-0.0018f,-0.2358f,-0.9718f,-0.0318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,-0.0049f,-0.0024f,0.0094f,0.0053f,0.6317f,0.1532f,1.635f,0.0011f,-0.1533f,0.6317f,-0.0723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,-0.0075f,0.0036f,0.0107f,-0.0081f,0.9718f,-0.2357f,1.468f,-0.0018f,-0.2358f,-0.9718f,-0.0318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7574f,0.6434f,-0.111f,-0.346f,0.0243f,-0.1421f,-0.9896f,1.3743f,-0.6525f,-0.7522f,0.092f,-0.1474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7574f,0.6434f,-0.111f,-0.5069f,0.0243f,-0.1421f,-0.9896f,1.4099f,-0.6525f,-0.7522f,0.092f,0.0406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7574f,0.6434f,-0.111f,-0.527f,0.0243f,-0.1421f,-0.9896f,1.4143f,-0.6525f,-0.7522f,0.092f,0.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.1276f,0.7399f,0.871f,-0.0545f,-1.138f,-0.1635f,-0.0279f,1.3099f,0.1058f,-0.865f,0.7503f,-0.4883f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7574f,0.6434f,-0.111f,-0.346f,0.0243f,-0.1421f,-0.9896f,1.3743f,-0.6525f,-0.7522f,0.092f,-0.1474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9075f,0.0407f,0.4181f,0.3647f,-0.1785f,0.8637f,-0.4714f,1.3743f,-0.3803f,-0.5024f,-0.7765f,0.0922f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9075f,0.0407f,0.4181f,0.3545f,-0.1785f,0.8637f,-0.4714f,1.1584f,-0.3803f,-0.5024f,-0.7765f,0.2178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9075f,0.0407f,0.4181f,0.3532f,-0.1785f,0.8637f,-0.4714f,1.1314f,-0.3803f,-0.5024f,-0.7765f,0.2335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.4808f,0.0468f,-1.0436f,0.3831f,0.5421f,0.9932f,-0.2053f,1.7657f,0.893f,-0.5778f,-0.4373f,-0.1355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9075f,0.0407f,0.4181f,0.3647f,-0.1785f,0.8637f,-0.4714f,1.3743f,-0.3803f,-0.5024f,-0.7765f,0.0922f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0898f,0.0171f,-0.3669f,0.0133f,0f,1.1487f,0.0536f,1.6397f,0.3673f,-0.0508f,1.0886f,-0.0394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0424f,0.0164f,0.351f,0.0105f,0f,1.0988f,-0.0513f,1.4524f,-0.3514f,-0.0486f,-1.0412f,-0.0311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":18.6284722222,"rx":-2.6736111111}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/dismantle/zzz/frames/17_locator_constant