# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.9994f,0.0001f,-0.0355f,0f,0f,1f,0.0016f,0.75f,0.0355f,0.0016f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9994f,0.0001f,-0.0355f,0f,0f,1f,0.0016f,0.75f,0.0355f,0.0016f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9358f,-0.0027f,-0.3526f,0f,-0.0235f,0.9982f,0.0548f,1.4687f,0.3518f,0.0596f,-0.9342f,0.0012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6083f,-0.0018f,0.2292f,-0.0004f,0.0153f,0.6488f,-0.0356f,1.6403f,-0.2287f,0.0388f,0.6072f,0.0114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9358f,-0.0027f,-0.3526f,0f,-0.0235f,0.9982f,0.0548f,1.4687f,0.3518f,0.0596f,-0.9342f,0.0012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8278f,-0.5398f,-0.1529f,-0.3747f,0.1631f,0.0292f,-0.9862f,1.375f,0.5368f,-0.8413f,0.0638f,0.0143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8278f,-0.5398f,-0.1529f,-0.2398f,0.1631f,0.0292f,-0.9862f,1.3677f,0.5368f,-0.8413f,0.0638f,0.2247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8278f,-0.5398f,-0.1529f,-0.2229f,0.1631f,0.0292f,-0.9862f,1.3668f,0.5368f,-0.8413f,0.0638f,0.251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.1758f,-0.6208f,0.952f,-0.6193f,-1.1341f,0.0336f,-0.1875f,1.3882f,0.0734f,-0.9675f,-0.6173f,-0.3669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8278f,-0.5398f,-0.1529f,-0.3747f,0.1631f,0.0292f,-0.9862f,1.375f,0.5368f,-0.8413f,0.0638f,0.0143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9889f,-0.1016f,0.1086f,0.3748f,-0.1334f,0.9287f,-0.3459f,1.375f,-0.0658f,-0.3565f,-0.932f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9889f,-0.1016f,0.1086f,0.4002f,-0.1334f,0.9287f,-0.3459f,1.1428f,-0.0658f,-0.3565f,-0.932f,0.0768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9889f,-0.1016f,0.1086f,0.4034f,-0.1334f,0.9287f,-0.3459f,1.1138f,-0.0658f,-0.3565f,-0.932f,0.088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.1249f,-0.1168f,-1.1372f,0.3288f,0.3978f,1.0681f,-0.1534f,1.7958f,1.0718f,-0.41f,-0.0756f,-0.1739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9889f,-0.1016f,0.1086f,0.3748f,-0.1334f,0.9287f,-0.3459f,1.375f,-0.0658f,-0.3565f,-0.932f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1493f,0.0001f,0.0409f,0.0001f,0f,1.15f,-0.0019f,1.6406f,-0.0409f,0.0019f,1.1493f,0.0014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0993f,0.0001f,-0.0391f,0f,0f,1.1f,0.0018f,1.4531f,0.0391f,0.0018f,-1.0993f,0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":357.962962963,"rx":0.0925925926}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/dismantle/zzz/frames/9_locator_constant
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:yuji/animations/dismantle/zzz/frames/9_root_function