# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.9953f,-0.0628f,0.0742f,0.1349f,-0.0464f,0.9777f,0.2048f,0.4057f,-0.0854f,0.2004f,-0.976f,-0.0373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.0948f,-0.069f,-0.0817f,0.1122f,0.051f,1.0755f,-0.2253f,0.759f,0.094f,0.2204f,1.0736f,0.0351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.1943f,-0.0753f,-0.0891f,0.1129f,0.0557f,1.1732f,-0.2458f,0.7476f,0.1025f,0.2405f,1.1712f,0.0327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.9953f,-0.0628f,0.0742f,0.1349f,-0.0464f,0.9777f,0.2048f,0.4057f,-0.0854f,0.2004f,-0.976f,-0.0373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9953f,-0.0555f,0.0798f,0.1156f,-0.0464f,0.9926f,0.1119f,0.75f,-0.0854f,0.1077f,-0.9905f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.0948f,-0.061f,-0.0878f,0.0988f,0.051f,1.0919f,-0.1231f,1.0513f,0.094f,0.1184f,1.0896f,0.0327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.9953f,-0.0555f,0.0798f,0.1156f,-0.0464f,0.9926f,0.1119f,0.75f,-0.0854f,0.1077f,-0.9905f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.9823f,0.0405f,-0.1829f,-0.1145f,0.0405f,0.9992f,0.004f,0.4127f,0.1829f,-0.0035f,-0.9831f,0.0808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0805f,0.0446f,0.2012f,-0.0998f,-0.0445f,1.0991f,-0.0044f,0.7737f,-0.2012f,-0.0038f,1.0814f,0.0795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1787f,0.0487f,0.2195f,-0.1003f,-0.0486f,1.199f,-0.0048f,0.7621f,-0.2195f,-0.0042f,1.1797f,0.0796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.9823f,0.0405f,-0.1829f,-0.1145f,0.0405f,0.9992f,0.004f,0.4127f,0.1829f,-0.0035f,-0.9831f,0.0808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9823f,-0.0033f,-0.1873f,-0.1156f,0.0405f,0.9725f,-0.2293f,0.75f,0.1829f,-0.2329f,-0.9551f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0805f,-0.0036f,0.2061f,-0.1166f,-0.0445f,1.0698f,0.2523f,1.0452f,-0.2012f,-0.2562f,1.0507f,-0.0707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.9823f,-0.0033f,-0.1873f,-0.1156f,0.0405f,0.9725f,-0.2293f,0.75f,0.1829f,-0.2329f,-0.9551f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.8826f,0.0576f,-0.4666f,0f,-0.0104f,0.9898f,0.142f,0.75f,0.4701f,0.1302f,-0.873f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.8826f,0.0576f,-0.4666f,0f,-0.0104f,0.9898f,0.142f,0.75f,0.4701f,0.1302f,-0.873f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9946f,0.0397f,-0.0955f,0.0383f,0.037f,0.9989f,0.0302f,1.4081f,0.0966f,0.0265f,-0.995f,0.0866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6465f,0.0258f,0.0621f,0.0446f,-0.024f,0.6493f,-0.0196f,1.5669f,-0.0628f,0.0172f,0.6467f,0.0908f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9946f,0.0397f,-0.0955f,0.0383f,0.037f,0.9989f,0.0302f,1.4081f,0.0966f,0.0265f,-0.995f,0.0866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8543f,0.0601f,-0.5163f,-0.2728f,0.2034f,0.9527f,-0.2258f,1.3186f,0.4783f,-0.2979f,-0.8261f,0.2383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8543f,-0.4138f,-0.3145f,-0.3004f,0.2034f,0.2906f,-0.935f,1.0792f,0.4783f,-0.8627f,-0.1641f,0.2909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8543f,-0.4138f,-0.3145f,-0.2884f,0.2034f,0.2906f,-0.935f,1.0708f,0.4783f,-0.8627f,-0.1641f,0.3158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.5937f,0.0691f,0.9824f,-0.2476f,-0.2597f,1.0956f,-0.2339f,1.7179f,-0.95f,-0.3426f,-0.5501f,0.1135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8543f,0.0601f,-0.5163f,-0.2728f,0.2034f,0.9527f,-0.2258f,1.3186f,0.4783f,-0.2979f,-0.8261f,0.2383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.721f,-0.6754f,0.1548f,0.3395f,-0.6909f,0.7177f,-0.0865f,1.3259f,-0.0527f,-0.1693f,-0.9841f,-0.0878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.721f,-0.1792f,0.6693f,0.51f,-0.6909f,0.2594f,-0.6748f,1.1466f,-0.0527f,-0.949f,-0.3109f,-0.0712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.721f,-0.1792f,0.6693f,0.5152f,-0.6909f,0.2594f,-0.6748f,1.1391f,-0.0527f,-0.949f,-0.3109f,-0.0437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.178f,-0.7767f,-0.8292f,0.0564f,0.0995f,0.8254f,-0.7945f,1.6267f,1.1318f,-0.1947f,-0.0606f,-0.1588f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.721f,-0.6754f,0.1548f,0.3395f,-0.6909f,0.7177f,-0.0865f,1.3259f,-0.0527f,-0.1693f,-0.9841f,-0.0878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.015f,0.0663f,0.5366f,0.0475f,0.012f,1.1383f,-0.1633f,1.5654f,-0.5406f,0.1497f,1.0039f,0.1073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.9708f,0.0634f,-0.5133f,0.0375f,-0.0115f,1.0888f,0.1562f,1.3938f,0.5171f,0.1432f,-0.9603f,0.0847f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":331.8736228159,"rx":8.1635728978}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/natural_talent/zzz/frames/17_locator_constant