# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.9955f,-0.0612f,0.073f,0.1453f,-0.0454f,0.9786f,0.2006f,0.3776f,-0.0837f,0.1964f,-0.977f,-0.0396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.095f,-0.0673f,-0.0803f,0.1214f,0.05f,1.0765f,-0.2206f,0.7599f,0.0921f,0.216f,1.0746f,0.0372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.1945f,-0.0734f,-0.0876f,0.1222f,0.0545f,1.1743f,-0.2407f,0.7477f,0.1004f,0.2356f,1.1723f,0.0347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.9955f,-0.0612f,0.073f,0.1453f,-0.0454f,0.9786f,0.2006f,0.3776f,-0.0837f,0.1964f,-0.977f,-0.0396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9955f,-0.0542f,0.0783f,0.125f,-0.0454f,0.9929f,0.1095f,0.75f,-0.0837f,0.1055f,-0.9909f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.095f,-0.0596f,-0.0861f,0.1072f,0.05f,1.0922f,-0.1205f,1.0758f,0.0921f,0.116f,1.09f,0.0346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.9955f,-0.0542f,0.0783f,0.125f,-0.0454f,0.9929f,0.1095f,0.75f,-0.0837f,0.1055f,-0.9909f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.983f,0.0397f,-0.1792f,-0.1241f,0.0397f,0.9992f,0.0038f,0.3849f,0.1792f,-0.0034f,-0.9838f,0.0856f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0813f,0.0437f,0.1971f,-0.1086f,-0.0437f,1.0991f,-0.0042f,0.7752f,-0.1971f,-0.0037f,1.0822f,0.0843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1796f,0.0477f,0.2151f,-0.1091f,-0.0476f,1.199f,-0.0045f,0.7627f,-0.2151f,-0.0041f,1.1806f,0.0843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.983f,0.0397f,-0.1792f,-0.1241f,0.0397f,0.9992f,0.0038f,0.3849f,0.1792f,-0.0034f,-0.9838f,0.0856f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.983f,-0.0023f,-0.1836f,-0.125f,0.0397f,0.9736f,-0.2249f,0.75f,0.1792f,-0.2283f,-0.9569f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0813f,-0.0026f,0.2019f,-0.1258f,-0.0437f,1.0709f,0.2473f,1.0695f,-0.1971f,-0.2512f,1.0526f,-0.0749f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.983f,-0.0023f,-0.1836f,-0.125f,0.0397f,0.9736f,-0.2249f,0.75f,0.1792f,-0.2283f,-0.9569f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.8988f,0.0553f,-0.4348f,0f,-0.0062f,0.9903f,0.1389f,0.75f,0.4383f,0.1275f,-0.8897f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.8988f,0.0553f,-0.4348f,0f,-0.0062f,0.9903f,0.1389f,0.75f,0.4383f,0.1275f,-0.8897f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9948f,0.0397f,-0.0942f,0.0398f,0.0385f,0.9991f,0.0151f,1.4618f,0.0947f,0.0114f,-0.9954f,0.0917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6466f,0.0258f,0.0612f,0.0466f,-0.025f,0.6494f,-0.0098f,1.6335f,-0.0616f,0.0074f,0.647f,0.0936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9948f,0.0397f,-0.0942f,0.0398f,0.0385f,0.9991f,0.0151f,1.4618f,0.0947f,0.0114f,-0.9954f,0.0917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8722f,0.0629f,-0.485f,-0.3025f,0.1922f,0.956f,-0.2217f,1.3666f,0.4497f,-0.2866f,-0.8459f,0.2441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.8722f,-0.3789f,-0.3092f,-0.332f,0.1922f,0.3157f,-0.9292f,1.1076f,0.4497f,-0.8699f,-0.2025f,0.2975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.8722f,-0.3789f,-0.3092f,-0.3202f,0.1922f,0.3157f,-0.9292f,1.0977f,0.4497f,-0.8699f,-0.2025f,0.3247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.5578f,0.0723f,1.0031f,-0.274f,-0.255f,1.0994f,-0.2211f,1.7998f,-0.9728f,-0.3296f,-0.5172f,0.1142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.8722f,0.0629f,-0.485f,-0.3025f,0.1922f,0.956f,-0.2217f,1.3666f,0.4497f,-0.2866f,-0.8459f,0.2441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.728f,-0.666f,0.1623f,0.3716f,-0.6827f,0.7259f,-0.0833f,1.3713f,-0.0623f,-0.1714f,-0.9832f,-0.0846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.728f,-0.183f,0.6606f,0.5532f,-0.6827f,0.2812f,-0.6744f,1.1759f,-0.0623f,-0.942f,-0.3297f,-0.0659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.728f,-0.183f,0.6606f,0.559f,-0.6827f,0.2812f,-0.6744f,1.1671f,-0.0623f,-0.942f,-0.3297f,-0.0364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.1866f,-0.766f,-0.8372f,0.0698f,0.0958f,0.8348f,-0.7851f,1.7002f,1.1307f,-0.1972f,-0.0717f,-0.1623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.728f,-0.666f,0.1623f,0.3716f,-0.6827f,0.7259f,-0.0833f,1.3713f,-0.0623f,-0.1714f,-0.9832f,-0.0846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0336f,0.0636f,0.5001f,0.0493f,0.0072f,1.1388f,-0.1597f,1.632f,-0.5041f,0.1467f,1.0232f,0.1136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.9887f,0.0609f,-0.4783f,0.0389f,-0.0069f,1.0893f,0.1528f,1.4463f,0.4821f,0.1403f,-0.9787f,0.0897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":333.9534182069,"rx":7.9834223789}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/natural_talent/zzz/frames/18_locator_constant