# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.maul.frame matches 12.. run scoreboard players set @s aj.maul.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.maul.frame
execute at @s run function animated_java:billy/animations/maul/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.maul.frame 1