# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouthb) {transformation: [-1f,0.0051f,-0.0001f,-0.0008f,0.0051f,0.9999f,-0.0093f,0.6841f,0f,-0.0093f,-1f,1.0618f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head3) {transformation: [-1f,0.0051f,0f,0f,0.0051f,1f,0.0047f,0.8421f,0f,0.0047f,-1f,0.6876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0.2187f,0f,1f,-0.0033f,0.3123f,0f,-0.0033f,-1f,0.4994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontleftleg) {transformation: [-1f,0f,0f,0.2187f,0f,1f,-0.0033f,0.4054f,0f,-0.0033f,-1f,0.3116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom2) {transformation: [-1f,0f,0f,-0.2188f,0f,1f,-0.0033f,0.3123f,0f,-0.0033f,-1f,0.4994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontrightleg2) {transformation: [-1f,0f,0f,-0.2188f,0f,1f,-0.0033f,0.4054f,0f,-0.0033f,-1f,0.3116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front) {transformation: [-1f,0f,0f,0f,0f,1f,0.0022f,0.8125f,0f,0.0022f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}