# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.gojo.locator', 'aj.gojo.locator.blue_hand']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:gojo/zzz/2
data modify entity @s data.locators.blue_hand.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.gojo.locator', 'aj.gojo.locator.purple_hand']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:gojo/zzz/3
data modify entity @s data.locators.purple_hand.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.gojo.locator', 'aj.gojo.locator.red_hand']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:gojo/zzz/4
data modify entity @s data.locators.red_hand.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.gojo.locator', 'aj.gojo.locator.blue']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:gojo/zzz/5
data modify entity @s data.locators.blue.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.gojo.locator', 'aj.gojo.locator.red']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:gojo/zzz/6
data modify entity @s data.locators.red.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.gojo.locator', 'aj.gojo.locator.purple']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:gojo/zzz/7
data modify entity @s data.locators.purple.uuid set from storage aj:uuid main.out
summon item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.camera', 'aj.gojo.camera', 'aj.gojo.camera'], teleport_duration: 2}
execute as @e[type=item_display,tag=aj.new,tag=aj.global.camera,limit=1,distance=..0.01] run function animated_java:gojo/zzz/8
data modify entity @s data.cameras.camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.blue_hand1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blue_hand1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.purple_hand1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_purple_hand1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.red_hand1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_red_hand1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.bottom2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.rightarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.bottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.leftarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.bottom3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.rightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.bottom4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.leftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.blue1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blue1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gojo.node.red1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_red1 set from storage aj:uuid main.out