# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function interactables:recieve_item/run_command {objective:"interactablesUniversal.RecieveItemID",what:"tag=interactablesUniversal.RecieveItemSpectator",output:"function custom:abilities/dice/roll/20/tommy_gun/inform"}
function interactables:recieve_item/reset