# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.gojo.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gojo', 'function_path': 'animated_java:gojo/animations/reverse_cursed_technique/next_frame'}
execute if score @s aj.reverse_cursed_technique.frame matches 25.. run scoreboard players set @s aj.reverse_cursed_technique.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.reverse_cursed_technique.frame
execute at @s run function animated_java:gojo/animations/reverse_cursed_technique/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.reverse_cursed_technique.frame 1