# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ 0 0
execute as @e[type=!#custom:not_mob,tag=gojoPickedUp,limit=4] run function custom:items/gojo/moves/2/end