# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.billy_cutscenes.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'billy_cutscenes', 'function_path': 'animated_java:billy_cutscenes/at_locator'}
data remove storage aj:temp args
$data modify storage aj:temp args merge value {name:'$(name)', command:'$(command)'}
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:billy_cutscenes/zzz/at_locator/as_data {name: $(name)}