# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.the_world_cutscenes.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.the_world_cutscenes.animation.impale.playing] run function animated_java:the_world_cutscenes/animations/impale/zzz/on_tick
execute on passengers if entity @s[tag=aj.the_world_cutscenes.data] run function animated_java:the_world_cutscenes/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~