# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.domain_clash.root] run return 0
execute on passengers if entity @s[tag=aj.domain_clash.data] unless data entity @s {data:{rigHash: '64291ba26a7905b8629ae66e7afec2f13b0f808ab3b509282de83682c10b7377'}} on vehicle run function animated_java:domain_clash/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1