# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.yuji.animation.natural_talent.playing] run function aj:yuji/animations/natural_talent/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.majin_kick.playing] run function aj:yuji/animations/majin_kick/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.majin_kick_fall.playing] run function aj:yuji/animations/majin_kick_fall/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.sukuna.playing] run function aj:yuji/animations/sukuna/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.sukuna_old.playing] run function aj:yuji/animations/sukuna_old/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.king_of_curses.playing] run function aj:yuji/animations/king_of_curses/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.cleave.playing] run function aj:yuji/animations/cleave/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.dismantle.playing] run function aj:yuji/animations/dismantle/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.fuga.playing] run function aj:yuji/animations/fuga/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.fuga2.playing] run function aj:yuji/animations/fuga2/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.obtain.playing] run function aj:yuji/animations/obtain/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.black_flash_assault.playing] run function aj:yuji/animations/black_flash_assault/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.black_flash_assault2.playing] run function aj:yuji/animations/black_flash_assault2/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.black_flash_assault3.playing] run function aj:yuji/animations/black_flash_assault3/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.domain_expansion.playing] run function aj:yuji/animations/domain_expansion/zzz/on_tick
execute if entity @s[tag=aj.yuji.animation.cleave_old.playing] run function aj:yuji/animations/cleave_old/zzz/on_tick