# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouthb) {transformation: [-1f,0f,0f,0f,0f,0.9941f,0.1084f,1.5536f,0f,0.1084f,-0.9941f,0.1602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head3) {transformation: [-1f,0f,0f,0f,0f,0.9977f,0.0673f,1.7348f,0f,0.0673f,-0.9977f,-0.2034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0.2188f,0f,0.4601f,-0.8878f,1.5557f,0f,-0.8878f,-0.4601f,-0.8263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontleftleg) {transformation: [-1f,0f,0f,0.2188f,0f,-0.0167f,-0.9999f,1.3667f,0f,-0.9999f,0.0167f,-0.9169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom2) {transformation: [-1f,0f,0f,-0.2187f,0f,0.4601f,-0.8878f,1.5557f,0f,-0.8878f,-0.4601f,-0.8263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontrightleg2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.0167f,-0.9999f,1.3667f,0f,-0.9999f,0.0167f,-0.9169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front) {transformation: [-1f,0f,0f,0f,0f,0.6463f,-0.7631f,1.1423f,0f,-0.7631f,-0.6463f,-0.6643f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,0.4314f,-0.9022f,0.5f,0f,-0.9022f,-0.4314f,-0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:billy/animations/encourage/zzz/frames/19_locator_commands
data modify entity @s data merge value {"cameras":{},"locators":{"mount":{"posx":-7.443710485743637e-18,"posy":1.9361938586532292,"posz":0.0607825088092846,"roty":0,"rotx":3.8617292455418197}}}