# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouthb) {transformation: [-1f,0f,0f,0f,0f,0.9758f,-0.2187f,1.8679f,0f,-0.2187f,-0.9758f,0.1111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head3) {transformation: [-1f,0f,0f,0f,0f,0.8141f,-0.5807f,1.7773f,0f,-0.5807f,-0.8141f,-0.2849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0.2188f,0f,0.1676f,-0.9859f,1.5463f,0f,-0.9859f,-0.1676f,-1.0364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontleftleg) {transformation: [-1f,0f,0f,0.2188f,0f,-0.3329f,-0.943f,1.3383f,0f,-0.943f,0.3329f,-1.0624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom2) {transformation: [-1f,0f,0f,-0.2187f,0f,0.1676f,-0.9859f,1.5463f,0f,-0.9859f,-0.1676f,-1.0364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontrightleg2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.3329f,-0.943f,1.3383f,0f,-0.943f,0.3329f,-1.0624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front) {transformation: [-1f,0f,0f,0f,0f,0.5651f,-0.8251f,1.1409f,0f,-0.8251f,-0.5651f,-0.6829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,0.405f,-0.9143f,0.5f,0f,-0.9143f,-0.405f,-0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:billy/animations/encourage/zzz/frames/7_locator_commands
data modify entity @s data merge value {"cameras":{},"locators":{"mount":{"posx":2.552617983209788e-17,"posy":2.100577353221488,"posz":-0.20843707630534927,"roty":0,"rotx":-35.50139851851852}}}