# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouthb) {transformation: [-1f,0f,0f,0f,0f,0.8428f,-0.5382f,2.1248f,0f,-0.5382f,-0.8428f,-0.1443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head3) {transformation: [-1f,0f,0f,0f,0f,0.3637f,-0.9315f,1.8323f,0f,-0.9315f,-0.3637f,-0.4263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0.2188f,0f,-0.2182f,-0.9759f,1.4468f,0f,-0.9759f,0.2182f,-1.2415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontleftleg) {transformation: [-1f,0f,0f,0.2188f,0f,-0.6794f,-0.7338f,1.2455f,0f,-0.7338f,0.6794f,-1.1829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.2182f,-0.9759f,1.4468f,0f,-0.9759f,0.2182f,-1.2415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frontrightleg2) {transformation: [-1f,0f,0f,-0.2187f,0f,-0.6794f,-0.7338f,1.2455f,0f,-0.7338f,0.6794f,-1.1829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_front) {transformation: [-1f,0f,0f,0f,0f,0.4173f,-0.9088f,1.1377f,0f,-0.9088f,-0.4173f,-0.7108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,0.3647f,-0.9311f,0.5f,0f,-0.9311f,-0.3647f,-0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function animated_java:billy/animations/encourage/zzz/frames/9_locator_commands
data modify entity @s data merge value {"cameras":{},"locators":{"mount":{"posx":6.602064833575073e-17,"posy":2.1447907760100153,"posz":-0.5390995051121423,"roty":0,"rotx":-68.66988444444446}}}