# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [0.9962f,-0.0468f,0.0735f,-0.1247f,0f,0.8434f,0.5373f,0.3629f,-0.0872f,-0.5353f,0.8402f,-0.1039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [-1.0958f,-0.0515f,-0.0809f,-0.1416f,0f,0.9277f,-0.591f,0.6677f,0.0959f,-0.5888f,-0.9242f,-0.2973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [-1.1954f,-0.0562f,-0.0882f,-0.1411f,0f,1.0121f,-0.6448f,0.6579f,0.1046f,-0.6423f,-1.0082f,-0.2911f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [0.9962f,-0.0468f,0.0735f,-0.1247f,0f,0.8434f,0.5373f,0.3629f,-0.0872f,-0.5353f,0.8402f,-0.1039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0.9962f,0.0262f,0.0831f,-0.1156f,0f,0.9537f,-0.3007f,0.6938f,-0.0872f,0.2996f,0.9501f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [-1.0958f,0.0288f,-0.0914f,-0.1077f,0f,1.0491f,0.3308f,0.9832f,0.0959f,0.3295f,-1.0451f,0.0909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [0.9962f,0.0262f,0.0831f,-0.1156f,0f,0.9537f,-0.3007f,0.6938f,-0.0872f,0.2996f,0.9501f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.999f,-0.0167f,-0.0403f,0.1156f,0f,0.9239f,-0.3827f,0.6938f,0.0436f,0.3823f,0.923f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0.999f,0.0076f,-0.043f,0.1214f,0f,0.9848f,0.1736f,0.3733f,0.0436f,-0.1735f,0.9839f,-0.1326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [-1.099f,0.0083f,0.0473f,0.1242f,0f,1.0833f,-0.191f,0.7291f,-0.048f,-0.1908f,-1.0823f,-0.1953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [-1.1989f,0.0091f,0.0515f,0.1241f,0f,1.1818f,-0.2084f,0.7177f,-0.0523f,-0.2082f,-1.1806f,-0.1933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [0.999f,0.0076f,-0.043f,0.1214f,0f,0.9848f,0.1736f,0.3733f,0.0436f,-0.1735f,0.9839f,-0.1326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [-1.099f,-0.0184f,0.0443f,0.1106f,0f,1.0163f,0.421f,0.9742f,-0.048f,0.4206f,-1.0153f,0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [0.999f,-0.0167f,-0.0403f,0.1156f,0f,0.9239f,-0.3827f,0.6938f,0.0436f,0.3823f,0.923f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0.9541f,-0.0131f,0.2991f,0f,0.0391f,0.9959f,-0.0812f,0.6938f,-0.2968f,0.0891f,0.9508f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [0.9541f,-0.0131f,0.2991f,0f,0.0391f,0.9959f,-0.0812f,0.6938f,-0.2968f,0.0891f,0.9508f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.8563f,-0.2235f,0.4656f,-0.0087f,-0.0729f,0.8401f,0.5375f,1.3559f,-0.5113f,-0.4942f,0.7031f,0.0593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [-0.5566f,-0.1453f,-0.3027f,-0.0442f,0.0474f,0.5461f,-0.3493f,1.4895f,0.3324f,-0.3212f,-0.457f,-0.0193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [0.8563f,-0.2235f,0.4656f,-0.0087f,-0.0729f,0.8401f,0.5375f,1.3559f,-0.5113f,-0.4942f,0.7031f,0.0593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.4014f,-0.1985f,0.8941f,0.3234f,0.5451f,0.8363f,-0.059f,1.2831f,-0.736f,0.511f,0.4439f,-0.0514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.4014f,0.8123f,0.4232f,0.3985f,0.5451f,0.1594f,-0.8231f,1.0701f,-0.736f,0.5611f,-0.3787f,-0.1682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,0.1965f,0f,0f,0f,1.0398f,0f,0f,0f,-0.3302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,0.1872f,0f,0f,0f,1.0272f,0f,0f,0f,-0.3132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,0.1779f,0f,0f,0f,1.0146f,0f,0f,0f,-0.2962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.4014f,0.8123f,0.4232f,0.3751f,0.5451f,0.1594f,-0.8231f,1.0655f,-0.736f,0.5611f,-0.3787f,-0.1844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [1.0282f,-0.2283f,-0.4617f,0.2402f,-0.0679f,0.9618f,-0.6268f,1.6336f,0.5105f,0.5877f,0.8464f,0.1628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.4014f,-0.1985f,0.8941f,0.3234f,0.5451f,0.8363f,-0.059f,1.2831f,-0.736f,0.511f,0.4439f,-0.0514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.5402f,0.1228f,-0.8325f,-0.3385f,-0.8391f,0.0033f,-0.544f,1.256f,-0.0641f,0.9924f,0.1048f,0.1545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0.5402f,-0.5308f,-0.653f,-0.3858f,-0.8391f,-0.3989f,-0.3699f,1.2436f,-0.0641f,0.7477f,-0.6609f,-0.0821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,-0.2492f,0f,0f,0f,1.3482f,0f,0f,0f,-0.2769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [0.5402f,-0.5308f,-0.653f,-0.3705f,-0.8391f,-0.3989f,-0.3699f,1.2551f,-0.0641f,0.7477f,-0.6609f,-0.1037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0.9574f,0.1412f,0.6213f,-0.2871f,0.6256f,0.0037f,-0.9649f,1.2573f,-0.1205f,1.1413f,-0.0737f,0.5705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [0.5402f,0.1228f,-0.8325f,-0.3385f,-0.8391f,0.0033f,-0.544f,1.256f,-0.0641f,0.9924f,0.1048f,0.1545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [-1.0973f,-0.015f,-0.344f,-0.0108f,-0.0449f,1.1453f,0.0934f,1.5142f,0.3413f,0.1025f,-1.0934f,0.0734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [1.0495f,-0.0144f,0.329f,-0.0085f,0.043f,1.0955f,-0.0893f,1.3415f,-0.3265f,0.0981f,1.0458f,0.058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":-0.177074654,"py":1.3039840892,"pz":0.2902284551,"ry":162.5373374841,"rx":-4.6564515351}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/flurry/zzz/frames/20_locator_constant