# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-0.751f,-0.6592f,0.0379f,0.3883f,-0.4591f,0.5625f,0.6876f,1.0805f,-0.4746f,0.499f,-0.7251f,1.6457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-0.751f,-0.2172f,0.6235f,0.5882f,-0.4591f,0.8505f,-0.2566f,1.1172f,-0.4746f,-0.479f,-0.7385f,1.2939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-0.8732f,-0.1939f,0.4471f,0.8724f,-0.0334f,0.9391f,0.3421f,0.5466f,-0.4862f,0.2838f,-0.8265f,1.2725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-0.8732f,-0.0716f,0.482f,0.9561f,-0.0334f,0.9956f,0.0874f,0.6563f,-0.4862f,0.0602f,-0.8718f,1.1147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-0.8732f,0.0132f,0.4871f,0.4754f,-0.0334f,0.9957f,-0.0868f,0.5996f,-0.4862f,-0.0921f,-0.869f,1.0821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-0.8732f,0.0976f,0.4774f,0.574f,-0.0334f,0.9655f,-0.2584f,0.6417f,-0.4862f,-0.2416f,-0.8398f,0.902f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-0.8732f,0.0132f,0.4871f,0.9531f,-0.0334f,0.9957f,-0.0868f,1.0209f,-0.4862f,-0.0921f,-0.869f,0.645f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-0.9063f,0.1786f,0.383f,1.1127f,0f,0.9063f,-0.4226f,0.5f,-0.4226f,-0.383f,-0.8214f,0.3027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4688f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4688f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4688f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4688f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4688f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0.8486f,0f,0f,0f,1.4687f,0f,0f,0f,0.8691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blb) {transformation: [-0.9063f,-0.0619f,0.4181f,1.2705f,0f,0.9892f,0.1465f,0.2705f,-0.4226f,0.1328f,-0.8965f,0.6299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backleftleg) {transformation: [-0.9063f,-0.0734f,0.4162f,1.3676f,0f,0.9848f,0.1736f,0.4063f,-0.4226f,0.1574f,-0.8925f,0.4216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(brb) {transformation: [-0.9063f,-0.0019f,0.4226f,0.7541f,0f,1f,0.0046f,0.3012f,-0.4226f,0.0042f,-0.9063f,0.4063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backrightleg) {transformation: [-0.9063f,-0.0193f,0.4222f,0.8578f,0f,0.999f,0.0458f,0.4063f,-0.4226f,0.0415f,-0.9054f,0.1838f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.3814905891,"py":1.1070774919,"pz":1.6307236857,"ry":40.1764444995,"rx":-14.8681770272},"position":{"px":0.9014136414,"py":0,"pz":0.7558557633,"ry":25,"rx":0},"text_location":{"px":0.8485863586,"py":0.75,"pz":0.8691442367,"ry":25,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args