# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.999f,-0.0387f,-0.0212f,0.1176f,-0.0384f,0.9992f,-0.0136f,0.4089f,0.0217f,-0.0128f,-0.9997f,0.0616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.0989f,-0.0426f,0.0233f,0.1036f,0.0423f,1.0991f,0.0149f,0.77f,-0.0238f,-0.014f,1.0997f,0.057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.1988f,-0.0465f,0.0254f,0.104f,0.0461f,1.199f,0.0163f,0.7584f,-0.026f,-0.0153f,1.1996f,0.0571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.999f,-0.0387f,-0.0212f,0.1176f,-0.0384f,0.9992f,-0.0136f,0.4089f,0.0217f,-0.0128f,-0.9997f,0.0616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.999f,-0.0417f,-0.0145f,0.1031f,-0.0384f,0.9832f,-0.1783f,0.75f,0.0217f,-0.1776f,-0.9839f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.0989f,-0.0458f,0.0159f,0.0905f,0.0423f,1.0815f,0.1961f,1.0484f,-0.0238f,-0.1953f,1.0823f,-0.0539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.999f,-0.0417f,-0.0145f,0.1031f,-0.0384f,0.9832f,-0.1783f,0.75f,0.0217f,-0.1776f,-0.9839f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.8866f,0.3828f,0.2596f,-0.2669f,0.0949f,0.6999f,-0.7079f,0.5249f,-0.4527f,-0.603f,-0.6569f,0.2245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0.9753f,0.4211f,-0.2856f,-0.1286f,-0.1044f,0.7699f,0.7787f,0.7778f,0.498f,-0.6633f,0.7226f,0.0067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.0639f,0.4594f,-0.3115f,-0.133f,-0.1139f,0.8399f,0.8495f,0.7697f,0.5432f,-0.7236f,0.7882f,0.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.8866f,0.3828f,0.2596f,-0.2669f,0.0949f,0.6999f,-0.7079f,0.5249f,-0.4527f,-0.603f,-0.6569f,0.2245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.8866f,0.4f,0.2323f,-0.1281f,0.0949f,0.6488f,-0.755f,0.75f,-0.4527f,-0.6473f,-0.6132f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0.9753f,0.44f,-0.2555f,-0.0067f,-0.1044f,0.7137f,0.8305f,0.9469f,0.498f,-0.7121f,0.6745f,-0.1965f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.8866f,0.4f,0.2323f,-0.1281f,0.0949f,0.6488f,-0.755f,0.75f,-0.4527f,-0.6473f,-0.6132f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.8523f,-0.1101f,0.5114f,-0.0125f,-0.1373f,0.9904f,-0.0156f,0.75f,-0.5048f,-0.0835f,-0.8592f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.8523f,-0.1101f,0.5114f,-0.0125f,-0.1373f,0.9904f,-0.0156f,0.75f,-0.5048f,-0.0835f,-0.8592f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9936f,0.0018f,0.1127f,-0.0857f,-0.0071f,0.9969f,-0.0783f,1.4085f,-0.1125f,-0.0786f,-0.9905f,-0.0555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6459f,0.0012f,-0.0732f,-0.0854f,0.0046f,0.648f,0.0509f,1.567f,0.0731f,-0.0511f,0.6438f,-0.068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9936f,0.0018f,0.1127f,-0.0857f,-0.0071f,0.9969f,-0.0783f,1.4085f,-0.1125f,-0.0786f,-0.9905f,-0.0555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9775f,0.1015f,0.1848f,-0.3718f,0.1711f,0.8942f,0.4137f,1.2749f,-0.1232f,0.436f,-0.8915f,-0.2234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.9775f,0.1524f,0.1457f,-0.3938f,0.1711f,0.9772f,0.1256f,1.0706f,-0.1232f,0.1477f,-0.9813f,-0.3325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.9775f,0.1524f,0.1457f,-0.3982f,0.1711f,0.9772f,0.1256f,1.0423f,-0.1232f,0.1477f,-0.9813f,-0.3368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0.2125f,0.1168f,1.1242f,-0.3292f,0.4757f,1.0283f,-0.1967f,1.6497f,-1.0252f,0.5014f,0.1417f,-0.0406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.9775f,0.1015f,0.1848f,-0.3718f,0.1711f,0.8942f,0.4137f,1.2749f,-0.1232f,0.436f,-0.8915f,-0.2234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.7895f,-0.3215f,0.5228f,0.2195f,-0.4889f,0.8444f,-0.219f,1.3702f,-0.3711f,-0.4284f,-0.8239f,0.1268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.7895f,-0.0187f,0.6135f,0.3026f,-0.4889f,0.6235f,-0.6101f,1.1685f,-0.3711f,-0.7816f,-0.5014f,0.2157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.7895f,-0.0187f,0.6135f,0.3031f,-0.4889f,0.6235f,-0.6101f,1.1505f,-0.3711f,-0.7816f,-0.5014f,0.2383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.6012f,-0.3697f,-0.9079f,0.0847f,0.2518f,0.9711f,-0.5622f,1.7241f,0.9474f,-0.4927f,-0.4267f,-0.0528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.7895f,-0.3215f,0.5228f,0.2195f,-0.4889f,0.8444f,-0.219f,1.3702f,-0.3711f,-0.4284f,-0.8239f,0.1268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0.9801f,-0.1266f,-0.5881f,-0.1032f,0.1579f,1.139f,0.0179f,1.5659f,0.5805f,-0.096f,0.9881f,-0.0688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.9375f,-0.1211f,0.5625f,-0.0841f,-0.151f,1.0894f,-0.0171f,1.3942f,-0.5552f,-0.0918f,-0.9451f,-0.0543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":-0.0125,"py":0.75,"pz":0,"ry":30.7599334168,"rx":-0.8916503684}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/majin_kick_fall/zzz/frames/2_locator_constant