# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-1f,0f,0f,0.1156f,0f,0.9962f,0.0872f,0.3885f,0f,0.0872f,-0.9962f,0.1904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.1f,0f,0f,0.1156f,0f,1.0958f,-0.0959f,0.7485f,0f,0.0959f,1.0958f,0.2219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.2f,0f,0f,0.1156f,0f,1.1954f,-0.1046f,0.737f,0f,0.1046f,1.1954f,0.2209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-1f,0f,0f,0.1156f,0f,0.9962f,0.0872f,0.3885f,0f,0.0872f,-0.9962f,0.1904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.1156f,0f,0.5736f,-0.8192f,0.5875f,0f,-0.8192f,-0.5736f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.1f,0f,0f,0.1156f,0f,0.6309f,0.9011f,0.7616f,0f,-0.9011f,0.6309f,-0.3424f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-1f,0f,0f,0.1156f,0f,0.5736f,-0.8192f,0.5875f,0f,-0.8192f,-0.5736f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.9567f,-0.128f,0.2614f,-0.1888f,0.1706f,-0.9743f,0.1473f,0.6404f,0.2358f,0.1856f,0.9539f,-0.4287f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0524f,-0.1408f,-0.2876f,-0.235f,-0.1876f,-1.0717f,-0.1621f,0.2884f,-0.2594f,0.2041f,-1.0493f,-0.3616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.148f,-0.1536f,-0.3137f,-0.2335f,-0.2047f,-1.1691f,-0.1768f,0.2996f,-0.283f,0.2227f,-1.1447f,-0.3638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.9567f,-0.128f,0.2614f,-0.1888f,0.1706f,-0.9743f,0.1473f,0.6404f,0.2358f,0.1856f,0.9539f,-0.4287f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9567f,0.2108f,0.2007f,-0.1156f,0.1706f,-0.1524f,0.9735f,0.5875f,0.2358f,0.9656f,0.1099f,-0.0938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0524f,0.2319f,-0.2207f,-0.0516f,-0.1876f,-0.1677f,-1.0708f,0.5412f,-0.2594f,1.0621f,-0.1209f,0.1993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.9567f,0.2108f,0.2007f,-0.1156f,0.1706f,-0.1524f,0.9735f,0.5875f,0.2358f,0.9656f,0.1099f,-0.0938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.9381f,0.0373f,-0.3442f,0f,-0.3248f,0.2495f,0.9123f,0.5875f,0.1199f,0.9677f,-0.2219f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9381f,0.0373f,-0.3442f,0f,-0.3248f,0.2495f,0.9123f,0.5875f,0.1199f,0.9677f,-0.2219f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9967f,0.0059f,-0.0815f,0.0248f,-0.0757f,0.3077f,0.9484f,0.7534f,0.0307f,0.9514f,-0.3063f,0.5496f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6478f,0.0039f,0.053f,0.0258f,0.0492f,0.2f,-0.6165f,0.8023f,-0.02f,0.6184f,0.1991f,0.7009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9967f,0.0059f,-0.0815f,0.0248f,-0.0757f,0.3077f,0.9484f,0.7534f,0.0307f,0.9514f,-0.3063f,0.5496f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.1125f,-0.0146f,-0.9935f,-0.3038f,-0.0125f,0.9998f,-0.0161f,0.619f,0.9936f,0.0143f,0.1123f,0.5073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.1125f,-0.0146f,-0.9935f,-0.3005f,-0.0125f,0.9998f,-0.0161f,0.3878f,0.9936f,0.0143f,0.1123f,0.504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.1125f,-0.0146f,-0.9935f,-0.3f,-0.0125f,0.9998f,-0.0161f,0.3589f,0.9936f,0.0143f,0.1123f,0.5036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-1.1426f,-0.0168f,-0.1294f,-0.3099f,-0.0185f,1.1498f,0.0144f,1.0381f,0.1292f,0.0164f,-1.1426f,0.5133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.1125f,-0.0146f,-0.9935f,-0.3038f,-0.0125f,0.9998f,-0.0161f,0.619f,0.9936f,0.0143f,0.1123f,0.5073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.596f,-0.3166f,-0.7379f,0.347f,-0.3194f,-0.7497f,0.5796f,0.8444f,-0.7367f,0.5811f,0.3457f,0.4241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.596f,-0.7169f,-0.3617f,0.4087f,-0.3194f,-0.2017f,0.9259f,1.0336f,-0.7367f,0.6674f,-0.1087f,0.2922f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.596f,-0.7169f,-0.3617f,0.4294f,-0.3194f,-0.2017f,0.9259f,1.0394f,-0.7367f,0.6674f,-0.1087f,0.2729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0.8486f,-0.3641f,-0.6854f,0.2143f,-0.6666f,-0.8621f,-0.3673f,0.5302f,-0.3976f,0.6683f,-0.8472f,0.6677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.596f,-0.3166f,-0.7379f,0.347f,-0.3194f,-0.7497f,0.5796f,0.8444f,-0.7367f,0.5811f,0.3457f,0.4241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0789f,0.0429f,0.3959f,0.0308f,0.3735f,0.2869f,-1.0491f,0.793f,-0.1379f,1.1128f,0.2552f,0.7034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.032f,0.0411f,-0.3787f,0.0243f,-0.3573f,0.2744f,1.0035f,0.7497f,0.1319f,1.0644f,-0.2441f,0.5356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.5875,"pz":-0.09375,"ry":302.8063164786,"rx":65.8231023167}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args