# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle dust{color:[0.706,0.000,0.882],scale:1} ~ ~ ~ 5 5 5 0 100 force @a
function animated_java:projectiles/remove/this