# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data merge entity @s {width:3f,height:3f}
function animated_java:global/util/get_entity_stack_uuids