# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-0.9823f,-0.1708f,-0.0771f,0.0225f,-0.1874f,0.8878f,0.4204f,0.7057f,-0.0033f,0.4274f,-0.9041f,1.0738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-0.9823f,-0.1866f,0.0176f,0f,-0.1874f,0.9794f,-0.0747f,0.8307f,-0.0033f,-0.0767f,-0.997f,0.6879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,0.2187f,0f,0.9997f,-0.0261f,0.311f,0f,-0.0261f,-0.9997f,0.4953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,0.2187f,0f,0.9997f,-0.0261f,0.3998f,0f,-0.0261f,-0.9997f,0.3054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9997f,-0.0261f,0.311f,0f,-0.0261f,-0.9997f,0.4953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9997f,-0.0261f,0.3998f,0f,-0.0261f,-0.9997f,0.3054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0174f,0.8125f,0f,0.0174f,-0.9998f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.0167081275,"py":0.7362921278,"pz":1.0714095905,"ry":1.0129168746,"rx":-4.2845252008}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/idle_snarl/zzz/frames/26_locator_constant