# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-0.9872f,-0.149f,-0.056f,0.02f,-0.1592f,0.918f,0.3632f,0.7007f,-0.0027f,0.3675f,-0.93f,1.0721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-0.9872f,-0.1587f,0.0127f,0f,-0.1592f,0.9853f,-0.0621f,0.8314f,-0.0027f,-0.0633f,-0.998f,0.6879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,0.2187f,0f,0.9997f,-0.0247f,0.311f,0f,-0.0247f,-0.9997f,0.4955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,0.2187f,0f,0.9997f,-0.0247f,0.4001f,0f,-0.0247f,-0.9997f,0.3058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9997f,-0.0247f,0.311f,0f,-0.0247f,-0.9997f,0.4955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9997f,-0.0247f,0.4001f,0f,-0.0247f,-0.9997f,0.3058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0164f,0.8125f,0f,0.0164f,-0.9999f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.0150667997,"py":0.7315331844,"pz":1.0700732405,"ry":0.7300685767,"rx":-3.5594538522}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args