# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-0.9999f,-0.0146f,-0.0005f,0.0022f,-0.0147f,0.9989f,0.0451f,0.6766f,-0.0002f,0.0451f,-0.999f,1.0621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-0.9999f,-0.0147f,0.0001f,0f,-0.0147f,0.9999f,0.0049f,0.8346f,-0.0002f,0.0048f,-1f,0.6878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,0.2187f,0f,0.9998f,-0.0182f,0.3114f,0f,-0.0182f,-0.9998f,0.4967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,0.2187f,0f,0.9998f,-0.0182f,0.4017f,0f,-0.0182f,-0.9998f,0.3075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9998f,-0.0182f,0.3114f,0f,-0.0182f,-0.9998f,0.4967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9998f,-0.0182f,0.4017f,0f,-0.0182f,-0.9998f,0.3075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0121f,0.8125f,0f,0.0121f,-0.9999f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.0017899378,"py":0.7078331158,"pz":1.0622137613,"ry":0.0064473672,"rx":0.2779362063}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/idle_snarl/zzz/frames/35_locator_constant