# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0112f,0.6749f,0f,0.0112f,-0.9999f,1.061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0112f,0.8353f,0f,0.0112f,-0.9999f,0.6878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,0.2187f,0f,0.9999f,-0.0169f,0.3115f,0f,-0.0169f,-0.9999f,0.497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,0.2187f,0f,0.9999f,-0.0169f,0.4021f,0f,-0.0169f,-0.9999f,0.3079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9999f,-0.0169f,0.3115f,0f,-0.0169f,-0.9999f,0.497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,-0.2188f,0f,0.9999f,-0.0169f,0.4021f,0f,-0.0169f,-0.9999f,0.3079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0112f,0.8125f,0f,0.0112f,-0.9999f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0,"py":0.7061156716,"pz":1.0613756324,"ry":0,"rx":0.643776}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/idle_snarl/zzz/frames/36_locator_constant