# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:billy rig_hash set value 'f961b22a1bce6f5b134ef64cf4f58bf8d5881d6b18e36e548c6568136e19fe9d'
scoreboard objectives add aj.summon.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.idle_snarl.frame dummy
scoreboard objectives add aj.movement.frame dummy
scoreboard objectives add aj.maul.frame dummy
scoreboard objectives add aj.encourage.frame dummy
scoreboard objectives add aj.phase.frame dummy
scoreboard objectives add aj.snare_set.frame dummy
scoreboard objectives add aj.snare_trigger.frame dummy
scoreboard objectives add aj.withdraw.frame dummy