# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(blackhole_sun) {transformation: [0.1815f,0f,1.3075f,0f,0f,1.32f,0f,0.94f,-1.3075f,0f,0.1815f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"blackhole_sun_locator":{"px":0,"py":0.94,"pz":0,"ry":97.9029585799,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(blackhole_sun_locator) positioned ^0 ^0.94 ^0 rotated ~97.9029585799 ~0 run function animated_java:cassette/animations/blackhole_sun/zzz/frames/48_locator_blackhole_sun_locator