# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.8655f,-0.0745f,-0.4954f,0.1914f,-0.2921f,0.8784f,0.3783f,0.4064f,0.407f,0.4721f,-0.782f,-0.0997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0.952f,-0.0819f,0.5449f,0.1645f,0.3213f,0.9662f,-0.4161f,0.7238f,-0.4477f,0.5193f,0.8602f,0.0709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.0386f,-0.0894f,0.5945f,0.1654f,0.3505f,1.0541f,-0.4539f,0.7136f,-0.4884f,0.5665f,0.9384f,0.0654f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.8655f,-0.0745f,-0.4954f,0.1914f,-0.2921f,0.8784f,0.3783f,0.4064f,0.407f,0.4721f,-0.782f,-0.0997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.8655f,-0.2745f,-0.4191f,0.0962f,-0.2921f,0.9561f,-0.0229f,0.738f,0.407f,0.1026f,-0.9077f,-0.0642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0.952f,-0.3019f,0.461f,0.0129f,0.3213f,1.0517f,0.0252f,1.0282f,-0.4477f,0.1128f,0.9984f,-0.033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.8655f,-0.2745f,-0.4191f,0.0962f,-0.2921f,0.9561f,-0.0229f,0.738f,0.407f,0.1026f,-0.9077f,-0.0642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.986f,0.0584f,0.1564f,-0.1306f,0.0554f,0.9982f,-0.024f,0.4074f,-0.1575f,-0.015f,-0.9874f,0.1633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0846f,0.0643f,-0.1721f,-0.1095f,-0.0609f,1.098f,0.0264f,0.7681f,0.1733f,-0.0165f,1.0861f,0.1578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1832f,0.0701f,-0.1877f,-0.1101f,-0.0664f,1.1978f,0.0288f,0.7565f,0.189f,-0.018f,1.1849f,0.158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.986f,0.0584f,0.1564f,-0.1306f,0.0554f,0.9982f,-0.024f,0.4074f,-0.1575f,-0.015f,-0.9874f,0.1633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.986f,0.0992f,0.1343f,-0.0962f,0.0554f,0.9532f,-0.2973f,0.738f,-0.1575f,-0.2857f,-0.9453f,0.0642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0846f,0.1091f,-0.1478f,-0.0661f,-0.0609f,1.0485f,0.327f,1.0273f,0.1733f,-0.3142f,1.0398f,-0.0225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.986f,0.0992f,0.1343f,-0.0962f,0.0554f,0.9532f,-0.2973f,0.738f,-0.1575f,-0.2857f,-0.9453f,0.0642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.8254f,0.4344f,-0.3606f,0f,0.0495f,0.692f,0.7202f,0.738f,0.5624f,0.5765f,-0.5927f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.8254f,0.4344f,-0.3606f,0f,0.0495f,0.692f,0.7202f,0.738f,0.5624f,0.5765f,-0.5927f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.8841f,0.2021f,0.4214f,0.2888f,0.4423f,0.6531f,0.6147f,1.1981f,-0.151f,0.7298f,-0.6668f,0.3833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.5746f,0.1314f,-0.2739f,0.3209f,-0.2875f,0.4245f,-0.3995f,1.302f,0.0981f,0.4744f,0.4334f,0.4993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.8841f,0.2021f,0.4214f,0.2888f,0.4423f,0.6531f,0.6147f,1.1981f,-0.151f,0.7298f,-0.6668f,0.3833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7094f,0.3403f,-0.6172f,-0.0352f,0.1174f,0.9205f,0.3726f,1.1553f,0.695f,0.1919f,-0.6929f,0.5284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7094f,0.0117f,-0.7047f,-0.1234f,0.1174f,0.9878f,-0.1019f,0.9444f,0.695f,-0.155f,-0.7021f,0.474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7094f,0.0117f,-0.7047f,-0.1237f,0.1174f,0.9878f,-0.1019f,0.9158f,0.695f,-0.155f,-0.7021f,0.4785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.7098f,0.3914f,0.8158f,0.1075f,0.4285f,1.0586f,-0.135f,1.5411f,-0.7969f,0.2206f,-0.7992f,0.6088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7094f,0.3403f,-0.6172f,-0.0352f,0.1174f,0.9205f,0.3726f,1.1553f,0.695f,0.1919f,-0.6929f,0.5284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9403f,0.0708f,0.333f,0.5374f,0.1615f,0.9539f,0.2531f,1.1209f,-0.2997f,0.2917f,-0.9083f,0.1382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9403f,0.2048f,0.2719f,0.5249f,0.1615f,0.9716f,-0.1732f,0.9009f,-0.2997f,-0.119f,-0.9466f,0.0589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9403f,0.2048f,0.2719f,0.519f,0.1615f,0.9716f,-0.1732f,0.8728f,-0.2997f,-0.119f,-0.9466f,0.0623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.3829f,0.0814f,-1.0813f,0.5671f,-0.291f,1.097f,0.1857f,1.5208f,1.0446f,0.3355f,-0.3446f,0.2605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9403f,0.0708f,0.333f,0.5374f,0.1615f,0.9539f,0.2531f,1.1209f,-0.2997f,0.2917f,-0.9083f,0.1382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0.9492f,0.4995f,0.4147f,0.3578f,-0.057f,0.7959f,-0.8282f,1.3082f,-0.6467f,0.663f,0.6816f,0.475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.9079f,0.4778f,-0.3967f,0.2825f,0.0545f,0.7613f,0.7922f,1.1881f,0.6186f,0.6342f,-0.652f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.7380401235,"pz":0,"ry":328.6822777122,"rx":46.0669990825}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args