# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.8057f,-0.1323f,-0.5774f,0.2693f,-0.3634f,0.8801f,0.3054f,0.4346f,0.4678f,0.4559f,-0.7572f,0.003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0.8863f,-0.1455f,0.6351f,0.2215f,0.3998f,0.9681f,-0.336f,0.7526f,-0.5145f,0.5015f,0.8329f,0.1678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0.9668f,-0.1588f,0.6928f,0.223f,0.4361f,1.0562f,-0.3665f,0.7424f,-0.5613f,0.5471f,0.9086f,0.1625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.8057f,-0.1323f,-0.5774f,0.2693f,-0.3634f,0.8801f,0.3054f,0.4346f,0.4678f,0.4559f,-0.7572f,0.003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.8057f,-0.4876f,-0.3363f,0.1001f,-0.3634f,0.8553f,-0.3694f,0.7313f,0.4678f,-0.1754f,-0.8663f,-0.0578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0.8863f,-0.5364f,0.3699f,-0.0479f,0.3998f,0.9408f,0.4064f,0.9908f,-0.5145f,-0.193f,0.9529f,-0.1111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.8057f,-0.4876f,-0.3363f,0.1001f,-0.3634f,0.8553f,-0.3694f,0.7313f,0.4678f,-0.1754f,-0.8663f,-0.0578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.9655f,0.0919f,0.2436f,-0.1647f,0.0847f,0.9956f,-0.0397f,0.4241f,-0.2462f,-0.0177f,-0.9691f,0.2054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0621f,0.101f,-0.268f,-0.1315f,-0.0932f,1.0952f,0.0437f,0.7838f,0.2708f,-0.0195f,1.066f,0.199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1586f,0.1102f,-0.2923f,-0.1326f,-0.1016f,1.1947f,0.0477f,0.7723f,0.2954f,-0.0213f,1.1629f,0.1992f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.9655f,0.0919f,0.2436f,-0.1647f,0.0847f,0.9956f,-0.0397f,0.4241f,-0.2462f,-0.0177f,-0.9691f,0.2054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9655f,0.1862f,0.182f,-0.1001f,0.0847f,0.8856f,-0.4568f,0.7313f,-0.2462f,-0.4256f,-0.8708f,0.0578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0621f,0.2048f,-0.2002f,-0.0436f,-0.0932f,0.9741f,0.5024f,1f,0.2708f,-0.4682f,0.9579f,-0.0714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.9655f,0.1862f,0.182f,-0.1001f,0.0847f,0.8856f,-0.4568f,0.7313f,-0.2462f,-0.4256f,-0.8708f,0.0578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.9043f,0.4043f,-0.1375f,0f,0.0519f,0.4235f,0.9044f,0.7313f,0.4238f,0.8107f,-0.4039f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9043f,0.4043f,-0.1375f,0f,0.0519f,0.4235f,0.9044f,0.7313f,0.4238f,0.8107f,-0.4039f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9303f,0.0348f,0.3653f,0.2688f,0.3478f,0.4009f,0.8475f,1.0128f,-0.117f,0.9155f,-0.385f,0.539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6047f,0.0226f,-0.2374f,0.2743f,-0.2261f,0.2606f,-0.5509f,1.0766f,0.076f,0.5951f,0.2503f,0.6845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9303f,0.0348f,0.3653f,0.2688f,0.3478f,0.4009f,0.8475f,1.0128f,-0.117f,0.9155f,-0.385f,0.539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7733f,0.3693f,-0.5154f,-0.0799f,0.1074f,0.8774f,0.4676f,0.9941f,0.6249f,0.3063f,-0.7181f,0.6157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7733f,-0.1305f,-0.6205f,-0.1798f,0.1074f,0.9375f,-0.3309f,0.7929f,0.6249f,-0.3225f,-0.711f,0.5267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7733f,-0.1305f,-0.6205f,-0.176f,0.1074f,0.9375f,-0.3309f,0.7658f,0.6249f,-0.3225f,-0.711f,0.536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.5927f,0.4247f,0.8893f,0.0749f,0.5378f,1.009f,-0.1235f,1.3618f,-0.8258f,0.3522f,-0.7186f,0.7441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7733f,0.3693f,-0.5154f,-0.0799f,0.1074f,0.8774f,0.4676f,0.9941f,0.6249f,0.3063f,-0.7181f,0.6157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8689f,0.1653f,0.4665f,0.5474f,0.3339f,0.8915f,0.3061f,0.9581f,-0.3653f,0.4218f,-0.8299f,0.3217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.8689f,0.2624f,0.4196f,0.512f,0.3339f,0.9366f,0.1059f,0.7532f,-0.3653f,0.2322f,-0.9015f,0.2186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.8689f,0.2624f,0.4196f,0.5044f,0.3339f,0.9366f,0.1059f,0.7262f,-0.3653f,0.2322f,-0.9015f,0.2119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.5364f,0.1901f,-0.9993f,0.6167f,-0.3521f,1.0252f,0.384f,1.3318f,0.9543f,0.4851f,-0.42f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.8689f,0.1653f,0.4665f,0.5474f,0.3339f,0.8915f,0.3061f,0.9581f,-0.3653f,0.4218f,-0.8299f,0.3217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0399f,0.4649f,0.1581f,0.3331f,-0.0597f,0.487f,-1.0401f,1.0802f,-0.4874f,0.9323f,0.4645f,0.6679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-0.9947f,0.4447f,-0.1512f,0.2629f,0.0571f,0.4659f,0.9948f,1.0067f,0.4662f,0.8917f,-0.4443f,0.5273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.73125,"pz":0,"ry":341.2077524499,"rx":64.7426962625}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args