# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.3799f,0f,0f,-1f,0.1732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.1f,0f,0f,0.125f,0f,1.1f,0f,0.7705f,0f,0f,1.1f,0.1732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.2f,0f,0f,0.125f,0f,1.2f,0f,0.758f,0f,0f,1.2f,0.1732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.3799f,0f,0f,-1f,0.1732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.887f,-0.4617f,0.7125f,0f,-0.4617f,-0.887f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.1f,0f,0f,0.125f,0f,0.9757f,0.5079f,1.0036f,0f,-0.5079f,0.9757f,-0.1515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-1f,0f,0f,0.125f,0f,0.887f,-0.4617f,0.7125f,0f,-0.4617f,-0.887f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.8925f,0.3041f,-0.3331f,-0.239f,0.3466f,0.935f,-0.0752f,0.3619f,0.2886f,-0.1826f,-0.9399f,0.0685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0.9818f,0.3345f,0.3664f,-0.1202f,-0.3813f,1.0285f,0.0828f,0.7271f,-0.3174f,-0.2009f,1.0339f,-0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.071f,0.3649f,0.3997f,-0.124f,-0.4159f,1.122f,0.0903f,0.7154f,-0.3463f,-0.2191f,1.1279f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.8925f,0.3041f,-0.3331f,-0.239f,0.3466f,0.935f,-0.0752f,0.3619f,0.2886f,-0.1826f,-0.9399f,0.0685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.8925f,0.3041f,-0.3331f,-0.125f,0.3466f,0.935f,-0.0752f,0.7125f,0.2886f,-0.1826f,-0.9399f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0.9818f,0.3345f,0.3664f,-0.0252f,-0.3813f,1.0285f,0.0828f,1.0193f,-0.3174f,-0.2009f,1.0339f,-0.0599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.8925f,0.3041f,-0.3331f,-0.125f,0.3466f,0.935f,-0.0752f,0.7125f,0.2886f,-0.1826f,-0.9399f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.9657f,-0.007f,0.2596f,0f,0.2253f,0.4744f,0.851f,0.7125f,-0.1291f,0.8803f,-0.4565f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9657f,-0.007f,0.2596f,0f,0.2253f,0.4744f,0.851f,0.7125f,-0.1291f,0.8803f,-0.4565f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9904f,0.0213f,0.1363f,-0.0051f,0.0528f,0.9714f,0.2314f,1.0535f,-0.1274f,0.2364f,-0.9633f,0.6327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6438f,0.0139f,-0.0886f,-0.0014f,-0.0343f,0.6314f,-0.1504f,1.2204f,0.0828f,0.1537f,0.6261f,0.6733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9904f,0.0213f,0.1363f,-0.0051f,0.0528f,0.9714f,0.2314f,1.0535f,-0.1274f,0.2364f,-0.9633f,0.6327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.1844f,0.4498f,0.8739f,-0.3665f,0.6133f,-0.7474f,0.2553f,1.0935f,0.768f,0.4889f,-0.4137f,0.5017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.1844f,0.6982f,-0.6918f,-0.4712f,0.6133f,0.4683f,0.636f,1.3183f,0.768f,-0.5416f,-0.3419f,0.3473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.1844f,0.6982f,-0.6918f,-0.493f,0.6133f,0.4683f,0.636f,1.3037f,0.768f,-0.5416f,-0.3419f,0.3642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [1.005f,0.5173f,-0.212f,-0.1627f,0.2936f,-0.8595f,-0.7053f,0.7548f,-0.4757f,0.5622f,-0.8832f,0.7233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.1844f,0.4498f,0.8739f,-0.3665f,0.6133f,-0.7474f,0.2553f,1.0935f,0.768f,0.4889f,-0.4137f,0.5017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.529f,-0.5635f,0.6345f,0.3577f,-0.1913f,0.8077f,0.5577f,0.9245f,-0.8268f,0.1736f,-0.5351f,0.5986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.529f,0.5555f,0.6415f,0.5336f,-0.1913f,0.6584f,-0.728f,0.7179f,-0.8268f,-0.5078f,-0.242f,0.5339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.529f,0.5555f,0.6415f,0.5162f,-0.1913f,0.6584f,-0.728f,0.6974f,-0.8268f,-0.5078f,-0.242f,0.5498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.7297f,-0.648f,-0.6084f,0.1024f,-0.6414f,0.9288f,-0.22f,1.2905f,0.6153f,0.1997f,-0.9508f,0.6773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.529f,-0.5635f,0.6345f,0.3577f,-0.1913f,0.8077f,0.5577f,0.9245f,-0.8268f,0.1736f,-0.5351f,0.5986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1105f,-0.0081f,-0.2985f,-0.0063f,-0.2591f,0.5456f,-0.9786f,1.135f,0.1485f,1.0123f,0.525f,0.784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0623f,-0.0077f,0.2856f,-0.0049f,0.2478f,0.5218f,0.9361f,1.0461f,-0.1421f,0.9683f,-0.5022f,0.6189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.7125,"pz":0,"ry":29.62347057,"rx":58.3189675296}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args