# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/black_flash_assault/zzz/frames/39_locator_commands
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/black_flash_assault/zzz/frames/39_locator_constant
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/black_flash_assault/zzz/frames/39_locator_skins
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/black_flash_assault/zzz/frames/39_locator_sfx
$execute as $(mount) positioned ^0 ^0.7125 ^0 rotated ~29.62347057 ~58.3189675296 run function aj:yuji/animations/black_flash_assault/zzz/frames/39_locator_mount