# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:cutscenes/root/zzz/2 with entity @s data.locators.head
function animated_java:cutscenes/root/zzz/4 with entity @s data.locators.heart
function animated_java:cutscenes/root/zzz/6 with entity @s data.locators.mount
function animated_java:cutscenes/root/zzz/8 with entity @s data.locators.body
function animated_java:cutscenes/root/zzz/10 with entity @s data.locators.mount2
function animated_java:cutscenes/root/zzz/12 with entity @s data.locators.locator