# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(yuji_waist) {transformation: [-0.9899f,0f,-0.1416f,0f,0f,1f,0f,0.6875f,0.1416f,0f,-0.9899f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist_group) {transformation: [-0.9899f,0f,-0.1416f,0f,0f,1f,0f,0.6875f,0.1416f,0f,-0.9899f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head) {transformation: [-0.8809f,0.1281f,-0.4557f,0f,0.1404f,0.9901f,0.007f,1.3523f,0.452f,-0.0578f,-0.8901f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_helmet) {transformation: [0.5726f,0.0833f,0.2962f,0.0204f,-0.0913f,0.6435f,-0.0045f,1.5097f,-0.2938f,-0.0376f,0.5786f,-0.0092f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head_group) {transformation: [-0.8809f,0.1281f,-0.4557f,0f,0.1404f,0.9901f,0.007f,1.3523f,0.452f,-0.0578f,-0.8901f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm) {transformation: [-0.9899f,0f,-0.1416f,-0.3434f,0f,1f,0f,1.2656f,0.1416f,0f,-0.9899f,0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm) {transformation: [-0.9899f,0f,-0.1416f,-0.3434f,0f,1f,0f,1.0344f,0.1416f,0f,-0.9899f,0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm_group) {transformation: [-0.9899f,0f,-0.1416f,-0.3434f,0f,1f,0f,1.0055f,0.1416f,0f,-0.9899f,0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_r) {transformation: [-0.1629f,0f,1.1384f,-0.3434f,0f,1.15f,0f,1.6848f,-1.1384f,0f,-0.1629f,0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm_group) {transformation: [-0.9899f,0f,-0.1416f,-0.3434f,0f,1f,0f,1.2656f,0.1416f,0f,-0.9899f,0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm) {transformation: [-0.7338f,-0.5527f,-0.395f,0.3434f,-0.1873f,0.7235f,-0.6644f,1.2656f,0.653f,-0.4136f,-0.6345f,-0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm) {transformation: [-0.7338f,-0.5738f,0.3637f,0.4706f,-0.1873f,-0.3438f,-0.9202f,1.0675f,0.653f,-0.7434f,0.1448f,0.037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm_group) {transformation: [-0.7338f,-0.5738f,0.3637f,0.4872f,-0.1873f,-0.3438f,-0.9202f,1.0774f,0.653f,-0.7434f,0.1448f,0.0585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_l) {transformation: [0.4542f,-0.6356f,-0.8439f,0.1117f,0.7641f,0.8321f,-0.2154f,1.5689f,0.7296f,-0.4756f,0.7509f,-0.2225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm_group) {transformation: [-0.7338f,-0.5527f,-0.395f,0.3434f,-0.1873f,0.7235f,-0.6644f,1.2656f,0.653f,-0.4136f,-0.6345f,-0.0491f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_body) {transformation: [1.1384f,0f,0.1629f,0f,0f,1.15f,0f,1.5113f,-0.1629f,0f,1.1384f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_pants) {transformation: [-1.0889f,0f,-0.1558f,0f,0f,1.1f,0f,1.3379f,0.1558f,0f,-1.0889f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"yuji_mount":{"px":0,"py":0.6875,"pz":0,"ry":351.85875,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/king_of_curses/zzz/frames/12_locator_constant