# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-0.9888f,0f,0.1492f,0f,0f,1f,0f,0.75f,-0.1492f,0f,-0.9888f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9888f,0f,0.1492f,0f,0f,1f,0f,0.75f,-0.1492f,0f,-0.9888f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.868f,-0.1347f,0.4779f,0f,-0.147f,0.9891f,0.0117f,1.4688f,-0.4743f,-0.0601f,-0.8783f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.5642f,-0.0875f,-0.3106f,-0.0231f,0.0956f,0.6429f,-0.0076f,1.6387f,0.3083f,-0.039f,0.5709f,-0.0103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.868f,-0.1347f,0.4779f,0f,-0.147f,0.9891f,0.0117f,1.4688f,-0.4743f,-0.0601f,-0.8783f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7148f,0.5776f,0.3943f,-0.3708f,0.191f,0.7036f,-0.6844f,1.375f,-0.6727f,-0.4139f,-0.6133f,-0.0559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7148f,0.5666f,-0.4099f,-0.5155f,0.191f,-0.4056f,-0.8939f,1.1644f,-0.6727f,-0.7173f,0.1817f,0.038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7148f,0.5666f,-0.4099f,-0.5332f,0.191f,-0.4056f,-0.8939f,1.1771f,-0.6727f,-0.7173f,0.1817f,0.0605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0.4534f,0.6642f,0.822f,-0.1091f,-0.7871f,0.8092f,-0.2197f,1.6938f,-0.7053f,-0.476f,0.7736f,-0.2435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7148f,0.5776f,0.3943f,-0.3708f,0.191f,0.7036f,-0.6844f,1.375f,-0.6727f,-0.4139f,-0.6133f,-0.0559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9888f,0f,0.1492f,0.3708f,0f,1f,0f,1.375f,-0.1492f,0f,-0.9888f,0.0559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9888f,0f,0.1492f,0.3708f,0f,1f,0f,1.125f,-0.1492f,0f,-0.9888f,0.0559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.9888f,0f,0.1492f,0.3708f,0f,1f,0f,1.0938f,-0.1492f,0f,-0.9888f,0.0559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.1716f,0f,-1.1371f,0.3708f,0f,1.15f,0f,1.8281f,1.1371f,0f,-0.1716f,0.0559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.9888f,0f,0.1492f,0.3708f,0f,1f,0f,1.375f,-0.1492f,0f,-0.9888f,0.0559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.1371f,0f,-0.1716f,0f,0f,1.15f,0f,1.6406f,0.1716f,0f,1.1371f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0877f,0f,0.1641f,0f,0f,1.1f,0f,1.4531f,-0.1641f,0f,-1.0877f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":8.58,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/king_of_curses/zzz/frames/20_locator_constant