# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cinematics.root] run return 0
execute on passengers if entity @s[tag=aj.cinematics.data] unless data entity @s {data:{rigHash: 'd5da6447329cc810cd2006483b68f042ed5a3e95ed0003e367d7c7b136db0145'}} on vehicle run function animated_java:cinematics/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1