# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_danger) {transformation: [-12f,0f,0f,0f,0f,1f,0f,0.0313f,0f,0f,-12f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_exclamation) {transformation: [-6f,0f,0f,0f,0f,6f,0f,1.6875f,0f,0f,-6f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"commands":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}