# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage minecraft:custom yuji.moves.id int 1 run scoreboard players get @s customUniversal_RigID
function custom:items/yuji/moves/7/main with storage minecraft:custom yuji.moves