# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.8118f,0f,-0.584f,0.1013f,0f,1f,0f,0.3469f,0.584f,0f,-0.8118f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0.893f,0f,0.6424f,0.1013f,0f,1.1f,0f,0.7082f,-0.6424f,0f,0.893f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0.9741f,0f,0.7008f,0.1013f,0f,1.2f,0f,0.6966f,-0.7008f,0f,0.9741f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.8118f,0f,-0.584f,0.1013f,0f,1f,0f,0.3469f,0.584f,0f,-0.8118f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.8118f,0f,-0.584f,0.1013f,0f,1f,0f,0.6938f,0.584f,0f,-0.8118f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0.893f,0f,0.6424f,0.1013f,0f,1.1f,0f,0.9973f,-0.6424f,0f,0.893f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.8118f,0f,-0.584f,0.1013f,0f,1f,0f,0.6938f,0.584f,0f,-0.8118f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9784f,0.0754f,-0.1927f,-0.0864f,0.0602f,0.9947f,0.0833f,0.6938f,0.198f,0.0699f,-0.9777f,0.1226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.9784f,0.0754f,-0.1927f,-0.1126f,0.0602f,0.9947f,0.0833f,0.3487f,0.198f,0.0699f,-0.9777f,0.0984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0762f,0.0829f,0.212f,-0.0853f,-0.0662f,1.0942f,-0.0916f,0.7081f,-0.2178f,0.0769f,1.0755f,0.1236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.174f,0.0904f,0.2313f,-0.0862f,-0.0723f,1.1936f,-0.1f,0.6966f,-0.2376f,0.0839f,1.1733f,0.1228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.9784f,0.0754f,-0.1927f,-0.1126f,0.0602f,0.9947f,0.0833f,0.3487f,0.198f,0.0699f,-0.9777f,0.0984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0762f,0.0829f,0.212f,-0.0636f,-0.0662f,1.0942f,-0.0916f,0.9957f,-0.2178f,0.0769f,1.0755f,0.1438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.9784f,0.0754f,-0.1927f,-0.0864f,0.0602f,0.9947f,0.0833f,0.6938f,0.198f,0.0699f,-0.9777f,0.1226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.9564f,-0.0416f,-0.289f,0.0074f,-0.0367f,0.9991f,-0.0222f,0.6938f,0.2897f,-0.0106f,-0.9571f,0.0551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9564f,-0.0416f,-0.289f,0.0074f,-0.0367f,0.9991f,-0.0222f,0.6938f,0.2897f,-0.0106f,-0.9571f,0.0551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9442f,0.0388f,0.3271f,-0.0202f,-0.1299f,0.8687f,-0.4781f,1.358f,-0.3027f,-0.4939f,-0.8151f,0.0481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.6137f,0.0252f,-0.2126f,-0.014f,0.0844f,0.5646f,0.3107f,1.4961f,0.1968f,-0.321f,0.5298f,-0.0305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9442f,0.0388f,0.3271f,-0.0202f,-0.1299f,0.8687f,-0.4781f,1.358f,-0.3027f,-0.4939f,-0.8151f,0.0481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.1953f,0.8448f,-0.4981f,-0.3484f,0.9755f,-0.2196f,0.01f,1.2586f,-0.1009f,-0.4879f,-0.867f,0.1495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.1953f,0.8579f,-0.4753f,-0.5434f,0.9755f,-0.2198f,0.0041f,1.3094f,-0.1009f,-0.4645f,-0.8798f,0.263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.7625f,0f,0f,0f,1.3876f,0f,0f,0f,0.3808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.767f,0f,0f,0f,1.3651f,0f,0f,0f,0.3831f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.7715f,0f,0f,0f,1.3425f,0f,0f,0f,0.3855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.1953f,0.8579f,-0.4753f,-0.5681f,0.9755f,-0.2198f,0.0041f,1.3157f,-0.1009f,-0.4645f,-0.8798f,0.2764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.5729f,0.9715f,-0.2246f,0.0057f,0.0115f,-0.2525f,-1.1219f,1.1666f,-0.9971f,-0.5611f,0.116f,-0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.1953f,0.8448f,-0.4981f,-0.3484f,0.9755f,-0.2196f,0.01f,1.2586f,-0.1009f,-0.4879f,-0.867f,0.1495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.7529f,-0.3746f,0.5411f,0.3151f,-0.6404f,0.2274f,-0.7336f,1.2841f,0.1517f,-0.8989f,-0.4111f,-0.0515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.7529f,-0.2502f,0.6087f,0.4054f,-0.6404f,0.0653f,-0.7653f,1.2268f,0.1517f,-0.966f,-0.2094f,0.1544f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.472f,0f,0f,0f,1.2101f,0f,0f,0f,0.4051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.7529f,-0.2502f,0.6087f,0.4126f,-0.6404f,0.0653f,-0.7653f,1.2249f,0.1517f,-0.966f,-0.2094f,0.1823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.6223f,-0.4308f,-0.8659f,0.1581f,0.8437f,0.2615f,-0.7364f,1.3794f,0.4728f,-1.0337f,0.1745f,-0.4283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.7529f,-0.3746f,0.5411f,0.3151f,-0.6404f,0.2274f,-0.7336f,1.2841f,0.1517f,-0.8989f,-0.4111f,-0.0515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0999f,-0.0478f,0.3324f,-0.0268f,0.0422f,1.1489f,0.0255f,1.5168f,-0.3331f,-0.0122f,1.1006f,0.0464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0521f,-0.0457f,-0.3179f,-0.0196f,-0.0404f,1.099f,-0.0244f,1.3435f,0.3187f,-0.0117f,-1.0528f,0.0482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.1520297051,"py":1.3337493952,"pz":-0.184607989,"ry":343.1955424757,"rx":-1.2709123155}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/default_knife_throw/zzz/frames/16_locator_constant