# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-0.7934f,0f,-0.6088f,0.1027f,0f,1f,0f,0.3469f,0.6088f,0f,-0.7934f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0.8727f,0f,0.6696f,0.1027f,0f,1.1f,0f,0.7082f,-0.6696f,0f,0.8727f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0.952f,0f,0.7305f,0.1027f,0f,1.2f,0f,0.6966f,-0.7305f,0f,0.952f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-0.7934f,0f,-0.6088f,0.1027f,0f,1f,0f,0.3469f,0.6088f,0f,-0.7934f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.7934f,0f,-0.6088f,0.1027f,0f,1f,0f,0.6938f,0.6088f,0f,-0.7934f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0.8727f,0f,0.6696f,0.1027f,0f,1.1f,0f,0.9973f,-0.6696f,0f,0.8727f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-0.7934f,0f,-0.6088f,0.1027f,0f,1f,0f,0.6938f,0.6088f,0f,-0.7934f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.971f,0.0776f,-0.2263f,-0.0808f,0.0637f,0.9957f,0.0678f,0.6938f,0.2306f,0.0514f,-0.9717f,0.1282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-0.971f,0.0776f,-0.2263f,-0.1077f,0.0637f,0.9957f,0.0678f,0.3484f,0.2306f,0.0514f,-0.9717f,0.1104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.0681f,0.0853f,0.249f,-0.0797f,-0.0701f,1.0952f,-0.0746f,0.7081f,-0.2537f,0.0565f,1.0689f,0.1289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.1651f,0.0931f,0.2716f,-0.0806f,-0.0765f,1.1948f,-0.0814f,0.6966f,-0.2767f,0.0617f,1.166f,0.1283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-0.971f,0.0776f,-0.2263f,-0.1077f,0.0637f,0.9957f,0.0678f,0.3484f,0.2306f,0.0514f,-0.9717f,0.1104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.0681f,0.0853f,0.249f,-0.0573f,-0.0701f,1.0952f,-0.0746f,0.9959f,-0.2537f,0.0565f,1.0689f,0.1438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-0.971f,0.0776f,-0.2263f,-0.0808f,0.0637f,0.9957f,0.0678f,0.6938f,0.2306f,0.0514f,-0.9717f,0.1282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-0.9351f,-0.0339f,-0.3528f,0.0109f,-0.0342f,0.9994f,-0.0053f,0.6938f,0.3528f,0.0071f,-0.9357f,0.0578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-0.9351f,-0.0339f,-0.3528f,0.0109f,-0.0342f,0.9994f,-0.0053f,0.6938f,0.3528f,0.0071f,-0.9357f,0.0578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9508f,-0.0131f,0.3095f,-0.0116f,-0.1651f,0.8667f,-0.4706f,1.3582f,-0.2621f,-0.4986f,-0.8263f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.618f,-0.0085f,-0.2012f,-0.0137f,0.1073f,0.5634f,0.3059f,1.496f,0.1704f,-0.3241f,0.5371f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-0.9508f,-0.0131f,0.3095f,-0.0116f,-0.1651f,0.8667f,-0.4706f,1.3582f,-0.2621f,-0.4986f,-0.8263f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.162f,0.8027f,-0.574f,-0.333f,0.9838f,-0.1767f,0.0305f,1.2597f,-0.077f,-0.5696f,-0.8183f,0.1843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0.162f,0.8027f,-0.574f,-0.5186f,0.9838f,-0.1767f,0.0305f,1.3005f,-0.077f,-0.5696f,-0.8183f,0.316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.7242f,0f,0f,0f,1.3678f,0f,0f,0f,0.4617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.7279f,0f,0f,0f,1.3451f,0f,0f,0f,0.4635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.7317f,0f,0f,0f,1.3223f,0f,0f,0f,0.4653f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [0.162f,0.8027f,-0.574f,-0.5418f,0.9838f,-0.1767f,0.0305f,1.3056f,-0.077f,-0.5696f,-0.8183f,0.3325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.6601f,0.9231f,-0.1863f,0.0034f,0.0351f,-0.2032f,-1.1314f,1.1856f,-0.941f,-0.6551f,0.0885f,-0.0545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [0.162f,0.8027f,-0.574f,-0.333f,0.9838f,-0.1767f,0.0305f,1.2597f,-0.077f,-0.5696f,-0.8183f,0.1843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8076f,-0.3232f,-0.4933f,0.3157f,-0.4974f,0.8227f,0.2753f,1.2834f,0.3169f,0.4677f,-0.8252f,-0.0605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.8076f,-0.4223f,-0.4117f,0.3876f,-0.4974f,0.8628f,0.0907f,1.0943f,0.3169f,0.278f,-0.9068f,-0.1741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.4982f,0f,0f,0f,0.8708f,0f,0f,0f,-0.2475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.8076f,-0.4223f,-0.4117f,0.3998f,-0.4974f,0.8628f,0.0907f,1.0694f,0.3169f,0.278f,-0.9068f,-0.1821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0.5673f,-0.3717f,-0.9287f,0.1802f,-0.3165f,0.9461f,-0.572f,1.6282f,0.9489f,0.5378f,0.3644f,0.1355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.8076f,-0.3232f,-0.4933f,0.3157f,-0.4974f,0.8227f,0.2753f,1.2834f,0.3169f,0.4677f,-0.8252f,-0.0605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.0753f,-0.0389f,0.4058f,-0.017f,0.0393f,1.1493f,0.0061f,1.5171f,-0.4057f,0.0082f,1.076f,0.0637f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.0286f,-0.0373f,-0.3881f,-0.0111f,-0.0376f,1.0993f,-0.0058f,1.3438f,0.3881f,0.0078f,-1.0292f,0.0624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.1444421249,"py":1.3362907465,"pz":-0.1815440062,"ry":339.3389680759,"rx":-0.3046554674}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/default_knife_throw/zzz/frames/24_locator_constant