# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9999f,-0.0126f,0.375f,0f,-0.0126f,-0.9999f,-0.0035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.1f,0f,0f,0.125f,0f,1.0999f,0.0138f,0.7656f,0f,-0.0138f,1.0999f,-0.0084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.2f,0f,0f,0.125f,0f,1.1999f,0.0151f,0.7531f,0f,-0.0151f,1.1999f,-0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-1f,0f,0f,0.125f,0f,0.9999f,-0.0126f,0.375f,0f,-0.0126f,-0.9999f,-0.0035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0094f,0.75f,0f,0.0094f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.1f,0f,0f,0.125f,0f,1.1f,-0.0104f,1.0781f,0f,0.0104f,1.1f,0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0094f,0.75f,0f,0.0094f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,-0.0063f,0.375f,0f,-0.0063f,-1f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.1f,0f,0f,-0.125f,0f,1.1f,0.0069f,0.7657f,0f,-0.0069f,1.1f,-0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.2f,0f,0f,-0.125f,0f,1.2f,0.0075f,0.7532f,0f,-0.0075f,1.2f,-0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-1f,0f,0f,-0.125f,0f,1f,-0.0063f,0.375f,0f,-0.0063f,-1f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9999f,0.0157f,0.75f,0f,0.0157f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.1f,0f,0f,-0.125f,0f,1.0999f,-0.0173f,1.0781f,0f,0.0173f,1.0999f,0.0052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-1f,0f,0f,-0.125f,0f,0.9999f,0.0157f,0.75f,0f,0.0157f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-1f,-0.0006f,0.0064f,0f,-0.0007f,0.9998f,-0.0188f,0.75f,-0.0064f,-0.0188f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,-0.0006f,0.0064f,0f,-0.0007f,0.9998f,-0.0188f,0.75f,-0.0064f,-0.0188f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,-0.0006f,0.0061f,-0.0004f,0.0013f,0.9509f,0.3096f,1.4686f,-0.006f,0.3096f,-0.9509f,-0.0135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,-0.0004f,-0.004f,-0.0005f,-0.0009f,0.6181f,-0.2012f,1.6321f,0.0039f,0.2012f,0.6181f,0.0397f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,-0.0006f,0.0061f,-0.0004f,0.0013f,0.9509f,0.3096f,1.4686f,-0.006f,0.3096f,-0.9509f,-0.0135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7202f,-0.571f,-0.3941f,-0.3753f,0.1591f,0.417f,-0.8949f,1.3746f,0.6753f,-0.7072f,-0.2095f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7202f,-0.5678f,0.3986f,-0.2325f,0.1591f,-0.6944f,-0.7018f,1.2357f,0.6753f,-0.442f,0.5905f,0.171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7202f,-0.5678f,0.3986f,-0.2148f,0.1591f,-0.6944f,-0.7018f,1.2574f,0.6753f,-0.442f,0.5905f,0.1848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.4532f,-0.6566f,0.8283f,-0.6341f,-1.0291f,0.4795f,-0.1829f,1.5636f,-0.2409f,-0.8133f,-0.7765f,-0.3346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7202f,-0.571f,-0.3941f,-0.3753f,0.1591f,0.417f,-0.8949f,1.3746f,0.6753f,-0.7072f,-0.2095f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.7119f,0.5836f,0.3906f,0.3746f,-0.1555f,0.4114f,-0.8981f,1.3751f,-0.6848f,-0.7001f,-0.2021f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.7119f,0.569f,-0.4117f,0.2283f,-0.1555f,-0.6993f,-0.6977f,1.2376f,-0.6848f,-0.4327f,0.5864f,0.174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.7119f,0.569f,-0.4117f,0.2105f,-0.1555f,-0.6993f,-0.6977f,1.2594f,-0.6848f,-0.4327f,0.5864f,0.1876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.4492f,0.6712f,-0.8187f,0.6391f,1.0328f,0.4731f,-0.1788f,1.5616f,0.2324f,-0.8051f,-0.7876f,-0.3266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.7119f,0.5836f,0.3906f,0.3746f,-0.1555f,0.4114f,-0.8981f,1.3751f,-0.6848f,-0.7001f,-0.2021f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,-0.0006f,-0.0073f,-0.0005f,0.0008f,1.1498f,0.0216f,1.6405f,0.0073f,-0.0216f,1.1498f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,-0.0006f,0.007f,-0.0004f,-0.0008f,1.0998f,-0.0206f,1.453f,-0.007f,-0.0207f,-1.0998f,-0.0132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":0.3649792983,"rx":-1.0754735251}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/domain_expansion/zzz/frames/40_locator_commands