# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lower_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9999f,-0.0119f,0.375f,0f,-0.0119f,-0.9999f,-0.0033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [1.1f,0f,0f,0.125f,0f,1.0999f,0.0131f,0.7656f,0f,-0.0131f,1.0999f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [1.2f,0f,0f,0.125f,0f,1.1999f,0.0143f,0.7531f,0f,-0.0143f,1.1999f,-0.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg_group) {transformation: [-1f,0f,0f,0.125f,0f,0.9999f,-0.0119f,0.375f,0f,-0.0119f,-0.9999f,-0.0033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0089f,0.75f,0f,0.0089f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [1.1f,0f,0f,0.125f,0f,1.1f,-0.0098f,1.0781f,0f,0.0098f,1.1f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg_group) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0089f,0.75f,0f,0.0089f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,-0.0059f,0.375f,0f,-0.0059f,-1f,-0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [1.1f,0f,0f,-0.125f,0f,1.1f,0.0065f,0.7657f,0f,-0.0065f,1.1f,-0.0079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [1.2f,0f,0f,-0.125f,0f,1.2f,0.0071f,0.7532f,0f,-0.0071f,1.2f,-0.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg_group) {transformation: [-1f,0f,0f,-0.125f,0f,1f,-0.0059f,0.375f,0f,-0.0059f,-1f,-0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9999f,0.0148f,0.75f,0f,0.0148f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [1.1f,0f,0f,-0.125f,0f,1.0999f,-0.0163f,1.0781f,0f,0.0163f,1.0999f,0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg_group) {transformation: [-1f,0f,0f,-0.125f,0f,0.9999f,0.0148f,0.75f,0f,0.0148f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [-1f,-0.0005f,0.006f,0f,-0.0006f,0.9998f,-0.0177f,0.75f,-0.006f,-0.0177f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,-0.0005f,0.006f,0f,-0.0006f,0.9998f,-0.0177f,0.75f,-0.006f,-0.0177f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,-0.0006f,0.0058f,-0.0004f,0.0013f,0.9503f,0.3113f,1.4686f,-0.0057f,0.3113f,-0.9503f,-0.0128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,-0.0004f,-0.0038f,-0.0005f,-0.0008f,0.6177f,-0.2024f,1.632f,0.0037f,0.2024f,0.6177f,0.0408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,-0.0006f,0.0058f,-0.0004f,0.0013f,0.9503f,0.3113f,1.4686f,-0.0057f,0.3113f,-0.9503f,-0.0128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7219f,-0.5678f,-0.3955f,-0.3753f,0.1582f,0.421f,-0.8932f,1.3747f,0.6736f,-0.7074f,-0.2141f,-0.0133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7219f,-0.5698f,0.3926f,-0.2334f,0.1582f,-0.6882f,-0.708f,1.2347f,0.6736f,-0.449f,0.587f,0.1716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7219f,-0.5698f,0.3926f,-0.2156f,0.1582f,-0.6882f,-0.708f,1.2563f,0.6736f,-0.449f,0.587f,0.1856f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.4548f,-0.653f,0.8302f,-0.6326f,-1.0271f,0.4842f,-0.1819f,1.5654f,-0.2462f,-0.8135f,-0.7747f,-0.3339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7219f,-0.5678f,-0.3955f,-0.3753f,0.1582f,0.421f,-0.8932f,1.3747f,0.6736f,-0.7074f,-0.2141f,-0.0133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.7141f,0.5798f,0.3923f,0.3747f,-0.1548f,0.4157f,-0.8962f,1.3751f,-0.6827f,-0.7007f,-0.2071f,-0.0088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.7141f,0.5711f,-0.4049f,0.2294f,-0.1548f,-0.6929f,-0.7042f,1.2366f,-0.6827f,-0.4402f,0.5832f,0.1745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.7141f,0.5711f,-0.4049f,0.2116f,-0.1548f,-0.6929f,-0.7042f,1.2582f,-0.6827f,-0.4402f,0.5832f,0.1882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.4512f,0.6668f,-0.8212f,0.6374f,1.0306f,0.4781f,-0.1781f,1.5635f,0.2382f,-0.8058f,-0.7851f,-0.3263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.7141f,0.5798f,0.3923f,0.3747f,-0.1548f,0.4157f,-0.8962f,1.3751f,-0.6827f,-0.7007f,-0.2071f,-0.0088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,-0.0006f,-0.0069f,-0.0005f,0.0007f,1.1498f,0.0204f,1.6405f,0.0069f,-0.0204f,1.1498f,-0.0158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,-0.0006f,0.0066f,-0.0004f,-0.0007f,1.0998f,-0.0195f,1.453f,-0.0066f,-0.0195f,-1.0998f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mount":{"px":0,"py":0.75,"pz":0,"ry":0.3449815408,"rx":-1.0166714418}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/domain_expansion/zzz/frames/41_locator_commands