# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(yuji_lower_left_leg) {transformation: [-1f,0f,0f,0.1156f,0f,1f,-0.0069f,0.3406f,0f,-0.0069f,-1f,-0.0018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_r) {transformation: [1.1f,0f,0f,0.1156f,0f,1.1f,0.0076f,0.7019f,0f,-0.0076f,1.1f,-0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_r) {transformation: [1.2f,0f,0f,0.1156f,0f,1.2f,0.0083f,0.6904f,0f,-0.0083f,1.2f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_left_leg_group) {transformation: [-1f,0f,0f,0.1156f,0f,1f,-0.0069f,0.3406f,0f,-0.0069f,-1f,-0.0018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg) {transformation: [-1f,0f,0f,0.1156f,0f,1f,0.0052f,0.6875f,0f,0.0052f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_r) {transformation: [1.1f,0f,0f,0.1156f,0f,1.1f,-0.0057f,0.991f,0f,0.0057f,1.1f,0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg_group) {transformation: [-1f,0f,0f,0.1156f,0f,1f,0.0052f,0.6875f,0f,0.0052f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,-0.0035f,0.3406f,0f,-0.0035f,-1f,-0.003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_l) {transformation: [1.1f,0f,0f,-0.1156f,0f,1.1f,0.0038f,0.702f,0f,-0.0038f,1.1f,-0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_l) {transformation: [1.2f,0f,0f,-0.1156f,0f,1.2f,0.0042f,0.6904f,0f,-0.0042f,1.2f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg_group) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,-0.0035f,0.3406f,0f,-0.0035f,-1f,-0.003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,0.0087f,0.6875f,0f,0.0087f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_l) {transformation: [1.1f,0f,0f,-0.1156f,0f,1.1f,-0.0096f,0.991f,0f,0.0096f,1.1f,0.0026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg_group) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,0.0087f,0.6875f,0f,0.0087f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist) {transformation: [-1f,-0.0003f,0.0035f,0f,-0.0004f,0.9999f,-0.0104f,0.6875f,-0.0035f,-0.0104f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist_group) {transformation: [-1f,-0.0003f,0.0035f,0f,-0.0004f,0.9999f,-0.0104f,0.6875f,-0.0035f,-0.0104f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head) {transformation: [-1f,-0.0004f,0.0034f,-0.0002f,0.0007f,0.946f,0.3241f,1.3523f,-0.0033f,0.3241f,-0.946f,-0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_helmet) {transformation: [0.65f,-0.0002f,-0.0022f,-0.0003f,-0.0005f,0.6149f,-0.2107f,1.5027f,0.0021f,0.2107f,0.6149f,0.0446f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head_group) {transformation: [-1f,-0.0004f,0.0034f,-0.0002f,0.0007f,0.946f,0.3241f,1.3523f,-0.0033f,0.3241f,-0.946f,-0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm) {transformation: [-0.734f,-0.5449f,-0.4054f,-0.3471f,0.152f,0.4499f,-0.88f,1.2655f,0.6619f,-0.7076f,-0.2474f,-0.0072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm) {transformation: [-0.734f,-0.5825f,0.3492f,-0.2221f,0.152f,-0.642f,-0.7514f,1.1299f,0.6619f,-0.4985f,0.5598f,0.1625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm_group) {transformation: [-0.734f,-0.5825f,0.3492f,-0.2053f,0.152f,-0.642f,-0.7514f,1.1484f,0.6619f,-0.4985f,0.5598f,0.1769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_r) {transformation: [-0.4662f,-0.6266f,0.8441f,-0.5755f,-1.0121f,0.5174f,-0.1748f,1.454f,-0.2845f,-0.8137f,-0.7612f,-0.3038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm_group) {transformation: [-0.734f,-0.5449f,-0.4054f,-0.3471f,0.152f,0.4499f,-0.88f,1.2655f,0.6619f,-0.7076f,-0.2474f,-0.0072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm) {transformation: [-0.7295f,0.552f,0.4038f,0.3467f,-0.15f,0.4469f,-0.8819f,1.2657f,-0.6673f,-0.7039f,-0.2432f,-0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm) {transformation: [-0.7295f,0.5838f,-0.3564f,0.2199f,-0.15f,-0.6449f,-0.7494f,1.1308f,-0.6673f,-0.4932f,0.558f,0.1641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm_group) {transformation: [-0.7295f,0.5838f,-0.3564f,0.2031f,-0.15f,-0.6449f,-0.7494f,1.1495f,-0.6673f,-0.4932f,0.558f,0.1784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_l) {transformation: [-0.4644f,0.6348f,-0.8389f,0.5781f,1.0142f,0.5139f,-0.1725f,1.453f,0.2797f,-0.8095f,-0.7674f,-0.2998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm_group) {transformation: [-0.7295f,0.552f,0.4038f,0.3467f,-0.15f,0.4469f,-0.8819f,1.2657f,-0.6673f,-0.7039f,-0.2432f,-0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_body) {transformation: [1.15f,-0.0004f,-0.004f,-0.0003f,0.0004f,1.1499f,0.0119f,1.5113f,0.004f,-0.0119f,1.1499f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_pants) {transformation: [-1.1f,-0.0004f,0.0039f,-0.0002f,-0.0004f,1.0999f,-0.0114f,1.3379f,-0.0039f,-0.0114f,-1.0999f,-0.0068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"yuji_mount":{"px":0,"py":0.6875,"pz":0,"ry":0.201634345,"rx":-0.5947461197}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/domain_expansion/zzz/frames/45_locator_commands