# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(yuji_lower_left_leg) {transformation: [-1f,0f,0f,0.1156f,0f,1f,-0.0017f,0.3406f,0f,-0.0017f,-1f,-0.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_r) {transformation: [1.1f,0f,0f,0.1156f,0f,1.1f,0.0018f,0.702f,0f,-0.0018f,1.1f,-0.001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_r) {transformation: [1.2f,0f,0f,0.1156f,0f,1.2f,0.002f,0.6904f,0f,-0.002f,1.2f,-0.001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_left_leg_group) {transformation: [-1f,0f,0f,0.1156f,0f,1f,-0.0017f,0.3406f,0f,-0.0017f,-1f,-0.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg) {transformation: [-1f,0f,0f,0.1156f,0f,1f,0.0013f,0.6875f,0f,0.0013f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_r) {transformation: [1.1f,0f,0f,0.1156f,0f,1.1f,-0.0014f,0.991f,0f,0.0014f,1.1f,0.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg_group) {transformation: [-1f,0f,0f,0.1156f,0f,1f,0.0013f,0.6875f,0f,0.0013f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,-0.0008f,0.3406f,0f,-0.0008f,-1f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_l) {transformation: [1.1f,0f,0f,-0.1156f,0f,1.1f,0.0009f,0.702f,0f,-0.0009f,1.1f,-0.001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_l) {transformation: [1.2f,0f,0f,-0.1156f,0f,1.2f,0.001f,0.6904f,0f,-0.001f,1.2f,-0.001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg_group) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,-0.0008f,0.3406f,0f,-0.0008f,-1f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,0.0021f,0.6875f,0f,0.0021f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_l) {transformation: [1.1f,0f,0f,-0.1156f,0f,1.1f,-0.0023f,0.991f,0f,0.0023f,1.1f,0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg_group) {transformation: [-1f,0f,0f,-0.1156f,0f,1f,0.0021f,0.6875f,0f,0.0021f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist) {transformation: [-1f,-0.0001f,0.0008f,0f,-0.0001f,1f,-0.0025f,0.6875f,-0.0008f,-0.0025f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist_group) {transformation: [-1f,-0.0001f,0.0008f,0f,-0.0001f,1f,-0.0025f,0.6875f,-0.0008f,-0.0025f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head) {transformation: [-1f,-0.0001f,0.0008f,-0.0001f,0.0002f,0.9412f,0.3377f,1.3523f,-0.0008f,0.3377f,-0.9412f,-0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_helmet) {transformation: [0.65f,-0.0001f,-0.0005f,-0.0001f,-0.0001f,0.6118f,-0.2195f,1.502f,0.0005f,0.2195f,0.6118f,0.052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head_group) {transformation: [-1f,-0.0001f,0.0008f,-0.0001f,0.0002f,0.9412f,0.3377f,1.3523f,-0.0008f,0.3377f,-0.9412f,-0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm) {transformation: [-0.7467f,-0.5201f,-0.4146f,-0.3469f,0.1454f,0.4806f,-0.8648f,1.2656f,0.6491f,-0.706f,-0.2833f,-0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm) {transformation: [-0.7467f,-0.5923f,0.3026f,-0.2287f,0.1454f,-0.5893f,-0.7947f,1.1235f,0.6491f,-0.5494f,0.5262f,0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm_group) {transformation: [-0.7467f,-0.5923f,0.3026f,-0.2116f,0.1454f,-0.5893f,-0.7947f,1.1406f,0.6491f,-0.5494f,0.5262f,0.1819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_r) {transformation: [-0.4768f,-0.5981f,0.8587f,-0.5649f,-0.9945f,0.5527f,-0.1672f,1.467f,-0.3257f,-0.8119f,-0.7464f,-0.2977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm_group) {transformation: [-0.7467f,-0.5201f,-0.4146f,-0.3469f,0.1454f,0.4806f,-0.8648f,1.2656f,0.6491f,-0.706f,-0.2833f,-0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm) {transformation: [-0.7456f,0.5219f,0.4143f,0.3468f,-0.1449f,0.4799f,-0.8652f,1.2657f,-0.6504f,-0.7052f,-0.2822f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm) {transformation: [-0.7456f,0.5928f,-0.3043f,0.2282f,-0.1449f,-0.59f,-0.7943f,1.1237f,-0.6504f,-0.5482f,0.5258f,0.1665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm_group) {transformation: [-0.7456f,0.5928f,-0.3043f,0.2111f,-0.1449f,-0.59f,-0.7943f,1.1408f,-0.6504f,-0.5482f,0.5258f,0.1823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_l) {transformation: [-0.4765f,0.6001f,-0.8575f,0.5656f,0.995f,0.5519f,-0.1667f,1.4668f,0.3246f,-0.811f,-0.748f,-0.2967f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm_group) {transformation: [-0.7456f,0.5219f,0.4143f,0.3468f,-0.1449f,0.4799f,-0.8652f,1.2657f,-0.6504f,-0.7052f,-0.2822f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_body) {transformation: [1.15f,-0.0001f,-0.001f,-0.0001f,0.0001f,1.15f,0.0029f,1.5113f,0.001f,-0.0029f,1.15f,-0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_pants) {transformation: [-1.1f,-0.0001f,0.0009f,-0.0001f,-0.0001f,1.1f,-0.0027f,1.3379f,-0.0009f,-0.0027f,-1.1f,-0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"yuji_mount":{"px":0,"py":0.6875,"pz":0,"ry":0.0483892668,"rx":-0.1428649884}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/domain_expansion/zzz/frames/49_locator_commands