# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:the_world_vfx rig_hash set value 'f261de2fe5476b5134302e455f623c6d135a1ddde5483e6c5bb30bff420bdd75'
scoreboard objectives add aj.knife.frame dummy
scoreboard objectives add aj.flurry.frame dummy
scoreboard objectives add aj.ring_right.frame dummy
scoreboard objectives add aj.ring_left.frame dummy
scoreboard objectives add aj.flurry_knife.frame dummy
scoreboard objectives add aj.barrage_left_1.frame dummy
scoreboard objectives add aj.barrage_left_2.frame dummy
scoreboard objectives add aj.barrage_left_3.frame dummy
scoreboard objectives add aj.barrage_right_1.frame dummy
scoreboard objectives add aj.barrage_right_2.frame dummy
scoreboard objectives add aj.entity_wind_start.frame dummy
scoreboard objectives add aj.entity_wind_end.frame dummy
scoreboard objectives add aj.projectile_wind.frame dummy
scoreboard objectives add aj.timestopping_knife.frame dummy