# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gojo_cutscene.root] run return 0
execute on passengers if entity @s[tag=aj.gojo_cutscene.data] unless data entity @s {data:{rigHash: '82c71748affe3749a2098c01649ad73397cc3a46eeef438321ff94080236bd22'}} on vehicle run function animated_java:gojo_cutscene/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1