# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^-0.08535125 ^0.0482425 ~0 ~-90
data modify entity @s data.locators.right merge value { px: 0, py: -0.08535125, pz: 0.0482425, ry: 0, rx: -90 }