# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from entity @s data.locators.coil_mount.uuid
function animated_java:toji/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.acrobatics_mount.uuid
function animated_java:toji/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.text_location.uuid
function animated_java:toji/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args