# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.satoru.root] run return 0
execute on passengers if entity @s[tag=aj.satoru.data] unless data entity @s {data:{rigHash: 'c46f2caf848bd91933ec1b5923e1911f7749feb27b8111d4b202827d29752f70'}} on vehicle run function animated_java:satoru/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1