# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(arm_right) {transformation: [-0.9942f,0.1069f,-0.0138f,-0.4716f,0.0054f,-0.0789f,-0.9969f,0.3837f,-0.1077f,-0.9911f,0.0779f,0.4725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"right":{"px":-0.4688631564,"py":0.3271441223,"pz":0.4439520965,"ry":190.075039972,"rx":-85.4634229389}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(right) positioned ^-0.4688631564 ^0.3271441223 ^0.4439520965 rotated ~190.075039972 ~-85.4634229389 run function aj:the_world_vfx/animations/barrage_right_1/zzz/frames/1_locator_right