# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.president.animation.kidnap.playing
tag @s remove aj.president.animation.self_kidnap.playing
tag @s remove aj.president.animation.self_kidnap_tiny.playing
tag @s remove aj.president.animation.self_kidnap_giant.playing
tag @s remove aj.president.animation.shake_key.playing
tag @s remove aj.president.animation.refreshments.playing
tag @s remove aj.president.animation.turtle_idle.playing
tag @s remove aj.president.animation.turtle_walk.playing