# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_center) {transformation: [-0.75f,0f,0f,0f,0f,0.75f,0f,0f,0f,0f,-0.75f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_middle) {transformation: [-1.9083f,0f,0f,0f,0f,1.9083f,0f,0f,0f,0f,-1.9083f,1.4312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_middle_alt) {transformation: [-1.9083f,0f,0f,0f,0f,1.9083f,0f,0f,0f,0f,-1.9083f,-1.4313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,-1.5188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,1.5188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"commands":{"posx":0,"posy":0,"posz":0,"roty":0,"rotx":0},"random":{"posx":0,"posy":0,"posz":0,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] run function animated_java:hatsune_miku_vfx/variants/countdown3/apply