# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s @n[type=marker,tag=yujiWarp]
kill @n[type=marker,tag=yujiWarp]
particle minecraft:poof ~ ~1 ~ 0.5 1 0.5 0.5 25 force @a