# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(waist) {transformation: [-1f,0f,0f,0f,0f,0.9898f,-0.1424f,0.75f,0f,-0.1424f,-0.9898f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist_group) {transformation: [-1f,0f,0f,0f,0f,0.9898f,-0.1424f,0.75f,0f,-0.1424f,-0.9898f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9905f,-0.1378f,1.4614f,0f,-0.1378f,-0.9905f,-0.1024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0.65f,0f,0f,0f,0f,0.6438f,0.0896f,1.6317f,0f,-0.0896f,0.6438f,-0.1261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_group) {transformation: [-1f,0f,0f,0f,0f,0.9905f,-0.1378f,1.4614f,0f,-0.1378f,-0.9905f,-0.1024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7743f,0.0307f,-0.6321f,-0.375f,0.5671f,0.4769f,-0.6716f,1.3686f,0.2808f,-0.8784f,-0.3866f,-0.089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7743f,-0.2578f,-0.5779f,-0.3917f,0.5671f,0.1226f,-0.8145f,1.2383f,0.2808f,-0.9584f,0.0513f,0.1281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife1) {transformation: [0f,0f,0f,-0.3379f,0f,0f,0f,1.2165f,0f,0f,0f,0.404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife2) {transformation: [0f,0f,0f,-0.3185f,0f,0f,0f,1.2023f,0f,0f,0f,0.397f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife3) {transformation: [0f,0f,0f,-0.2992f,0f,0f,0f,1.1881f,0f,0f,0f,0.3899f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm_group) {transformation: [-0.7743f,-0.2578f,-0.5779f,-0.3836f,0.5671f,0.1226f,-0.8145f,1.2345f,0.2808f,-0.9584f,0.0513f,0.158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [-0.7269f,0.0353f,0.8904f,-0.3611f,-0.7723f,0.5484f,-0.6522f,1.5847f,-0.4446f,-1.0102f,-0.323f,-0.4871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm_group) {transformation: [-0.7743f,0.0307f,-0.6321f,-0.375f,0.5671f,0.4769f,-0.6716f,1.3686f,0.2808f,-0.8784f,-0.3866f,-0.089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.7743f,-0.0307f,0.6321f,0.375f,-0.5671f,0.4769f,-0.6716f,1.3686f,-0.2808f,-0.8784f,-0.3866f,-0.089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.7743f,0.2578f,0.5779f,0.3917f,-0.5671f,0.1226f,-0.8145f,1.2383f,-0.2808f,-0.9584f,0.0513f,0.1281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(knife4) {transformation: [0f,0f,0f,0.321f,0f,0f,0f,1.2041f,0f,0f,0f,0.3978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm_group) {transformation: [-0.7743f,0.2578f,0.5779f,0.3836f,-0.5671f,0.1226f,-0.8145f,1.2345f,-0.2808f,-0.9584f,0.0513f,0.158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [-0.7269f,-0.0353f,-0.8904f,0.3611f,0.7723f,0.5484f,-0.6522f,1.5847f,0.4446f,-1.0102f,-0.323f,-0.4871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm_group) {transformation: [-0.7743f,-0.0307f,0.6321f,0.375f,-0.5671f,0.4769f,-0.6716f,1.3686f,-0.2808f,-0.8784f,-0.3866f,-0.089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,1.1383f,0.1638f,1.6315f,0f,-0.1638f,1.1383f,-0.1269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,1.0888f,-0.1567f,1.446f,0f,-0.1567f,-1.0888f,-0.1002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"dio_shoulder":{"px":0.25,"py":1.4037795611,"pz":-0.2835221077,"ry":0,"rx":-8.1896296296}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:the_world/animations/timestop_knife_throw/zzz/frames/10_locator_constant