# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage minecraft:custom gojo.attack.red.id int 1 run scoreboard players get @s customGojo_RedID
function custom:items/gojo/moves/3/movement with storage minecraft:custom gojo.attack.red