# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gojo/remove/zzz/this/kill_locator with entity @s data.locators.locator_blue_hand
function animated_java:gojo/remove/zzz/this/kill_locator with entity @s data.locators.locator_purple_hand
function animated_java:gojo/remove/zzz/this/kill_locator with entity @s data.locators.locator_red_hand
function animated_java:gojo/remove/zzz/this/kill_locator with entity @s data.locators.locator_blue
function animated_java:gojo/remove/zzz/this/kill_locator with entity @s data.locators.locator_red
function animated_java:gojo/remove/zzz/this/kill_locator with entity @s data.locators.locator_purple
function animated_java:gojo/remove/zzz/this/kill_camera with entity @s data.locators.camera_camera