# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:toji/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'd5ad27636dfc09d06b8eabb97c4d59aef448f71e5ea22ba303d5b507e40f6653'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack