# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage minecraft:custom yuji.moves.id int 1 run scoreboard players get @s customYuji.PactID
function custom:items/yuji/moves/3/position with storage minecraft:custom yuji.moves
playsound minecraft:yuji.pact.voiceline2 player @a ~ ~ ~ 0.5