# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.rage_mode.frame matches 78.. run scoreboard players set @s aj.rage_mode.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.rage_mode.frame
execute at @s run function animated_java:the_world/animations/rage_mode/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.rage_mode.frame 1