# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-0.5151f,0f,0f,0.875f,0f,0.5121f,0.0556f,3.5714f,0f,0.0556f,-0.5121f,-4.4736f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-0.5151f,0f,0f,0.875f,0f,0.5118f,0.0578f,3.673f,0f,0.0578f,-0.5118f,-4.6565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-0.5135f,-0.0289f,-0.0273f,0.9935f,-0.0312f,0.5123f,0.0433f,3.5091f,0.0247f,0.0448f,-0.5125f,-4.804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-0.5135f,-0.0378f,-0.0123f,0.9877f,-0.0312f,0.4819f,-0.1793f,3.5207f,0.0247f,-0.178f,-0.4827f,-4.9112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-0.5135f,-0.0289f,-0.0273f,0.7682f,-0.0312f,0.5123f,0.0433f,3.5091f,0.0247f,0.0448f,-0.5125f,-4.804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-0.5135f,-0.0378f,-0.0123f,0.7623f,-0.0312f,0.4819f,-0.1793f,3.5207f,0.0247f,-0.178f,-0.4827f,-4.9112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-0.5151f,0f,0f,0.875f,0f,0.4884f,0.1636f,3.7804f,0f,0.1636f,-0.4884f,-5.0279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-0.5151f,0f,0f,0.875f,0f,0.458f,0.2356f,3.7698f,0f,0.2356f,-0.458f,-5.3592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0663f,0f,0f,0f,-4.8447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blb) {transformation: [-0.5151f,0f,0f,1.0199f,0f,0.3443f,0.3831f,3.6044f,0f,0.3831f,-0.3443f,-5.3186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backleftleg) {transformation: [-0.5151f,0f,0f,1.0199f,0f,0.3806f,0.347f,3.7269f,0f,0.347f,-0.3806f,-5.3812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(brb) {transformation: [-0.5151f,0f,0f,0.7301f,0f,0.3443f,0.3831f,3.6044f,0f,0.3831f,-0.3443f,-5.3186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backrightleg) {transformation: [-0.5151f,0f,0f,0.7301f,0f,0.3806f,0.347f,3.7269f,0f,0.347f,-0.3806f,-5.3812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.875,"py":3.587381653,"pz":-4.4717466944,"ry":0,"rx":6.4379412618},"position":{"px":0.875,"py":3.4230097697,"pz":-5.2479242668,"ry":0,"rx":27.2179412618},"text_location":{"px":0.875,"py":3.7370959581,"pz":-5.0139798967,"ry":0,"rx":27.2179412618}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/summon/zzz/frames/21_locator_commands
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/summon/zzz/frames/21_locator_constant