# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-0.6999f,0f,0f,0.875f,0f,0.688f,0.1283f,3.336f,0f,0.1283f,-0.688f,-4.1953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-0.6999f,0f,0f,0.875f,0f,0.686f,0.1385f,3.4951f,0f,0.1385f,-0.686f,-4.4309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-0.6978f,-0.046f,-0.0284f,1.0348f,-0.045f,0.698f,-0.0248f,3.3102f,0.03f,-0.0229f,-0.6988f,-4.6466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-0.6978f,-0.0533f,-0.0094f,1.0281f,-0.045f,0.6392f,-0.2813f,3.3174f,0.03f,-0.2799f,-0.6407f,-4.7929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-0.6978f,-0.046f,-0.0284f,0.7287f,-0.045f,0.698f,-0.0248f,3.3102f,0.03f,-0.0229f,-0.6988f,-4.6466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-0.6978f,-0.0533f,-0.0094f,0.7219f,-0.045f,0.6392f,-0.2813f,3.3174f,0.03f,-0.2799f,-0.6407f,-4.7929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-0.6999f,0f,0f,0.875f,0f,0.643f,0.2763f,3.6822f,0f,0.2763f,-0.643f,-4.9218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-0.6999f,0f,0f,0.875f,0f,0.6271f,0.3107f,3.661f,0f,0.3107f,-0.6271f,-5.3717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,4.0744f,0f,0f,0f,-4.6787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blb) {transformation: [-0.6999f,0f,0f,1.0718f,0f,0.496f,0.4938f,3.4563f,0f,0.4938f,-0.496f,-5.284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backleftleg) {transformation: [-0.6999f,0f,0f,1.0718f,0f,0.6013f,0.3581f,3.6022f,0f,0.3581f,-0.6013f,-5.4008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(brb) {transformation: [-0.6999f,0f,0f,0.6782f,0f,0.496f,0.4938f,3.4563f,0f,0.4938f,-0.496f,-5.284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backrightleg) {transformation: [-0.6999f,0f,0f,0.6782f,0f,0.6013f,0.3581f,3.6022f,0f,0.3581f,-0.6013f,-5.4008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.875,"py":3.3574122522,"pz":-4.1909830495,"ry":0,"rx":11.4136583062},"position":{"px":0.875,"py":3.1921166477,"pz":-5.2134291095,"ry":0,"rx":26.3536583062},"text_location":{"px":0.875,"py":3.6236219102,"pz":-4.9020347073,"ry":0,"rx":26.3536583062}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/summon/zzz/frames/22_locator_commands
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/summon/zzz/frames/22_locator_constant