# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-0.9897f,0f,0f,0.875f,0f,0.8783f,0.4563f,1.6517f,0f,0.4563f,-0.8783f,-2.5187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-0.9897f,0f,0f,0.875f,0f,0.846f,0.5137f,1.9766f,0f,0.5137f,-0.846f,-2.7557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-0.9867f,-0.077f,-0.004f,1.0943f,-0.0674f,0.8871f,-0.4338f,1.8356f,0.0373f,-0.4322f,-0.8896f,-3.0903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-0.9867f,-0.0739f,0.022f,1.0915f,-0.0674f,0.6905f,-0.7058f,1.768f,0.0373f,-0.7052f,-0.6935f,-3.2865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-0.9867f,-0.077f,-0.004f,0.6613f,-0.0674f,0.8871f,-0.4338f,1.8356f,0.0373f,-0.4322f,-0.8896f,-3.0903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-0.9867f,-0.0739f,0.022f,0.6585f,-0.0674f,0.6905f,-0.7058f,1.768f,0.0373f,-0.7052f,-0.6935f,-3.2865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-0.9897f,0f,0f,0.875f,0f,0.8743f,0.4638f,2.2971f,0f,0.4638f,-0.8743f,-3.4259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-0.9897f,0f,0f,0.875f,0f,0.9597f,0.2422f,2.1335f,0f,0.2422f,-0.9597f,-4.0414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9118f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,2.9117f,0f,0f,0f,-3.207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blb) {transformation: [-0.9897f,0f,0f,1.1534f,0f,0.9159f,0.3751f,2.0284f,0f,0.3751f,-0.9159f,-3.8003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backleftleg) {transformation: [-0.9897f,0f,0f,1.1534f,0f,0.9451f,-0.294f,2.0435f,0f,-0.294f,-0.9451f,-4.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(brb) {transformation: [-0.9897f,0f,0f,0.5966f,0f,0.9159f,0.3751f,2.0284f,0f,0.3751f,-0.9159f,-3.8003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backrightleg) {transformation: [-0.9897f,0f,0f,0.5966f,0f,0.9451f,-0.294f,2.0435f,0f,-0.294f,-0.9451f,-4.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.875,"py":1.6781797673,"pz":-2.5026147444,"ry":0,"rx":31.2664040063},"position":{"px":0.875,"py":1.5325416498,"pz":-3.682656174,"ry":0,"rx":14.164665725},"text_location":{"px":0.875,"py":2.2220054063,"pz":-3.3810500417,"ry":0,"rx":14.164665725}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/summon/zzz/frames/26_locator_commands
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:billy/animations/summon/zzz/frames/26_locator_constant