# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.blitz_slam.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:toji/animations/blitz_slam/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only