# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage minecraft:custom yuji.awakening.id int 1 run scoreboard players get @s customUniversal_RigID
data merge storage minecraft:custom {yuji:{awakening:{tags:"tag=YujiUser",objective:"customUniversal_RigID",path:"custom:items/yuji/awakening/setup with storage minecraft:custom yuji.awakening",rig:"yuji"}}}
function custom:universal/find_player with storage minecraft:custom yuji.awakening
function custom:items/yuji/moves/reset/rig with storage minecraft:custom yuji.awakening