# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/sukuna_old/zzz/frames/196_locator_commands
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/sukuna_old/zzz/frames/196_locator_constant
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/sukuna_old/zzz/frames/196_locator_skins
execute positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:yuji/animations/sukuna_old/zzz/frames/196_locator_sfx
$execute as $(mount) positioned ^0 ^0.75 ^0 rotated ~0 ~0 run function aj:yuji/animations/sukuna_old/zzz/frames/196_locator_mount