# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouthb) {transformation: [-1f,0f,0f,0.875f,0f,0.8388f,0.5444f,0.2548f,0f,0.5444f,-0.8388f,-0.0785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head3) {transformation: [-1f,0f,0f,0.875f,0f,0.8388f,0.5444f,0.59f,0f,0.5444f,-0.8388f,-0.308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom) {transformation: [-1f,0f,0f,1.0938f,0f,0.9993f,0.0382f,0.1978f,0f,0.0382f,-0.9993f,-0.5693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontleftleg) {transformation: [-1f,0f,0f,1.0938f,0f,0.9766f,-0.2152f,0.249f,0f,-0.2152f,-0.9766f,-0.7725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bottom2) {transformation: [-1f,0f,0f,0.6563f,0f,0.9993f,0.0382f,0.1978f,0f,0.0382f,-0.9993f,-0.5693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(frontrightleg2) {transformation: [-1f,0f,0f,0.6563f,0f,0.9766f,-0.2152f,0.249f,0f,-0.2152f,-0.9766f,-0.7725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front) {transformation: [-1f,0f,0f,0.875f,0f,0.9739f,0.227f,0.7298f,0f,0.227f,-0.9739f,-1.0455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top) {transformation: [-1f,0f,0f,0.875f,0f,0.9984f,0.0572f,0.45f,0f,0.0572f,-0.9984f,-1.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(waist) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(helmet) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4188f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4188f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4188f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_arm_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4188f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chestplate_body) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4188f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_pants) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_l) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_lower_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(boots_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lower_left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leggings_upper_r) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0.875f,0f,0f,0f,1.4187f,0f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blb) {transformation: [-1f,0f,0f,1.1563f,0f,1f,0f,0.3073f,0f,0f,-1f,-1.3625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backleftleg) {transformation: [-1f,0f,0f,1.1563f,0f,0.9848f,-0.1736f,0.3562f,0f,-0.1736f,-0.9848f,-1.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(brb) {transformation: [-1f,0f,0f,0.5938f,0f,1f,0f,0.3073f,0f,0f,-1f,-1.3625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(backrightleg) {transformation: [-1f,0f,0f,0.5938f,0f,0.9848f,-0.1736f,0.3562f,0f,-0.1736f,-0.9848f,-1.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"mouth":{"px":0.875,"py":0.2809731094,"pz":-0.0615052005,"ry":0,"rx":32.9824161808},"position":{"px":0.875,"py":-0.05,"pz":-1.125,"ry":0,"rx":0},"text_location":{"px":0.875,"py":0.7,"pz":-1,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args