# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(yuji_lower_left_leg) {transformation: [-0.9888f,-0.149f,-0.0039f,0.1673f,-0.0086f,0.0305f,0.9995f,0.0592f,-0.1488f,0.9884f,-0.0314f,-0.343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_r) {transformation: [1.0877f,-0.1639f,0.0043f,0.1134f,0.0094f,0.0336f,-1.0994f,0.0703f,0.1637f,1.0872f,0.0346f,0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_r) {transformation: [1.1866f,-0.1788f,0.0047f,0.1152f,0.0103f,0.0366f,-1.1994f,0.0699f,0.1786f,1.186f,0.0377f,0.0027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_left_leg_group) {transformation: [-0.9888f,-0.149f,-0.0039f,0.1673f,-0.0086f,0.0305f,0.9995f,0.0592f,-0.1488f,0.9884f,-0.0314f,-0.343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg) {transformation: [-0.9888f,-0.1489f,-0.0071f,0.1156f,-0.0086f,0.0094f,0.9999f,0.0625f,-0.1488f,0.9888f,-0.0105f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_r) {transformation: [1.0877f,-0.1638f,0.0078f,0.0704f,0.0094f,0.0103f,-1.0999f,0.0653f,0.1637f,1.0877f,0.0116f,0.3001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg_group) {transformation: [-0.9888f,-0.1489f,-0.0071f,0.1156f,-0.0086f,0.0094f,0.9999f,0.0625f,-0.1488f,0.9888f,-0.0105f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg) {transformation: [-0.9888f,0.149f,0.0039f,-0.1673f,0.0086f,0.0305f,0.9995f,0.0592f,0.1488f,0.9884f,-0.0314f,-0.343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_l) {transformation: [1.0877f,0.1639f,-0.0043f,-0.1134f,-0.0094f,0.0336f,-1.0994f,0.0703f,-0.1637f,1.0872f,0.0346f,0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_l) {transformation: [1.1866f,0.1788f,-0.0047f,-0.1152f,-0.0103f,0.0366f,-1.1994f,0.0699f,-0.1786f,1.186f,0.0377f,0.0027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg_group) {transformation: [-0.9888f,0.149f,0.0039f,-0.1673f,0.0086f,0.0305f,0.9995f,0.0592f,0.1488f,0.9884f,-0.0314f,-0.343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg) {transformation: [-0.9888f,0.1489f,0.0071f,-0.1156f,0.0086f,0.0094f,0.9999f,0.0625f,0.1488f,0.9888f,-0.0105f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_l) {transformation: [1.0877f,0.1638f,-0.0078f,-0.0704f,-0.0094f,0.0103f,-1.0999f,0.0653f,-0.1637f,1.0877f,0.0116f,0.3001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg_group) {transformation: [-0.9888f,0.1489f,0.0071f,-0.1156f,0.0086f,0.0094f,0.9999f,0.0625f,0.1488f,0.9888f,-0.0105f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist) {transformation: [-1f,0f,0f,0f,0f,-0.0215f,0.9998f,0.0625f,0f,0.9998f,0.0215f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist_group) {transformation: [-1f,0f,0f,0f,0f,-0.0215f,0.9998f,0.0625f,0f,0.9998f,0.0215f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head) {transformation: [-1f,0f,0f,0f,0f,-0.0811f,0.9967f,0.0482f,0f,0.9967f,0.0811f,0.6647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_helmet) {transformation: [0.65f,0f,0f,0f,0f,-0.0527f,-0.6479f,0.0353f,0f,0.6479f,-0.0527f,0.8232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head_group) {transformation: [-1f,0f,0f,0f,0f,-0.0811f,0.9967f,0.0482f,0f,0.9967f,0.0811f,0.6647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm) {transformation: [-0.81f,0.5848f,-0.0436f,-0.3469f,-0.029f,0.0343f,0.999f,0.0501f,0.5857f,0.8105f,-0.0108f,0.578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm) {transformation: [-0.81f,0.5862f,0.0151f,-0.4821f,-0.029f,-0.0658f,0.9974f,0.0393f,0.5857f,0.8075f,0.0703f,0.3905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm_group) {transformation: [-0.81f,0.5862f,0.0151f,-0.499f,-0.029f,-0.0658f,0.9974f,0.0412f,0.5857f,0.8075f,0.0703f,0.3671f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_r) {transformation: [-0.0501f,0.6725f,0.9315f,-0.1018f,1.1488f,0.0394f,0.0333f,0.0644f,-0.0124f,0.932f,-0.6736f,0.9177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm_group) {transformation: [-0.81f,0.5848f,-0.0436f,-0.3469f,-0.029f,0.0343f,0.999f,0.0501f,0.5857f,0.8105f,-0.0108f,0.578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm) {transformation: [-0.81f,-0.5848f,0.0436f,0.3469f,0.029f,0.0343f,0.999f,0.0501f,-0.5857f,0.8105f,-0.0108f,0.578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm) {transformation: [-0.81f,-0.5862f,-0.0151f,0.4821f,0.029f,-0.0658f,0.9974f,0.0393f,-0.5857f,0.8075f,0.0703f,0.3905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm_group) {transformation: [-0.81f,-0.5862f,-0.0151f,0.499f,0.029f,-0.0658f,0.9974f,0.0412f,-0.5857f,0.8075f,0.0703f,0.3671f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_l) {transformation: [-0.0501f,-0.6725f,-0.9315f,0.1018f,-1.1488f,0.0394f,0.0333f,0.0644f,0.0124f,0.932f,-0.6736f,0.9177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm_group) {transformation: [-0.81f,-0.5848f,0.0436f,0.3469f,0.029f,0.0343f,0.999f,0.0501f,-0.5857f,0.8105f,-0.0108f,0.578f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,-0.0247f,-1.1497f,0.0448f,0f,1.1497f,-0.0247f,0.8236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,-0.0236f,1.0997f,0.0485f,0f,1.0997f,0.0236f,0.6502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"yuji_mount":{"px":0,"py":0.0625,"pz":0,"ry":180,"rx":88.76953125}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args