# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(yuji_lower_left_leg) {transformation: [-0.9857f,-0.1648f,0.0338f,0.1694f,0.0795f,-0.2787f,0.9571f,3.7826f,-0.1483f,0.9461f,0.2878f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_r) {transformation: [1.0843f,-0.1813f,-0.0372f,0.1099f,-0.0874f,-0.3066f,-1.0528f,3.6818f,0.1632f,1.0407f,-0.3166f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_r) {transformation: [1.1829f,-0.1978f,-0.0406f,0.1118f,-0.0954f,-0.3345f,-1.1485f,3.6851f,0.178f,1.1353f,-0.3454f,-0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_left_leg_group) {transformation: [-0.9857f,-0.1648f,0.0338f,0.1694f,0.0795f,-0.2787f,0.9571f,3.7826f,-0.1483f,0.9461f,0.2878f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg) {transformation: [-0.9857f,-0.1551f,0.0654f,0.1156f,0.0795f,-0.0867f,0.9931f,3.7525f,-0.1483f,0.9841f,0.0977f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_r) {transformation: [1.0843f,-0.1706f,-0.0719f,0.0686f,-0.0874f,-0.0953f,-1.0924f,3.7262f,0.1632f,1.0825f,-0.1075f,0.2987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_leg_group) {transformation: [-0.9857f,-0.1551f,0.0654f,0.1156f,0.0795f,-0.0867f,0.9931f,3.7525f,-0.1483f,0.9841f,0.0977f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg) {transformation: [-0.9857f,0.1648f,-0.0338f,-0.1694f,-0.0795f,-0.2787f,0.9571f,3.7826f,0.1483f,0.9461f,0.2878f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_lower_l) {transformation: [1.0843f,0.1813f,0.0372f,-0.1099f,0.0874f,-0.3066f,-1.0528f,3.6818f,-0.1632f,1.0407f,-0.3166f,0.0005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_boots_l) {transformation: [1.1829f,0.1978f,0.0406f,-0.1118f,0.0954f,-0.3345f,-1.1485f,3.6851f,-0.178f,1.1353f,-0.3454f,-0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_lower_right_leg_group) {transformation: [-0.9857f,0.1648f,-0.0338f,-0.1694f,-0.0795f,-0.2787f,0.9571f,3.7826f,0.1483f,0.9461f,0.2878f,-0.3414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg) {transformation: [-0.9857f,0.1551f,-0.0654f,-0.1156f,-0.0795f,-0.0867f,0.9931f,3.7525f,0.1483f,0.9841f,0.0977f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_upper_l) {transformation: [1.0843f,0.1706f,0.0719f,-0.0686f,0.0874f,-0.0953f,-1.0924f,3.7262f,-0.1632f,1.0825f,-0.1075f,0.2987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_leg_group) {transformation: [-0.9857f,0.1551f,-0.0654f,-0.1156f,-0.0795f,-0.0867f,0.9931f,3.7525f,0.1483f,0.9841f,0.0977f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist) {transformation: [-1f,0f,0f,0f,0f,0.0872f,0.9962f,3.7525f,0f,0.9962f,-0.0872f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_waist_group) {transformation: [-1f,0f,0f,0f,0f,0.0872f,0.9962f,3.7525f,0f,0.9962f,-0.0872f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head) {transformation: [-1f,0f,0f,0f,0f,0.3007f,0.9537f,3.8104f,0f,0.9537f,-0.3007f,0.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_helmet) {transformation: [0.65f,0f,0f,0f,0f,0.1955f,-0.6199f,3.8583f,0f,0.6199f,0.1955f,0.8139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_head_group) {transformation: [-1f,0f,0f,0f,0f,0.3007f,0.9537f,3.8104f,0f,0.9537f,-0.3007f,0.6623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm) {transformation: [-0.8143f,0.557f,0.1633f,-0.3469f,0.1581f,-0.0578f,0.9857f,3.8029f,0.5585f,0.8285f,-0.0411f,0.5759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm) {transformation: [-0.8143f,0.5736f,0.0892f,-0.4752f,0.1581f,0.0714f,0.9848f,3.82f,0.5585f,0.816f,-0.1488f,0.384f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_forearm_group) {transformation: [-0.8143f,0.5736f,0.0892f,-0.4918f,0.1581f,0.0714f,0.9848f,3.8179f,0.5585f,0.816f,-0.1488f,0.3604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_r) {transformation: [0.1878f,0.6406f,0.9364f,-0.1134f,1.1336f,-0.0664f,-0.1819f,3.7787f,-0.0472f,0.9528f,-0.6423f,0.9232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_right_arm_group) {transformation: [-0.8143f,0.557f,0.1633f,-0.3469f,0.1581f,-0.0578f,0.9857f,3.8029f,0.5585f,0.8285f,-0.0411f,0.5759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm) {transformation: [-0.8143f,-0.557f,-0.1633f,0.3469f,-0.1581f,-0.0578f,0.9857f,3.8029f,-0.5585f,0.8285f,-0.0411f,0.5759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm) {transformation: [-0.8143f,-0.5736f,-0.0892f,0.4752f,-0.1581f,0.0714f,0.9848f,3.82f,-0.5585f,0.816f,-0.1488f,0.384f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_forearm_group) {transformation: [-0.8143f,-0.5736f,-0.0892f,0.4918f,-0.1581f,0.0714f,0.9848f,3.8179f,-0.5585f,0.816f,-0.1488f,0.3604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_arm_l) {transformation: [0.1878f,-0.6406f,-0.9364f,0.1134f,-1.1336f,-0.0664f,-0.1819f,3.7787f,0.0472f,0.9528f,-0.6423f,0.9232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_left_arm_group) {transformation: [-0.8143f,-0.557f,-0.1633f,0.3469f,-0.1581f,-0.0578f,0.9857f,3.8029f,-0.5585f,0.8285f,-0.0411f,0.5759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_chestplate_body) {transformation: [1.15f,0f,0f,0f,0f,0.1002f,-1.1456f,3.8243f,0f,1.1456f,0.1002f,0.8207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(yuji_leggings_pants) {transformation: [-1.1f,0f,0f,0f,0f,0.0959f,1.0958f,3.8092f,0f,1.0958f,-0.0959f,0.6479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"yuji_mount":{"px":0,"py":3.7525,"pz":0,"ry":0,"rx":85}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args