# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:item_display ^0 ^1.0625 ^0.9375 {Tags:["aj.billy.bone.back.decendant","aj.billy.bone.back.decendant.locator","aj.billy.bone.back.tree","aj.billy.bone.billy.decendant","aj.billy.bone.billy.decendant.locator","aj.billy.bone.billy.tree","aj.billy.bone.bodyf.decendant","aj.billy.bone.bodyf.decendant.locator","aj.billy.bone.bodyf.tree","aj.billy.bone.front.decendant","aj.billy.bone.front.decendant.locator","aj.billy.bone.front.tree","aj.billy.bone.head3.child","aj.billy.bone.head3.child.locator","aj.billy.bone.head3.decendant","aj.billy.bone.head3.decendant.locator","aj.billy.bone.head3.tree","aj.billy.bone.top.decendant","aj.billy.bone.top.decendant.locator","aj.billy.bone.top.tree","aj.billy.entity","aj.billy.locator","aj.billy.locator.mount","aj.billy.node","aj.billy.node.mount","aj.global.bone.back.decendant","aj.global.bone.back.decendant.locator","aj.global.bone.back.tree","aj.global.bone.billy.decendant","aj.global.bone.billy.decendant.locator","aj.global.bone.billy.tree","aj.global.bone.bodyf.decendant","aj.global.bone.bodyf.decendant.locator","aj.global.bone.bodyf.tree","aj.global.bone.front.decendant","aj.global.bone.front.decendant.locator","aj.global.bone.front.tree","aj.global.bone.head3.child","aj.global.bone.head3.child.locator","aj.global.bone.head3.decendant","aj.global.bone.head3.decendant.locator","aj.global.bone.head3.tree","aj.global.bone.top.decendant","aj.global.bone.top.decendant.locator","aj.global.bone.top.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.mount","aj.new"]}
execute as @n[ type=minecraft:item_display, tag=aj.new, tag=aj.billy.locator.mount, distance=..3 ] run function animated_java:billy/zzz/summon/as_data_entity/as_locator/mount
data modify entity @s data.uuids.locator_mount set from storage aj:uuid main.out
data modify entity @s data.locators.mount.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.mouthb] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_mouthb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.head3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.bottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bottom set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.frontleftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontleftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.bottom2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bottom2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.frontrightleg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontrightleg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.front] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.top] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.waist] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_waist set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.helmet] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_helmet set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.chestplate_arm_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_chestplate_arm_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.chestplate_arm_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_chestplate_arm_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.chestplate_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_chestplate_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.leggings_pants] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_leggings_pants set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.leggings_lower_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_leggings_lower_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.boots_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_boots_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.lower_right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_lower_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.leggings_upper_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_leggings_upper_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.leggings_lower_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_leggings_lower_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.boots_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_boots_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.lower_left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_lower_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.leggings_upper_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_leggings_upper_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.blb] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_blb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.backleftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_backleftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.brb] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_brb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.billy.node.backrightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_backrightleg set from storage aj:uuid main.out